### ISSUE TITLE
LP1832678: Automated power-management/lid test

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#103]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1832678

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2019-06-13 07:03:10	| 6	| Medium	| False  	|

## Description
[Summary]
power-management/lid test is a manual test case. Tester need to verify "Does closing your laptop lid cause your system to suspend?". We used to rely on power/suspend led to judge whether system goes to suspend. However most of recent hardware does not have power/suspend led, so we need to check kernel log or dmesg to confirm system went into suspend when lid closed. 
Seems it could be checking by checkbox and judging automatically.

We could check "suspend entry" and "suspend exit" in dmesg
[ 4072.715038] PM: suspend entry (s2idle)
[ 4072.788286] Suspending console(s) (use no_console_suspend to debug)
[ 4076.456427] PM: suspend exit
or kernel log
Jun 13 14:34:45 u-Precision-5530 kernel: [ 4072.715038] PM: suspend entry (s2idle)
Jun 13 14:34:53 u-Precision-5530 kernel: [ 4072.715039] PM: Syncing filesystems ... done.
Jun 13 14:34:53 u-Precision-5530 kernel: [ 4072.784927] Freezing user space processes ... (elapsed 0.002 seconds) done.
Jun 13 14:34:53 u-Precision-5530 kernel: [ 4072.787197] OOM killer disabled.
Jun 13 14:34:53 u-Precision-5530 kernel: [ 4072.787197] Freezing remaining freezable tasks ... (elapsed 0.001 seconds) done.
Jun 13 14:34:53 u-Precision-5530 kernel: [ 4072.788286] Suspending console(s) (use no_console_suspend to debug)
Jun 13 14:34:53 u-Precision-5530 kernel: [ 4076.366232] OOM killer enabled.
Jun 13 14:34:53 u-Precision-5530 kernel: [ 4076.366232] Restarting tasks ... done.
Jun 13 14:34:53 u-Precision-5530 kernel: [ 4076.403313] thermal thermal_zone11: failed to read out thermal zone (-61)
Jun 13 14:34:53 u-Precision-5530 kernel: [ 4076.456427] PM: suspend exit
 
[Steps to reproduce]

[Expected result]

[Actual result]

[Failure rate]

[Additional information]
GPU: 00:02.0 VGA compatible controller: Intel Corporation Device 3e9b
system-manufacturer: Dell Inc.
CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12x)
system-product-name: Precision 5530
kernel-version: 4.18.0-21-generic
bios-version: 1.6.0

## Attachments
[snap_list.log](https://api.launchpad.net/devel/bugs/1832678/+attachment/5270513/data)
[checkbox-session.tgz](https://api.launchpad.net/devel/bugs/1832678/+attachment/5270514/data)
[acpidump.log](https://api.launchpad.net/devel/bugs/1832678/+attachment/5270515/data)
[sosreport-u-Precision-5530-20190613150319.tar.gz](https://api.launchpad.net/devel/bugs/1832678/+attachment/5270516/data)

Tags:
['ce-qa-concern', 'checkbox', 'test-case']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~jerry.kao wrote on 2019-06-13 07:03:29:
Automatically attached

##### https://launchpad.net/~jerry.kao wrote on 2019-06-13 07:03:45:
Automatically attached

##### https://launchpad.net/~jerry.kao wrote on 2019-06-13 07:03:49:
Automatically attached

##### https://launchpad.net/~jerry.kao wrote on 2019-06-13 07:03:57:
Automatically attached

**Comment by yphus** [comment]
Duplicate of https://github.com/canonical/checkbox/issues/65
