### ISSUE TITLE
LP1853549: disk_xxx tests will be failed when the image mounted on sd card

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#107]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1853549

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2019-11-22 02:26:20	| 6	| Medium	| False  	|

## Description
Platform: armv7l
Type: Freescale i.MX6 Quad/DualLite
Image: both ubuntu server and ubuntu core 18

Description:
There are two sd slots on iMX6. One is mounted for image (mmcblk1), the other is storage (mmcblk2)
When running disk_xxx tests, they will test on mtdblock0 and failed.

bettyl@localhost:~$ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
mtdblock0    31:0    0     2M  0 disk
mmcblk1     179:0    0   3.7G  0 disk
|-mmcblk1p1 179:1    0   256M  0 part /boot/uboot
`-mmcblk1p2 179:2    0   3.5G  0 part /writable

C3 test link:
https://certification.canonical.com/hardware/201908-27262/submission/154743/test/84354/result/11718405/

## Attachments
No attachments

Tags:
['ce-qa-concern']

**Comment by pieqq** [comment]
There was no more recent issues with this, and this platform has been issued a certificate already. Closing this issue.
