### ISSUE TITLE
LP1855300: Network test needs to focus on advertized speeds, not supported speeds

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#108]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1855300

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2019-12-05 15:57:51	| 8	| Medium	| False  	|

## Description
As we've learned, chipsets can be rate limitied and while a chipset may support one speed, it's max advertized may be lower. For example:
Settings for enP8p1s0:
	Supported ports: [ FIBRE ]
	Supported link modes:   1000baseKX/Full 
	                        10000baseKX4/Full 
	                        10000baseKR/Full 
	                        40000baseCR4/Full 
	                        40000baseSR4/Full 
	                        56000baseCR4/Full 
	                        56000baseSR4/Full 
	Supported pause frame use: Symmetric Receive-only
	Supports auto-negotiation: Yes
	Supported FEC modes: Not reported
	Advertised link modes:  1000baseKX/Full 
	                        10000baseKX4/Full 
	                        10000baseKR/Full 
	                        40000baseCR4/Full 
	                        40000baseSR4/Full 
	Advertised pause frame use: Symmetric
	Advertised auto-negotiation: Yes
	Advertised FEC modes: Not reported
	Speed: 40000Mb/s
	Duplex: Full
	Port: Direct Attach Copper
	PHYAD: 0
	Transceiver: internal
	Auto-negotiation: off
	Supports Wake-on: d
	Wake-on: d
	Current message level: 0x00000014 (20)
			       link ifdown
	Link detected: yes

Currently the Network script will fail if the detected network speed is lower than the max. The intention was to verify network speed against the advertised max, but it seems to be checking against the supported max instead.  For example, this controller failed:

ERROR:root:Detected link speed (40000) is lower than detected max speed (56000)
ERROR:root:Check your device configuration and try again.
ERROR:root:If you want to override and test despite this under-speed link, use
ERROR:root:the --underspeed-ok option.

It advertises 40Gb max, and is connected on a 40Gb link, yet failed because the chipset supported max says 56Gb.

SO, we need to fix this to do two things:

1:  It needs to compare the link speed to the advertized max speed, NOT the supported max speed.
2:  We need to know when advertised and supported are different, so it should drop a warning if the advertised max is different than the supported max (higher OR lower).

## Attachments
No attachments

Tags:
[]

**Comment by pieqq** [comment]
I moved the Jira card to the Server Cert board: https://warthogs.atlassian.net/browse/SERVCERT-1458

This should be handled by the Server Cert team directly. PRs welcomed! \o/
