### ISSUE TITLE
Some issues with test case power-management/lid_close_suspend_open

### ISSUE THREAD

**Issue by eugene-yujinwu** [canonical/checkbox#1080]
### Bug Description

There are some issues related to the test case [power-management/lid_close_suspend_open](https://github.com/canonical/checkbox/blob/44498aa07112594d4634a94af9be4134b9977128/providers/base/units/power-management/jobs.pxu#L158):

1. A typo that make the test steps jump from 3 to 5.

2. There is a [HoldoffTimeoutSec](https://www.freedesktop.org/software/systemd/man/latest/logind.conf.html#HoldoffTimeoutSec=) which will "Specifies a period of time after system startup or system resume in which systemd will hold off on reacting to lid events....Defaults to 30s. " So if we run this test just after a resume from suspend, it will failed.  Please see LP bugs: [LP:2042406](https://bugs.launchpad.net/somerville/+bug/2042406),[ LP:2047136](https://bugs.launchpad.net/sutton/+bug/2047136). Maybe we need add some notes to make the tester aware of this information.

3. This test case seems to be redundant with another test case [power-management/lid](https://github.com/canonical/checkbox/blob/44498aa07112594d4634a94af9be4134b9977128/providers/base/units/power-management/jobs.pxu#L99C5-L99C25). Each of them listed in the test plan [after-suspend-graphics-integrated-gpu-cert-manual ](https://github.com/canonical/checkbox/blob/a12b050c58e8440285f2eb6ab4409ebfeea46d03/providers/base/units/graphics/test-plan.pxu#L122), so it's recursively included in the test plan client-cert-desktop-22-04-manual. Maybe we can remove one of them.

4. A improvement suggestion from Kent: Maybe we could move this test case away from the suspend_advanced_auto test case, to avoid the situation that run this test case just after the resume from suspend. 

### To Reproduce

checbox-cli run com.canonical.certification::power-management/lid_close_suspend_open

### Environment

checkbox: 4.0.0.dev139. Lenovo Desktop OEM image 1016-oem kernel

**Comment by zongminl** [comment]
This has been fixed by #1093
