### ISSUE TITLE
LP1861658: suspend/cpu_before_suspend sometimes failed on system set with on-demand governor

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#109]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1861658

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2020-02-03 09:12:31	| 6	| Medium	| False  	|

## Description
Found following issue on dragonboard:
https://bugs.launchpad.net/ubuntu/bionic/+source/linux-snapdragon/+bug/1860527

If the system is set to on-demand governor, the attributes in /sys/devices/system/cpu/cpu0/cpufreq/ won't be there until demanded, so the test will fail if it runs at that time.

## Attachments
No attachments

Tags:
[]

**Comment by pieqq** [comment]
The source issue about sysfs has been marked as invalid. Closing this issue.
