### ISSUE TITLE
LP1864017: Checkbox failed to clear dmesg buffer while running "thunderbolt3/daisy-chain" test

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#110]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1864017

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Confirmed	| 2020-02-20 09:21:04	| 6	| Medium	| False  	|

## Description
[Summary]
While running "thunderbolt3/daisy-chain" test, the console shows following message.
It seems to me that the checkbox doesn't have permission to run the "dmesg -C" command.

```
-------------[ Running job 14 / 195. Estimated time left: unknown ]-------------
------[ Daisy-chain testing for Thunderbolt 3 storage and display device ]------
ID: com.canonical.certification::thunderbolt3/daisy-chain
Category: com.canonical.plainbox::disk
PURPOSE:
    This test will check if your system can support daisy-chaining of a storage
    and a monitor over Thunderbolt 3 port
STEPS:
    1. Connect your Thunderbolt monitor to your systems
    2. Connect and mount your Thunderbolt HDD to another Thunderbolt 3 port of the
       monitor (you can do this with HDD first as well)
    3. Click 'Test' to perform the storage test on the Thunderbolt HDD
VERIFICATION:
    1. The verification for storage is automated, please select the result combine
       with the result for the display.
    2. Was the desktop displayed correctly on the Thunderbolt-connected screen?
Pick an action
    => press ENTER to continue
  c => add a comment
  s => skip this job
  q => save the session and quit
[csq]: 
... 8< -------------------------------------------------------------------------
dmesg: klogctl failed: Operation not permitted
Found the following mounted scsi partitions:
    /dev/nvme3n1p1 : /media/u/HP P800 : None bits/s
--------------------
Traceback (most recent call last):
  File "/tmp/nest-ac2szmjv.f72a97acc7625ebde274d683a4ac49e1c7d149a2e1b42de99e910da270a15ed7/removable_storage_test", line 885, in <module>
    sys.exit(main())
  File "/tmp/nest-ac2szmjv.f72a97acc7625ebde274d683a4ac49e1c7d149a2e1b42de99e910da270a15ed7/removable_storage_test", line 733, in main
    subprocess.check_output(['dmesg', '-C'])
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['dmesg', '-C']' returned non-zero exit status 1.
```

[Steps to reproduce]
1. Install the checkbox
2. Run the daisy-chain test or the following command
   $ checkbox-cli run thunderbolt3/daisy-chain

[Expected result]
The dmesg buffer can be cleaned

[Actual result]
The console pops up following message
"dmesg: klogctl failed: Operation not permitted"

[Failure rate]
3/3

[Additional information]
SKU: RAT5-DVT1-C3X 
Image: somerville-bionic-amd64-iso-hybrid-20190418-59
Manifest: canonical-oem-somerville-bionic-amd64-20190418-59+beaver-osp1-gendry+X41
system-manufacturer: Dell Inc.
system-product-name: Precision 7550
bios-version: 0.3.19
CPU: Genuine Intel(R) CPU 0000 @ 2.80GHz (16x)
GPU: 00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:3e9b] (rev 02)
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation Device [10de:1fb8] (rev a1)
kernel-version: 5.0.0-1038-oem-osp1
checkbox-ng: 1.7.0
checkbox-support: 0.44.0
com.canonical.ce:oem: 1.0
certification-client: 0.39.0
plainbox-provider-checkbox: 0.51.0
plainbox-provider-resource-generic: 0.43.0
plainbox-provider-sru: 1.16.0
plainbox-provider-tpm2: 1.12.0

## Attachments
[snap_list.log](https://api.launchpad.net/devel/bugs/1864017/+attachment/5329718/data)
[acpidump.log](https://api.launchpad.net/devel/bugs/1864017/+attachment/5329719/data)
[sosreport-u-27528-20200220042111.tar.gz](https://api.launchpad.net/devel/bugs/1864017/+attachment/5329720/data)

Tags:
['ce-qa-concern', 'oem-other']

**Comment by pieqq** [comment]
Fixed already (31ea560bc1), issue was not closed.
