### ISSUE TITLE
LP1871046: Use vkcube to smoke test Vulkan support

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#111]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1871046

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Triaged	| 2020-04-06 08:17:12	| 6	| Medium	| False  	|

## Description
vkcube to Vulkan is like glxgears to OpenGL.

Let's use vkcube as a smoke test to Vulkan support.

It's in vulkan-tools package.

## Attachments
No attachments

Tags:
[]

**Comment by pieqq** [comment]
Closing this in GitHub since it's an enhancement and should be tracked in Jira only.
