### ISSUE TITLE
`check_audio_deamon.sh` naming isn't changed to match real file name

### ISSUE THREAD

**Issue by hanhsuan** [canonical/checkbox#1117]
### Bug Description

#1087 is fixed the typo for `check_audio_deamon.sh` and changed to `check_audio_daemon.sh`. However #1087 isn't fixed the naming in the suspend.pxu at the same time.

[submission](https://certification.canonical.com/hardware/202401-33398/submission/362100/test/102/result/40046101/)

### To Reproduce

Run job `suspend/audio_before_suspend` and `suspend/audio_after_suspend_auto`

### Environment

- OS: jammy
- Checkbox type: debian
- Checkbox version: 4.0.0.dev194

### Relevant log output

```shell
bash: line 1: check_audio_deamon.sh: command not found
```

**Comment by zongminl** [comment]
Closing this issue for it has been fixed by #1121
