### ISSUE TITLE
Checkbox couldn't recognize job failed

### ISSUE THREAD

**Issue by hanhsuan** [canonical/checkbox#1122]
### Bug Description

The condition of #1117 shows that checkbox couldn't recognize this job should be marked as failed. This behavior could be found in [graphics/1_gl_support](https://certification.canonical.com/hardware/202401-33397/submission/362354/test/200240/result/40073727/) that worked [before](https://certification.canonical.com/hardware/202401-33399/submission/354087/test/206378/result/39028089/).

### To Reproduce

1. modify the `suspend/audio_before_suspend` to naming miss match
2. run `suspend/audio_before_suspend` test

### Environment

- OS: jammy
- checkbox type: debian
- checkbox version: 4.0.0.dev194

**Comment by zongminl** [comment]
Fixed by #1247 and #1268
