### ISSUE TITLE
Unable rotate the built-in display to "Portrait Right" and "Portrait Left" while external monitor be connected

### ISSUE THREAD

**Issue by baconYao** [canonical/checkbox#1126]
### Bug Description

# Problem

In Baoshan Project, there are several display combinations, the most common (default) one is `built-in DSI` + `external HDMI`.

A Checkbox job, `graphics/1_rotation_{graphic}` is in charge of verifying the screen rotation.

**Pass**

The screen of built-in DSI panel can be rotated successfully

**FAIL**

After plugging the external monitor through HDMI cable, the built-in DSI panel can only be rotated to two Orientation (Landscape and Landscape flipped)

Video Record: https://drive.google.com/file/d/1S_yFmkajYFRef67Xp5QZEtST7cqjlKdx/view?usp=sharing

- Pass
  - Time `00:00 - 00:40`
  - Rotated to 4 orientation successfully
- Fail
  - Time `00:45 - 01:30`
  - Connect the HDMI monitor
  - Rotated to 2 orientation only (Landscape and Landscape flipped)
  - Submission: https://certification.canonical.com/hardware/202308-31931/submission/362461/test-results/fail/
    - Log
      ```
      Unable rotate the built-in DSI panel to Right and Left while external monitor (HDMI / type-c DP) be connected
      setting rotation to right
      Logical monitors not adjacent
      D-Bus error: Logical monitors not adjacent (org.freedesktop.DBus.Error.InvalidArgs)
      setting rotation to inverted
      setting rotation to left
      D-Bus error: Logical monitors not adjacent (org.freedesktop.DBus.Error.InvalidArgs)
      Logical monitors not adjacent
      setting rotation to normal
      Using output: DSI-1
       ```

### To Reproduce

1. Install Checkbox on DUT via the following commmands
```
$ sudo snap install checkbox22 --beta
$ sudo snap install checkbox --beta --classic
```

2. Run case via Host machine
```
$ checkbox.checkbox-cli control <IP of DUT>
```

3. Choose `Desktop Preload Certification Tests for 22.04 (Manual Tests)` test plan
4. Run `graphics/1_rotation_drm-platform-mediatek-drm_4_auto` job

### Environment

OS: Jammy Desktop
Checkbox Type: Snap
Checkbox Snap version: checkbox22 4.0.0-dev194 867
Devices: Baoshan G1200, G700 and G510

**Comment by zongminl** [comment]
Display rotation should only be tested on the internal display, close this issue as this is invalid test case to test when an external display is connected.
