### ISSUE TITLE
LP1881861: automatic gpu testing cases for amdgpu is out of date

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#113]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1881861

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2020-06-03 07:48:03	| 8	| Medium	| False  	|

## Description
so far we use DRI_PRIME=1 to make all amdgpu driver (pro stack, non-pro stack, in-kernel amdgpu) rendering.

So, there's some part of automatical dgpu test cases [1][2] is waiting for revising otherwise in-kernel amdgpu will not be verified.

There're some related code there, but not yet understand why it works: https://git.launchpad.net/plainbox-provider-checkbox/tree/bin/graphics_env#n25

So far, I get an error from testing in-kernel amdgpu:

graphics/1_auto_switch_card_Vega_10_XT__Radeon_PRO_SSG_	not supported			job cannot be started: resource expression "graphics_card.driver in ['nvidia', 'amdgpu-pro', 'pcieport']" evaluates to false
graphics/1_gl_support_Vega_10_XT__Radeon_PRO_SSG_	not supported			job cannot be started: resource expression "package.name == 'nux-tools'" evaluates to false

[1] https://git.launchpad.net/plainbox-provider-checkbox/tree/units/graphics/jobs.pxu#n525
[2] https://git.launchpad.net/plainbox-provider-resource/tree/bin/graphics_card_resource#n132

## Attachments
No attachments

Tags:
[]

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~alextu wrote on 2020-06-03 07:49:27:
Just found the automatical test cases not yet support well on amdgpu driver, I just dump the find there and plan to fix it when I have sparse time.

##### https://launchpad.net/~chihchun wrote on 2020-10-29 10:35:03:

On Somerville projects, the factory image always shipped in performance mode for estar. 
This test job should be fixed and apply to the machines that installed with the factory image, in order to verify if there is a regression with dGPU.

**Comment by pieqq** [comment]
This has been done already when we revamped the amdgpu tests back in 2022. Closing this issue.
