### ISSUE TITLE
LP1882782: core release shows as a point release in submissions

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#114]
This issue was migrated from https://bugs.launchpad.net/checkbox-support/+bug/1882782

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2020-06-09 13:51:33	| 6	| Medium	| False  	|

## Description
When we parse the "distribution" element in a submission, we're seeing "release" elements with a decimal as though they were not core releases. It causes problems on our end. Nothing is on fire, but the results from parsing submissions on our end get miscategorized.

For example,

"distribution": {
  "codename": "bionic",
  "description": "Ubuntu Core 18",
  "distributor_id": "Ubuntu",
  "release": "18.04"
},

## Attachments
No attachments

Tags:
[]

**Comment by yphus** [comment]
Looking at recent [submissions](https://certification.canonical.com/hardware/202103-28853/submission/311534/), the issue seems to be fixed:

```
    "distribution": {
        "codename": "unknown",
        "description": "Ubuntu Core 20",
        "distributor_id": "Ubuntu Core",
        "release": "20"
    },
```
