### ISSUE TITLE
LP1889195: serial-automated test plan only recognizes configs defined in the launcher

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#115]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1889195

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2020-07-28 11:05:54	| 6	| Medium	| False  	|

## Description
[Background info]

1) serial-automated test plan[1] includes one test - serial/loopback-{dev}[2].

2) the job serial/loopback-{dev} requires the following prerequisites to be run:
a) the resource job 'serial_ports_static'[3] bootstrap_included in the same test plan

b) "SERIAL_PORT_STATIC = /dev/ttyS0 /dev/ttyS1" defined in configuration files that are to be parsed by the resource job serial_ports_static

[Issue]
When attempting to nest serial-automated plan in to a larger test plan, the tests within it do not get recognized unless $SERIAL_PORT_STATIC is specified in the launcher.

Specifying $SERIAL_PORT_STATIC in any of the other locations where all other config settings are set[4] would not work.

[Checkbox]
checkbox version:
checkbox18 v1.15 rev 1137

---------------------------------------------------------
[1] https://git.launchpad.net/plainbox-provider-checkbox/tree/units/serial/test-plan.pxu#n17

[2] https://git.launchpad.net/plainbox-provider-checkbox/tree/units/serial/jobs.pxu#n25

[3] https://git.launchpad.net/plainbox-provider-resource/tree/jobs/resource.pxu#n422

[4] https://trello.com/c/zb8knYjM/923-as-a-checkbox-snap-user-i-want-there-to-be-one-checkboxconf-file-location-that-is-used-in-all-circumstances-so-i-can-be-very-con

## Attachments
No attachments

Tags:
['ce-qa-concern']

**Comment by pieqq** [comment]
This sounds like a Checkbox config issue that was fixed 2 years ago. Closing this for now, if the problem happens, please open a new issue.
