### ISSUE TITLE
keys/power-button-event auto skip on 24.04

### ISSUE THREAD

**Issue by scotthu27** [canonical/checkbox#1152]
### Bug Description

keys/power-button-event is a manual case for checking the long-press physical power button event has reported correctly or not
It used to get the acpid which is not pre-install on noble, suggest to set checkbox dependency to pre-install it.

### To Reproduce

run keys/power-button-event

### Environment

OS: noble
checkbox type: debian
checkbox version: 4.0.0.dev194

### Relevant log output

```shell
job cannot be started: resource expression "package.name == 'acpid'" evaluates to false
```

**Comment by zongminl** [comment]
- Conclusion between CE and OEMQA is to skip this test when running the desktop certification test plan.
- ODM will verify this feature on their side.
- The acpid is not available in Ubuntu nobel archive.
