### ISSUE TITLE
LP1895337: Mediacard/sd-preinserted-server Fails When Previously Skipped

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#117]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1895337

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Confirmed	| 2020-09-11 17:56:19	| 8	| Medium	| False  	|

## Description
I have noticed on the Dell PowerEdge T440 that the mediacard/sd-preinserted-server test failed on the 20.04 and previously it was skipped on 18.04.   This test was run on the same system.  

20.04
mediacard/sd-preinserted-server	blocker	fail	ERROR:root:No removable drives were detected, aborting

18.04
mediacard/sd-preinserted	None	skip	job cannot be started: resource expression "manifest.has_card_reader == 'True'" evaluates to false

A media card slot is not present on this server and I think this could be a test case issue.

## Attachments
No attachments

Tags:
[]

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~bladernr wrote on 2020-09-11 19:03:18:
It skipped because there is no resource job that says "I have a media reader" installed.

It's definitely an issue, but this test will fail on literally everything because there's no constraint.  The 18.04 version has an equally bad design because "manifest.has_card_reader" is simply the product of reading a manually crafted text file that cannot be automated.

The manifest file isnt' generated by hardware probing, it is created by the tester at test time.

To resolve this, we need to find a resource that identifies media card readers, and then create a constraint similar to the ones we have for other resources (like constraints based on arch, or on presense of SSD, or whatever).

##### https://launchpad.net/~bladernr wrote on 2020-09-18 14:15:04:
The ultimate fix for this is to add/create a resource that can be used as a job constraint ... like "media_reader == yes" or something like that.

The Devices Team method of using a manually crafted manifest is not workable for server which is mostly automated and depends on accurate, programmatic probing of hardware to decide what to test or not to test.



##### https://launchpad.net/~meribold wrote on 2021-06-04 10:32:01:
Skipping tests based on hardware probing would be risky if it's possible that a kernel or other update introduces a real regression that breaks memory card reader detection.  For the Taipei cert. lab we write the manifest when setting up a new machine.  This isn't a huge amount of effort since any machine will likely be in the lab for years and the manifest only has to be created once per machine.  Is your situation different?

**Comment by Hook25** [comment]
Closing as duplicated in https://github.com/canonical/checkbox/issues/118
