### ISSUE TITLE
Under Ubuntu 24.04, installing canonical-certification-server requires user interaction

### ISSUE THREAD

**Issue by rodwsmith** [canonical/checkbox#1171]
### Bug Description

When installing canonical-certification-server in Ubuntu 24.04, apt presents a "Configuring iperf3" text-mode dialog:

```
│ Choose this option if Iperf3 should start automatically as a daemon, now  │ 
│ and at boot time.                                                         │ 
│                                                                           │ 
│ Start Iperf3 as a daemon automatically?                                   │ 
│                                                                           │ 
│                    <Yes>                       <No> 
```

This is OK if it's happening at the console; but if it's being installed automatically (as part of a Testflinger deployment, say), it leaves the package unconfigured, which then prevents further APT actions until the issue is resolved.

I'm not sure if this is really best handled as a Checkbox bug, or should be dealt with by adapting other projects.

### To Reproduce

1. Install Ubuntu 24.04
2. `sudo add-apt-repository pp:checkbox-dev/stable`
3. `sudo apt install canonical-certification-server`

### Environment

* Ubuntu 24.04.
* Tested on two systems -- notso (in DRN) and brennan (one of my own computers)
* APT packaging

**Comment by rodwsmith** [comment]
I've verified that installing iperf3 alone, before installing c-c-s, does the same thing.

**Comment by bladernr** [comment]
As a workaround (noted in email), you can try this:

 sudo DEBIAN_FRONTEND=noninteractive apt install iperf3

which should squash the user interactivity.  (Note, you may need to do this with apt-get, I'm not sure if apt will listen to that setting or not.

**Comment by Hook25** [comment]
Hello, I just found this while browsing jira. I don't see how this is a Checkbox issue, we depend on iperf3, if you install with an interactive frontend, it asks for some confirmation. Please do switch to a non interactive apt frontend if you don't desire this. 

If you have a suggestion on how we could avoid this at a checkbox level, feel free to ping me and reopen the issue
