### ISSUE TITLE
LP1901512: A file/list/document that collects all user configurable variables

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#121]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1901512

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2020-10-26 10:18:59	| 8	| Medium	| False  	|

## Description
Currently there is no way to get an overview of all user configurable variables in checkbox.
The most easily accessible configurable variables are the ones already exposed in plainbox.conf, but that list is not exhaustive. 

If a user adds a new job into their test plan, they have no way of knowing if that new job requires a variable to be configured (and how that variable is to be set) unless they have certain knowledge of where within the checkbox structure this info is located.

It would be great if a list of these variables is collected somewhere, with the following info provided:

* The variable name themselves
* Which jobs use these variables
* A short summary of what to set to a variable and/or what it's for

## Attachments
No attachments

Tags:
['ce-qa-concern']

**Comment by kissiel** [comment]
The situation got greatly improved last year, so I'm allowing myself to close this one. If you find any particular thing missing please file issues.
