### ISSUE TITLE
LP1904670: usb/storage-detect fails with no error message when USB drive has no partitions

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#122]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1904670

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2020-11-18 04:49:14	| 6	| Medium	| False  	|

## Description
When a machine has a USB drive with no partitions, usb/storage-detect fails and doesn't produce any output indicating why it failed:

----------------------------[ Running job 10 / 25 ]-------------------
------------[ Detect storage partitions on a device on the USB bus ]--
ID: com.canonical.certification::usb/storage-detect
Category: USB tests
----------------------------------------------------------------------
----------------------------------------------------------------------
Outcome: job failed

I would expect that usb/storage-detect either succeeds or produces an error message indicating that it requires a partition to exist on the USB drive.

## Attachments
No attachments

Tags:
[]

**Comment by pieqq** [comment]
This has been fixed recently. If it's not the case, please reopen an issue with all the usual information (Ubuntu version, USB partitions, etc.)
