### ISSUE TITLE
LP1906766: The checkbox needs the root permission to run "thunderbolt3/daisy-chain"

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#123]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1906766

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Triaged	| 2020-12-04 05:53:10	| 10	| Medium	| False  	|

## Description
[Summary]
The checkbox needs the root permission to run "thunderbolt3/daisy-chain". Otherwise, it popped up the error message.
- "ERROR: This script must be run as root!"

# Test case:
plugin: user-interact-verify
category_id: com.canonical.plainbox::disk
id: thunderbolt3/daisy-chain
imports: from com.canonical.plainbox import manifest
requires: manifest.has_thunderbolt3 == 'True'
flags: also-after-suspend-manual
estimated_duration: 45.0
command: removable_storage_test.py -s 268400000 scsi
_summary: Daisy-chain testing for Thunderbolt 3 storage and display device
_description:
 PURPOSE:
     This test will check if your system can support daisy-chaining of a storage
     and a monitor over Thunderbolt 3 port
 STEPS:
     1. Connect your Thunderbolt monitor to your systems
     2. Connect and mount your Thunderbolt HDD to another Thunderbolt 3 port of the
        monitor (you can do this with HDD first as well)
     3. Click 'Test' to perform the storage test on the Thunderbolt HDD
 VERIFICATION:
     1. The verification for storage is automated, please select the result combine
        with the result for the display.
     2. Was the desktop displayed correctly on the Thunderbolt-connected screen?

[Steps to reproduce]
1. Power on the system
2. Install the checkbox
3. Run the following command to test system-low-power idle
   $ checkbox-cli run thunderbolt3/daisy-chain

[Expected result]
The daisy-chain can work properly

[Actual result]
The checkbox needs the root permission to run "thunderbolt3/daisy-chain".

[Failure rate]
2/2

[Additional information]
SKU: STRA-DVT2-C7
Manifest: canonical-oem-somerville-focal-amd64-20200502-85+fossa-bronn+X43
system-manufacturer: Dell Inc.
system-product-name: Precision 5750
bios-version: 1.5.0
CPU: Intel(R) Xeon(R) W-10855M CPU @ 2.80GHz (12x)
GPU: 00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:9bf6] (rev 05)
01:00.0 3D controller [0302]: NVIDIA Corporation Device [10de:1fb8] (rev a1)
kernel-version: 5.6.0-1035-oem

## Attachments
No attachments

Tags:
[]

**Comment by Hook25** [comment]
This job is now correctly marked with `user: root`
