### ISSUE TITLE
Checkbox snap installed from 20.04/beta channel requires checkbox16

### ISSUE THREAD

**Issue by zongminl** [canonical/checkbox#1236]
### Bug Description

When trying to install checkbox snap from 20.04/beta channel, an error message popped up:
```
$ sudo snap install checkbox --channel=20.04/beta --classic
error: cannot perform the following tasks:
- Run configure hook of "checkbox" snap if present (run hook "configure": 
-----
You need to install the checkbox16 snap.

You can do this with this command:
snap install checkbox16
-----)
```

While the correct dependency checkbox20 snap has been installed on the system:
```
$ snap list checkbox20
Name        Version       Rev   Tracking     Publisher            Notes
checkbox20  4.0.0-dev270  1786  latest/beta  ce-certification-qa  -
```

After checking the snap info it seems that there are some snap packages have been published to wrong channels:
```
  uc20/beta:        4.0.0-dev270 2024-05-07 (6930) 28kB classic
  20.04/beta:       4.0.0-dev270 2024-05-07 (6930) 28kB classic
  16.04/beta:       4.0.0-dev270 2024-05-07 (6930) 28kB classic
```

### To Reproduce

1. Install checkbox20 snap from beta channel `$ sudo snap install checkbox20 --beta`
2. Install checkbox snap from 20.04/beta channel `$ sudo snap install checkbox --channel=20.04/beta --classic`
3. Check the snap information of checkbox `$ snap info checkbox`

### Environment

- OS: 20.04 Desktop
- Checkbox Type: Snap
- Checkbox Version: 4.0.0-dev270

**Comment by Hook25** [comment]
Thank you for reporting this. Should be fixed now
