### ISSUE TITLE
LP1908961: some device not have vid/pid in it's nature, and that shouldn't be failure

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#124]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1908961

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2020-12-22 02:11:49	| 8	| Medium	| False  	|

## Description
per test case com.canonical.certification::miscellanea/device_check,
if VID/PID is missing, it will be treated as a failure.

Some devices will provide virtual UART and connect the device there.

For such a device, this test case will always fail, which is wrong.

Ex:

path: /devices/pci0000:00/0000:00:1e.0/dw-apb-uart.4/serial0/serial0-0/bluetooth/hci0
bus: bluetooth
category: BLUETOOTH

and they won't have vid/pid by it's nature.

## Attachments
[udevadm-info--e.log](https://api.launchpad.net/devel/bugs/1908961/+attachment/5449161/data)

Tags:
['oem-priority', 'originate-from-1908385', 'somerville']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~sylvain-pineau wrote on 2021-01-04 08:36:11:
Could you please attach the output of `udevadm info -e`. It will help to fix the udev parser

##### https://launchpad.net/~ycheng-twn wrote on 2021-01-04 09:23:00:
the log captured on the target machine.

**Comment by kissiel** [comment]
The PID/VID situation got a few patches over the last 3 years, so this probably got fixed too.
If the problem persists, feel free to re-open this ticket.
