### ISSUE TITLE
LP1913397: Add cpufreq resource job (skip test)

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#126]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-resource/+bug/1913397

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2021-01-27 08:47:04	| 6	| Medium	| False  	|

## Description
Add cpufreq resource job to to skip test if cpufreq scaling is non-supported.

## Attachments
No attachments

Tags:
[]

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~bladernr wrote on 2021-01-28 04:13:47:
Added PPC task as well and assigned to Adrian.  This will require creating the resource and then modifying the job description in PPC to utilize that resource.

**Comment by kissiel** [comment]
This got ultimately fixed here:
https://code.launchpad.net/~alanec/plainbox-provider-checkbox/+git/plainbox-provider-checkbox/+merge/400086
