### ISSUE TITLE
ethernet/hotplug-.* failed due to unable to ping the host

### ISSUE THREAD

**Issue by LiaoU3** [canonical/checkbox#1260]
### Bug Description

[ethernet/hotplug-eth0](https://certification.canonical.com/hardware/202311-32317/submission/371615/test/112526/result/41212712/) failed, however, the function is well indeed.

submission: https://certification.canonical.com/hardware/202311-32317/submission/371615/

### To Reproduce

1. sudo snap install checkbox24 --beta
2. sudo snap install checkbox --channel 24.04/beta
3. checkbox.checkbox-cli
4. Select `client-cert-iot-server-24-04-manual`
5. Select `Ethernet Hotplut Test`

### Environment

 - OS: Server 24.04
 - Checkbox Type: Snap
 - Checkbox Version: 4.0.0-dev264
 - Hardware: KV260 Rev2 ([202311-32317](https://certification.canonical.com/hardware/202311-32317/submission/371615/))

### Relevant log output

```shell
Press enter and unplug the ethernet cable from the port eth0 of the System.
After 15 seconds plug it back in.
Checkbox session may be interrupted but it should come back up.
Waiting for cable to get disconnected.
....Cable unplugged!
Waiting for the cable to get connected.
......Cable detected!
ERROR:root:Could not find def gateway info in /proc
Failed to find a host to ping on interface eth0
FAIL: Unable to ping any host with the above interfaces
```

**Comment by baconYao** [comment]
Same issue can be reproduced on UC22 as well

Failure rate: 100%

Baoshan
- G1200: https://certification.canonical.com/hardware/202307-31859/submission/375967/test-results/fail/?term=ethernet%2Fhotplug-eth0
- G700: https://certification.canonical.com/hardware/202308-31931/submission/375968/test-results/fail/?term=ethernet%2Fhotplug-eth0
- G350: https://certification.canonical.com/hardware/202309-32029/submission/375952/test-results/fail/?term=ethernet%2Fhotplug-eth0

**Comment by Hook25** [comment]
Dumb question could this be because we try right after detecting the re-plugging connectivity? I think a few retries with some exponential backoff can't be bad in this situation while we just `detect connected && check connection`, which is not optimal. What do you think? Can you just run this command and see if running the second one a few seconds from the first fixes this?

**Comment by LiaoU3** [comment]
This is duplicated to #1197
