### ISSUE TITLE
LP1919473: Wrong mapping the cpu codename of Intel i7-8665UE processor

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#128]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1919473

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Triaged	| 2021-03-17 15:17:30	| 6	| Medium	| False  	|

## Description
The checkbox report recognize Intel Core i7-8665UE as "Kaby Lake"[0], but it should be Whiskey Lake based on Intel ARK database[1].

It seems we have a wrong mapping in bin/inxi_snapshot[2].

[0] 
% grep "kaby lake" attachment_files/com.canonical.certification__system_info_json
13:        "Model: Intel Core i7-8665UE arch: Kaby Lake "

[1] Whiskey Lake - https://ark.intel.com/content/www/us/en/ark/products/193554/intel-core-i7-8665ue-processor-8m-cache-up-to-4-40-ghz.html
[2] https://git.launchpad.net/plainbox-provider-checkbox/tree/bin/inxi_snapshot?h=v0.57.0#n7839

## Attachments
No attachments

Tags:
['cbox-22']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~bladernr wrote on 2021-03-17 15:40:53:
FYI bin/cpuid.py in checkbox also does this by getting the CPUID return from the processor and checking the ID string to determine the CPU family.

I do not add much desktop CPUs, and currently it only has AMD and Intel CPUs, but feel free to add to it.

Interestingly, inxi_snapshot does not recognize my i7 as Skylake...

bladernr@galactica:~/development/plainbox-provider-checkbox/bin$ ./inxi_snapshot 
CPU: Quad Core Intel Core i7-6700K (-MT MCP-) speed/min/max: 4114/800/4200 MHz Kernel: 5.4.0-67-generic x86_64 Up: 12d 18h 15m 
Mem: 25962.2/62406.9 MiB (41.6%) Storage: 6.08 TiB (28.2% used) Procs: 652 Shell: bash 5.0.17 inxi: 3.0.27 
bladernr@galactica:~/development/plainbox-provider-checkbox/bin$ ./cpuid.py 
CPU Model: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
CPUID: 0x506e3 which appears to be a Skylake processor


##### https://launchpad.net/~sylvain-pineau wrote on 2021-04-28 10:15:57:
@Jeff even with ./inxi_snapshot -C -xx ??

Inxi snapshot is https://github.com/smxi/inxi/blob/1639125a176cd56aa913937b59b8bed48749f7c2/inxi :

my $self_version='3.0.27';
my $self_date='2018-10-14';

We could evaluate a refresh of it from master:

my $self_version='3.3.04';
my $self_date='2021-04-16';

Two jobs are currently depending on inxi:
- system-info-json
- raw_device_dmi (to get bios mode info - legacy or uefi)

##### https://launchpad.net/~bladernr wrote on 2021-05-03 22:23:28:
Eh... I wish I was able to follow up on this but my skylake MB died and I ended up having to upgrade the whole thing to a newer Comet Lake CPU/MB.

But on that one... I get N/A for arch:
bladernr@galactica:~/development/plainbox-provider-checkbox/bin$ ./inxi_snapshot -C -xx
CPU:       Topology: 10-Core model: Intel Core i9-10900F bits: 64 type: MT MCP arch: N/A L2 cache: 20.0 MiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 111997 
           Speed: 4903 MHz min/max: 800/5200 MHz Core speeds (MHz): 1: 4903 2: 4896 3: 4911 4: 4927 5: 4889 6: 4945 7: 4968 
           8: 4945 9: 4912 10: 4907 11: 4920 12: 4886 13: 4735 14: 4950 15: 4930 16: 4972 17: 4924 18: 4909 19: 4896 20: 4919 

the latest inxi from github does identify my Comet Lake CPU:
bladernr@galactica:~/development/inxi$ ./inxi -C -xx
CPU:       Info: 10-Core model: Intel Core i9-10900F bits: 64 type: MT MCP arch: Comet Lake rev: 5 cache: L2: 20 MiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 111997 
           Speed: 4934 MHz min/max: 800/5200 MHz Core speeds (MHz): 1: 4934 2: 4994 3: 4895 4: 4946 5: 4902 6: 4988 7: 4909 
           8: 4906 9: 4922 10: 4929 11: 4995 12: 4964 13: 4941 14: 4998 15: 4928 16: 4999 17: 4974 18: 4992 19: 4991 20: 4998

And also seems to have better differentiation between Kaby Lake, Coffee Lake, Comet Lake and Whiskey Lake

https://github.com/smxi/inxi/blob/master/inxi#L9833

So just updating inxi should work then.

**Comment by kissiel** [comment]
The list in the provider is up to date right now. If there's anything missing feel free to reopen this issue.
