### ISSUE TITLE
Import `gi` error on checkbox24 arm

### ISSUE THREAD

**Issue by LiaoU3** [canonical/checkbox#1288]
### Bug Description

The job [graphics/{index}_minimum_resolution_{product_slug}](https://github.com/canonical/checkbox/blob/49aee5ee6c933dc9a7ea0c4e55aeaffde4db8e41/providers/base/units/graphics/jobs.pxu#L114) caused python library `gi` import error.
I tried this test on another amd64 desktop 24.04 machine, I did not observe this issue.

Submission: https://certification.canonical.com/hardware/202311-32348/submission/374565/test/204072/result/41628747/

### To Reproduce

1. Run the job graphics/{index}_minimum_resolution_{product_slug}

### Environment

 - OS: Desktop 23.10
 - Checkbox Type: Snap
 - Checkbo version: 4.0.0-dev297

### Relevant log output

```shell
Traceback (most recent call last):
  File "/tmp/nest-exa88i62.81db9b9ec044f8b8e5d21ff3570f86a5d3e81043b6f239e30951b5c0c9e3a603/resolution_test.py", line 3, in <module>
    import gi
  File "/snap/checkbox24/current/usr/lib/python3/dist-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: /snap/checkbox24/current/usr/lib/aarch64-linux-gnu/libgirepository-1.0.so.1: undefined symbol: g_once_init_leave_pointer
```

**Comment by Hook25** [comment]
Is it possible that this is also due to the fact that you are using checkbox24 on 23.10? Can you try to reproduce this on 24.04?

**Comment by LiaoU3** [comment]
I can reproduce this issue on [202406-34099](https://certification.canonical.com/hardware/202406-34099/) with 23.10 image.
https://certification.canonical.com/hardware/202406-34099/submission/376082/

However, it is not reproducible on 24.10
https://certification.canonical.com/hardware/202406-34099/submission/376108/

Hence, this should because of the fact that we test on 23.10
Close this issue.
