### ISSUE TITLE
LP1947632: Improve DCPMM tests

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#130]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1947632

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| In Progress	| 2021-10-18 20:45:30	| 6	| Medium	| False  	|

## Description
Add new tests to improve testing DCPMMs

## Attachments
No attachments

Tags:
['cbox-28', 'servcert-214']

**Comment by pieqq** [comment]
Marked as Rejected in Jira, closing it.
