### ISSUE TITLE
LP1948383: manifest has_bt_adapter ignored when running bluetooth/detect job (UC20, CDTS)

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#131]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1948383

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Confirmed	| 2021-10-22 06:20:08	| 6	| Medium	| False  	|

## Description
[Summary]

$ snap list
Name Version Rev Tracking Publisher Notes
cdts 0.8 186 uc20/stable ce-certification-qa devmode
checkbox20 1.23 621 latest/stable ce-certification-qa -

Using CDTS to test a device without a BT adapter.

When asked by Checkbox if device has a BT adapter, I select "No". In the Manifest, it shows as:

$ cdts.checkbox-cli run com.canonical.plainbox::manifest
===========================[ Running Selected Jobs ]============================
--------------[ Running job 1 / 1. Estimated time left: 0:00:01 ]---------------
-----------------------------[ Hardware Manifest ]------------------------------
ID: com.canonical.plainbox::manifest
Category: com.canonical.plainbox::uncategorised
... 8< -------------------------------------------------------------------------
ns: com.canonical.certification
name: certification-client

ns: com.canonical.certification
name: plainbox-provider-checkbox
has_audio_playback:
has_audio_capture:
has_audio_loopback_connector:
has_bt_adapter: False
has_bt_smart:
has_rpi_camera:
has_camera:
has_ethernet_adapter: True
has_fingerprint_reader:
gpio_loopback:
has_i2c: True
has_special_keys:
has_card_reader:
has_muxpi_hdmi:
socket_can_echo_server_running:
has_thunderbolt:
has_thunderbolt3:
has_touchscreen:
has_tpm_chip:
has_usb_type_c:
has_usb_storage: True
has_hardware_watchdog: True
has_wlan_adapter: False
has_wwan_module: False

ns: com.canonical.certification
name: plainbox-provider-docker

ns: com.intel.ipdt
name: plainbox-provider-ipdt

ns: com.canonical.certification
name: plainbox-provider-resource-generic

ns: com.canonical.certification
name: plainbox-provider-snappy

ns: com.canonical.certification
name: plainbox-provider-tpm2
has_tpm2_chip:

------------------------------------------------------------------------- >8 ---
Outcome: job passed

The Bluetooth detect job requires the "has_bt_adapter":

$ cdts.checkbox-cli list 'all-jobs' -f "{id}, {requires}\n" | grep bluetooth/detect
bluetooth/detect, manifest.has_bt_adapter

However, if I run it, instead of being skipped because it does not match the requirements, it's executed and fails:

$ cdts.checkbox-cli run .*bluetooth/detect
(...)
--------------[ Running job 2 / 2. Estimated time left: 0:00:02 ]---------------
------------[ Make sure at least one bluetooth device is detected ]-------------
ID: com.canonical.certification::bluetooth/detect
Category: com.canonical.plainbox::bluetooth
... 8< -------------------------------------------------------------------------
No bluetooth adatpers registered with rfkill
------------------------------------------------------------------------- >8 ---
Outcome: job failed

[Additional information]
CID: 202109-29496
SKU:
Image: 20211020.4
system-manufacturer: AAEON
system-product-name: UPN-EHL01
bios-version: UNEHAM0D
CPU: Intel Atom(R) x6425RE Processor @ 1.90GHz (4x)
GPU: 00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:4571] (rev 01)
kernel-version: 5.13.0-1007-intel

[Stage]
Issue reported and logs collected right after it happened

## Attachments
[checkbox-session.tgz](https://api.launchpad.net/devel/bugs/1948383/+attachment/5535062/data)
[snap_list.log](https://api.launchpad.net/devel/bugs/1948383/+attachment/5535063/data)
[acpidump.log](https://api.launchpad.net/devel/bugs/1948383/+attachment/5535064/data)
[sosreport-ubuntu-2021-10-22-fondyuq.tar.gz](https://api.launchpad.net/devel/bugs/1948383/+attachment/5535065/data)

Tags:
['202109-29496', 'cbox-29', 'checkbox', 'ehl', 'ehl-aaeon', 'ihv-intel', 'iotg', 'test-case']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~pieq wrote on 2021-10-22 06:20:51:
Automatically attached

##### https://launchpad.net/~pieq wrote on 2021-10-22 06:20:56:
Automatically attached

##### https://launchpad.net/~pieq wrote on 2021-10-22 06:21:13:
Automatically attached

##### https://launchpad.net/~pieq wrote on 2021-10-22 06:21:23:
Automatically attached

**Comment by pieqq** [comment]
CDTS not used anymore, closing.
