### ISSUE TITLE
Two almost identical 'Stress Tests' lead to some confusion

### ISSUE THREAD

**Issue by eugene-yujinwu** [canonical/checkbox#1319]
### Bug Description

There are two almost same "Stress Tests" folder in the test plan and test reports, one is "Stress Tests", the other one is "Stress tests" . It's not clear what's difference between these two item, for  which will case some confusion.
Please see attached screenshot.
![Stress-tests-cate](https://github.com/canonical/checkbox/assets/117058060/7db01084-901d-4552-87aa-784991bd8eb4)
![Stress-Test](https://github.com/canonical/checkbox/assets/117058060/fda561b6-f665-462b-98be-6ec9059a1149)

### To Reproduce

1. Launch checkbox with command: checkbox-cli control 127.0.0.1
2. Choose the test plan "Desktop Preload Certification Tests for 22.04 (Stress Tests)"

### Environment

Checkbox type: Debian
Version: 4.0.0.dev271

**Comment by tomli380576** [comment]
For anyone working on this, 
- the id of "Stress tests" is `stress-cert-full`, from [this file](https://github.com/canonical/checkbox/blob/main/providers/base/units/stress/test-plan.pxu#L1)
- the id of "Stress Tests" is `stress-tests`, from [this file](https://github.com/canonical/checkbox/blob/main/providers/base/units/stress/boot.pxu#L8)

**Comment by zongminl** [comment]
This has been fixed by #1368
