### ISSUE TITLE
The audio/detect_sinks based on incorrect manifest entry

### ISSUE THREAD

**Issue by andrejvelichkovski** [canonical/checkbox#1329]
### Bug Description

The `audio/detect_sinks` test is currently based on the `has_audio_playback` manifest entry. This seems to be incorrect, as this machine has a playback and passes all other audio tests but fails this one.

I believe this test should be based on another manifest entry.

Please let us know if you are making this change, so that we can organise the effort to update the manifest for this entry, as it will likely affect other jobs running in the lab.

### To Reproduce

1. Launch checkbox SRU test plan on a ASRock iEP-5000G Industrial PC (202211-30899)

### Environment

- OS: Ubuntu 22.04.4
- Checkbox Type: Deb
- Checkbox Version: 4.0.1~dev2~ubuntu22.04.1
- Hardware tested: Audio

### Relevant log output

```shell
Daemon is pulseaudio, use pulseaudio function
No available sinks found
```

**Comment by pieqq** [comment]
`has_audio_playback` and `has_audio_capture` manifest are very unclear, unfortunately.

I think the best reading for them is:

- `has_audio_playback`: is the device capable of rendering sound? On a desktop, it probably means there is a line-out port **and** speakers are connected to it
- `has_audio_capture`: is the device capable of recording sounds? On a desktop or a device without embedded microphones, there might be a line-in port, but a microphone needs to be connected to it.

**Comment by mz2** [comment]
These are good definitions, please document the manifest entries with these definitions.

We may separately add more granular capabilities (for example built-in mic) but these are good definitions for the terms in use right now.
