### ISSUE TITLE
LP1984668: Add  Sapphire Rapids Support to CPUID Script 

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#133]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1984668

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| In Progress	| 2022-08-10 21:51:25	| 6	| Medium	| False  	|

## Description
The cpuid script does not identify Sapphire Rapids CPUs.  

Update the script to identify Sapphire Rapids CPUs

First identifiied ID (output of the cpuid.py script):
CPU Model: Intel(R) Xeon(R) Platinum 8480+ Unable to determine CPU Family for this CPUID: 0x806f8

## Attachments
No attachments

Tags:
[]

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~mreed8855 wrote on 2022-08-10 21:52:57:
I have created a fix in this branch

https://code.launchpad.net/~mreed8855/plainbox-provider-checkbox/+git/plainbox-provider-checkbox/+ref/sapphire_rapids_cpuid

##### https://launchpad.net/~bladernr wrote on 2022-08-15 13:30:35:
Hold on merging this for now, until I've checked something upstream

##### https://launchpad.net/~mreed8855 wrote on 2022-09-19 15:40:46:
I have included the MP for this and the branch in comment #1 is no longer needed.

https://code.launchpad.net/~mreed8855/plainbox-provider-checkbox/+git/plainbox-provider-checkbox/+merge/430110

**Comment by pieqq** [comment]
Merged in Launchpad, closing.
