### ISSUE TITLE
LP1987412: Update SRU Server Tests

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#134]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1987412

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| In Progress	| 2022-08-23 15:15:07	| 6	| Medium	| False  	|

## Description
More cleanup of server SRU suite

## Attachments
No attachments

Tags:
[]

**Comment by Hook25** [comment]
Closing as it is unclear what should be done to clean up the SRU suite, if this is still relevat, please re-open and add all relevant details
