### ISSUE TITLE
The scripts of thunderbolt test cases had changed and didn't change all related test case

### ISSUE THREAD

**Issue by hanhsuan** [canonical/checkbox#1344]
### Bug Description

The #930 has changed the scripts of thunderbolt test cases and didn't change all related test case, such as [dock/all-init-thunderbolt3-insert](https://github.com/canonical/checkbox/blob/5b51df12f792b992b79a52d8f304f714c5fa3670/providers/base/units/dock/jobs.pxu#L2638), [dock/all-init-thunderbolt3-remove](https://github.com/canonical/checkbox/blob/5b51df12f792b992b79a52d8f304f714c5fa3670/providers/base/units/dock/jobs.pxu#L2687) and [dock/all-init-thunderbolt3-storage-automated](https://github.com/canonical/checkbox/blob/5b51df12f792b992b79a52d8f304f714c5fa3670/providers/base/units/dock/jobs.pxu#L2663).

Using the script `run_watcher.py` is working.

### To Reproduce

1. Run checkbox docking test
2. Select thunderbolt related test cases

### Environment

- OS: 22.04, 24.04
- Checkbox type: debian and snap
- Checkbox version: 4.0.1.dev2

**Comment by hanhsuan** [comment]
@fernando79513 Is that possible to fix this in your PR #1291 ? Thanks.

**Comment by fernando79513** [comment]
I modified the jobs in PR [#1291](https://github.com/canonical/checkbox/pull/1291) to include also the modified scripts
