### ISSUE TITLE
Add new CPUID of AMD Raphael to cpuid.py

### ISSUE THREAD

**Issue by Shixiong0** [canonical/checkbox#1349]
### Enhancement Proposal

Hi, 

We're now testing 24.04 with AMD Raphael CPU, but I find there is no this cpu id when running the cpuid case, could you help to add the cpuid to the script as the CPU we're using is the GAed level:

AMD Raphael | 0xa60f12

Thanks.

**Comment by Hook25** [comment]
Thank you for reporting this, I've added the cpuid to the list, should be there once the pr is merged
