### ISSUE TITLE
LP1987412: Update SRU Server Tests

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#135]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-certification-server/+bug/1987412

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| In Progress	| 2022-08-23 15:15:21	| 6	| Medium	| False  	|

## Description
More cleanup of server SRU suite

## Attachments
No attachments

Tags:
[]

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~beliaev-maksim wrote on 2022-11-28 16:31:02:
Bug was migrated to GitHub: https://github.com/canonical/checkbox/issues/134.
Bug is no more monitored here.

**Comment by Hook25** [comment]
Closed as duplicated in https://github.com/canonical/checkbox/issues/134
