### ISSUE TITLE
LP1768283: Unable to test aliased network devices

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#136]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1768283

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Confirmed	| 2018-05-01 15:44:06	| 6	| Low	| False  	|

## Description
Checkbox is not able to test aliased network devices because they are not picked up as network devices.

For example: https://certification.canonical.com/hardware/201604-21859/submission/129686/

That is an s390 LPAR... it actually has two devices when you look at ifconfig:

ubuntu@s1lp10-jefflane:~$ ifconfig
encc000: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::ff:fe9e:c7db  prefixlen 64  scopeid 0x20<link>
        ether 02:00:00:9e:c7:db  txqueuelen 1000  (Ethernet)
        RX packets 990175  bytes 1364564738 (1.3 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 166123  bytes 43865301 (43.8 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

encc000.2653: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.245.236.10  netmask 255.255.255.0  broadcast 10.245.236.255
        inet6 fe80::ff:fe9e:c7db  prefixlen 64  scopeid 0x20<link>
        ether 02:00:00:9e:c7:db  txqueuelen 1000  (Ethernet)
        RX packets 208851  bytes 1317138318 (1.3 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 165619  bytes 43167449 (43.1 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

The problem here is that encc000 is the physical device, but in configuring it, the actual device used for passing traffic is the enccc000.2653 device which is a virtual device.

So when the test runs it fails to see encc000.2653 and only sets up a test for encc000 which, of course, fails because it's not directly configured.

For now this is a very corner case, and certainly not a high priority, but it would be nice to resolve this issue at some point so we can test these things adequately.

## Attachments
No attachments

Tags:
[]

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~bladernr wrote on 2018-05-02 14:19:37:
FWIW, I talked to Frank about this, thinking it was just a configuration that could be changed easily. Turns out this config method is pretty common in s390x deployments when LPARs are all sharing the same network device but connecting to multiple VLANs.  So, unfortunately, we do need to sort out how to ensure this gets tested, rather than just ask for a different network configuration on my LPAR.

That said, this is also s390x specific so setting it Low was the right call, IMO.

##### https://launchpad.net/~kissiel wrote on 2019-09-05 11:43:22:
What do you mean by 'Checkbox is not able to test'? Targeting Slave with remote? Some job fails to see the target?

##### https://launchpad.net/~bladernr wrote on 2019-09-05 13:44:33:
Checkbox fails to recognize the alias device (encc000.2653) as a network device and test it.  Because encc000.2653 is ignored by checkbox, network tests on the Z Lpar always fail, as checkbox tries to use encc000 to test instead, which is not possible.

The NIC itself, as discussed in comment 1, is passed through to several LPARs (as it was described to me), and each LPAR creats an alias for that NIC, but the guest OS on the LPAR can apparently see the passed-through physical device, but cannot address it directly (because doing so would make it unusable for other machines that had access to it).





##### https://launchpad.net/~bladernr wrote on 2020-12-18 17:31:45:
Not expired, this is still an issue and affects every time I do testing on s390 (IBM Z).

**Comment by pieqq** [comment]
Very old issue, very low importance, closing it.
