### ISSUE TITLE
miscellanea/kernel_taint_test failed with kernel tainted

### ISSUE THREAD

**Issue by Shixiong0** [canonical/checkbox#1367]
### Bug Description

We're test AMD Turin system with Ubuntu 24.04, and got the fail of the case "miscellanea/kernel_taint_test", I'd like to know what caused the kernel tainted? Is it acceptable for Ubuntu?
The returned value of the tainted is 512.

### To Reproduce

1. depoly the 24.04 into the AMD Turin system
2. execute the command: certify-ubuntu-server
3. check the log when the test done, the case of "miscellanea/kernel_taint_test" failed
Kernel taint value is 512
![kernel tainted](https://github.com/user-attachments/assets/783b03e6-f760-4cc0-abab-1430cab7a640)

Taint bit value: 9 (kernel issued warning)

### Environment

1. OS Ubuntu 24.04
2. Checkbox 4.1.0
3. CPU: AMD Turin Eng Sample

**Comment by Hook25** [comment]
Hello, I don't think this is a Checkbox issue. Please do refer to the [Tainted Kernel](https://docs.kernel.org/admin-guide/tainted-kernels.html) documentation page to debug why the kernel is tainted and possibly solve that. I don't know what exactly you are trying to do so I can't help you further on this, please feel free to re-open this if you think that the test is flawed.
