### ISSUE TITLE
LP1803652: Add a "after" job for system-trigger-reset to undo sysrq change

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#137]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1803652

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Confirmed	| 2018-11-16 03:58:09	| 6	| Low	| False  	|

## Description
To solve bug #1802459 we will modify the system setting that allows the triggering of a kernel panic from user space. We should create a job with an "after" field dependency on this job to ensure that this configuration is removed again after the test is completed.

## Attachments
No attachments

Tags:
[]

**Comment by pieqq** [comment]
Closing this issue as it was raised in 2018 with a low priority.
