### ISSUE TITLE
LP1808290: dkms-build-exclusive-test is failed on AMD graphic

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#138]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1808290

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Confirmed	| 2018-12-13 08:04:37	| 6	| Low	| False  	|

## Description
Checkbox always show error below when execute "dkms-build-exclusive-test"

Beginning DKMS BUILD_EXCLUSIVE Test
ERROR: amdgpu-pro-dkms does not have BUILD_EXCLUSIVE

This case should not check amdgpu-pro-dkms due to it come from AMD, and AMD replied on Jira:
https://bugs.launchpad.net/somerville/+bug/1791051/comments/22

## Attachments
[com.canonical.ce__somerville_dkms-build-exclusive-test.stderr](https://api.launchpad.net/devel/bugs/1808290/+attachment/5221867/data)
[com.canonical.ce__somerville_dkms-build-exclusive-test.stdout](https://api.launchpad.net/devel/bugs/1808290/+attachment/5221869/data)

Tags:
['ce-qa-concern']

**Comment by pieqq** [comment]
We don't test amdgpu-pro anymore, closing this.
