### ISSUE TITLE
`stress-tests/hibernate-{s4_iterations}-cycles-log-check` shouldn't be executed while `stress-tests/hibernate_{{ s4_iterations }}_cycles` is skipped

### ISSUE THREAD

**Issue by hanhsuan** [canonical/checkbox#1382]
### Bug Description

While stress testing, the  `stress-tests/hibernate-{s4_iterations}-cycles-log-check` is executed while `stress-tests/hibernate_{{ s4_iterations }}_cycles` is skipped. However, There is no log and `stress-tests/hibernate-{s4_iterations}-cycles-log-check` is failed always.

### To Reproduce

Run client-cert-iot-server-24-04-stress test plan

### Environment

- OS Ubuntu server 24.04
- Checkbox Type Snap
- Checkbox Version 4.0.0.dev333

### Relevant log output

[submission](https://certification.canonical.com/hardware/202405-34047/submission/384085/test-results/?term=hibernate)

**Comment by zongminl** [comment]
Fixed by #1483
