### ISSUE TITLE
Add new CPUID of AMD Turin to cpuid.py

### ISSUE THREAD

**Issue by Shixiong0** [canonical/checkbox#1384]
### Enhancement Proposal

Hi, we're running Ubuntu certification tests on systems that based on AMD Turin platform, we find there is no correct cpuid in the cpuid.py which leads to the failure of the case:

CPU Model: AMD EPYC 9655 96-Core Processor
Unable to determine CPU Family for this CPUID: <__main__.CPUID object at 0x7482e33bb440>

The AMD Turin CPU is PR stepping, which is regard as the production level ones. Could you help to add the cpuid into the script?

Attached the html log for your reference. Thanks.
[Uploading submission 1.zip…]()

**Comment by Hook25** [comment]
Please do provide the correct CPUID and I will add it to the list

**Comment by Shixiong0** [comment]
Hi, will double check the CPUID and feedback to you.

Thanks.

**Comment by Shixiong0** [comment]
> Please do provide the correct CPUID and I will add it to the list

Hi, I checked the CPUID and the correct one I think is:

CPUID |  0x00b00f21

Please help to add it into the cpuid.py script, many thanks.
