### ISSUE TITLE
LP1834219: underspeed test fails 

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#140]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1834219

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2019-06-25 16:04:41	| 6	| Low	| False  	|

## Description
network tests using the underspeed option are still failing, though they should pass regardless of observed throughput.

Sample: https://certification.canonical.com/hardware/201708-25649/submission/144030/test-results/fail/

## Attachments
No attachments

Tags:
[]

**Comment by pieqq** [comment]
Old, low priority, no clear description. Closing.
