### ISSUE TITLE
Get maas version failed during test

### ISSUE THREAD

**Issue by Shixiong0** [canonical/checkbox#1414]
### Bug Description

We got an error during the certification test, the case miscellanea/get_maas_version failed to say:

Installation data source is
http://12.12.12.10:5248/MAAS/metadata/
MAAS server's IP address is 12.12.12.10
ERROR: The MAAS version cannot be determined
FAIL: System appears to have not been installed by MANIACS-compliant MAAS

Would you please help to check what caused the failure? Or if more log needed, just let me know, Thanks.

### To Reproduce

1. setup maas server
2. deploy the SUT with 24.04
3. run certify-ubuntu-server

### Environment

OS: 24.01
MAAS: 3.4.3

**Comment by bladernr** [comment]
Was this MAAS server deployed using our script that configures evrerything (maas-cert-server) or is this a MAAS installation you set up manually without using our setup script?

**Comment by Shixiong0** [comment]
Yes, we followed the official guide to setup maas:

1. sudo snap install maas
2. sudo apt-add-repository ppa:checkbox-dev/stable
3. sudo apt install maas-cert-server
4. sudo maniacs-setup

is there any wrong step?

**Comment by Shixiong0** [comment]
Hold on, I'll double confirm with our tester about the steps.
