### ISSUE TITLE
LP1852643: cpu_topology test should not run on s390x

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#143]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1852643

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2019-11-14 21:16:44	| 6	| Low	| False  	|

## Description
cpu_topology should not run on s390x.  There has been some changes to how CPUs are presented in newer models of s390x via proc/cpuinfo and sysfs.  Because of this, the cpu topology test will always fail.

Need to revert what I did before that enabled topology on s390x in bug #1558838

## Attachments
No attachments

Tags:
[]

**Comment by kissiel** [comment]
It landed here
https://code.launchpad.net/~alanec/plainbox-provider-checkbox/+git/plainbox-provider-checkbox/+merge/394995
