### ISSUE TITLE
LP1859940: Need test cases for WPA3 

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#145]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1859940

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Triaged	| 2020-01-16 08:40:40	| 6	| Low	| False  	|

## Description
WPA3 will be introduced in 20.04 Focal, so we need new test cases cover WPA3:

 - WPA3 cases with 802.11 b/g/n/ac/ax
 - Before and after suspend

## Attachments
No attachments

Tags:
['cq-qa-concern']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~narahuang wrote on 2020-01-16 09:45:39:
We can check WPA3 key management by:
sudo wpa_cli status | grep key_mgmt
If it's "SAE" then it's WPA3, not WPA2.

##### https://launchpad.net/~jocave wrote on 2020-06-10 18:20:07:
In what way is it introduced in Focal? From the wpa_supplicant changelog it seems to have first been introduced in 2014-02-04 - v2.1

**Comment by kissiel** [comment]
Landed in 925033156a
