### ISSUE TITLE
Manual test items exist in automation client-cert-odm-desktop-24-04-automated

### ISSUE THREAD

**Issue by ianchangc** [canonical/checkbox#1457]
### Bug Description

When customer executing client-cert-odm-desktop-24-04-automated, the process would be suspended by

- keys/sleep
- led/power-blink-suspend	
- led/suspend	

 and wait for user's input.
These should be in Manual test. Please remove them from auto.

### To Reproduce

1. Install checkbox 4.1.0 stable
2. execute com.canonical.certification::client-cert-odm-desktop-24-04-automated   

### Environment

Ubuntu desktop 24.04
Checkbox 4.1.0

**Comment by zongminl** [comment]
Fixed by #1462
