### ISSUE TITLE
LP1886810: fwts tests need stdout to prevent TF output timeout

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#146]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1886810

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2020-07-08 11:37:08	| 6	| Low	| False  	|

## Description
Tests like firmware/fwts_desktop_diagnosis can take a long time to run to completion and because they have been written to output completely to a log file they can exceed the timeout used by TF to catch hung jobs.

If you check the log file in the session data directory the tests appear to have been running fine. Is it possible to output some basic status lines to stdout so that we can make it obvious that the job is running ok? 

11:29:58 ----------------------------[ Running job 23 / 82 ]-----------------------------
11:29:58 ----------[ Run FWTS QA-concerned desktop-specific diagnosis tests. ]-----------
11:29:58 ID: com.canonical.certification::firmware/fwts_desktop_diagnosis
11:29:58 Category: Firmware tests
11:29:58 --------------------------------------------------------------------------------
11:59:58 
11:59:58 ERROR: Output timeout reached! (1800s)

## Attachments
No attachments

Tags:
[]

**Comment by pieqq** [comment]
Not a checkbox issue. Closing.
