### ISSUE TITLE
Missing pm-graph pkg in 24.04 noble, and stress/s2idle_pm-graph_30 stress/s3_pm-graph_30 will be skipped.

### ISSUE THREAD

**Issue by seankingyang** [canonical/checkbox#1463]
### Bug Description
There is no `pm-grah` deb pkg in 24.04 [noble](https://launchpad.net/~checkbox-dev/+archive/ubuntu/beta/+index?field.series_filter=noble), andi it will make test job: `stress/s2idle_pm-graph_30 stress/s3_pm-graph_30` to be skipped ( [Skipped Submission](https://certification.canonical.com/hardware/202312-33263/submission/390633/test-results/skipped/)).

Please help to build the `pm-graph` deb pkg in noble series, or this test case (pm_graph) test case should be removed in 24.04.

```
ubuntu@localhost:~$ sudo apt policy pm-graph
pm-graph:
  Installed: (none)
  Candidate: (none)
  Version table:
ubuntu@localhost:~$ ubuntu-report | grep Version
  "Version": "24.04",
```

### To Reproduce

1. Install 2404 desktop image
2. install checkbox dev version
3. checkbox-cli run com.canonical.certification::stress/s2idle_pm-graph_30

### Environment

- OS 2404 Desktop image
- Any version of checkbox deb version.

**Comment by Hook25** [comment]
I have imported the new pmgraph version in all ppas, please check that this did fix the issue

**Comment by seankingyang** [comment]
The pm-graph pkg can be found in 24.04.

```
ubuntu@ubuntu:~$ sudo apt policy pm-graph 
pm-graph:
  Installed: 5.8-1+202409262109+9190832~ubuntu24.04.1
  Candidate: 5.8-1+202409262109+9190832~ubuntu24.04.1
  Version table:
 *** 5.8-1+202409262109+9190832~ubuntu24.04.1 500
        500 https://ppa.launchpadcontent.net/checkbox-dev/beta/ubuntu noble/main amd64 Packages
        100 /var/lib/dpkg/status

```

Mark this issue closed~~
