### ISSUE TITLE
miscellanea/cpuid fails with unusual output

### ISSUE THREAD

**Issue by rodwsmith** [canonical/checkbox#1472]
### Bug Description

In a recent submission, the miscellanea/cpuid test failed with the following output:

```
CPU Model: Intel(R) Xeon(R) 6766E
Unable to determine CPU Family for this CPUID: <__main__.CPUID object at 0x715cff1b7530>
```

This looks like it may be a problem parsing the output of this CPU's information, but I haven't fully traced it (and might not be able to without access to a system that shows the symptoms).

The relevant certificate request is:

https://certification.canonical.com/certificates/2409-16076/

### To Reproduce

1. Run `certify-ubuntu-server` (or presumably anything else that causes miscellanea/cpuid to run) on an affected system (Intel Xeon 6766E, presumably; maybe others...?).

### Environment

- Ubuntu 24.04
- Intel Xeon 6766E CPU

### Relevant log output

```shell
CPU Model: Intel(R) Xeon(R) 6766E
Unable to determine CPU Family for this CPUID: <__main__.CPUID object at 0x715cff1b7530>
```

**Comment by Hook25** [comment]
Please check if this is still current in a recent version of checkbox and feel free to reopen it
