### ISSUE TITLE
drop image/model-grade test for platforms that we test with dangerous images

### ISSUE THREAD

**Issue by amalinowski75** [canonical/checkbox#1479]
### Enhancement Proposal

This example test: http://10.102.156.15:8080/job/cert-cm4l-arm64-pi-kernel-24-beta/7/testReport/com.canonical/certification__image_model-grade/com_canonical_certification__image_model_grade/
most likely shouldn't be run. This discussion seconds the idea: https://chat.canonical.com/canonical/pl/fnyu6xj5yty39kbapkr69zohoy

**Comment by omar-selo** [comment]
For reference, here are other (non RPI) environments that we're testing with dangerous images:
```
aaeon-lookout-canyon-ehl
aaeon-lookout-canyon-tgl
dawson-j-uc24
zhongyi
```
