### ISSUE TITLE
CPUID Incorrectly Returns Siena for Bergamo

### ISSUE THREAD

**Issue by mreed8855** [canonical/checkbox#1502]
### Bug Description

In a recent submission, the cpuid test returned the incorrect cpuid.  Siena was returned instead of Bergamo

The relevant certificate request is:
https://certification.canonical.com/certificates/2407-15946/

### To Reproduce

1. Run certify-ubuntu-server (or presumably anything else that causes miscellanea/cpuid to run) on an affected system

### Environment

1. Ubuntu 24.04
2. CPU Model: AMD EPYC 9754 128-Core Processor
3. C245 M8

### Relevant log output

```shell
CPU Model: AMD EPYC 9754 128-Core Processor 
CPUID: 0xaa0f02 which appears to be a AMD Siena SP6 processor
```

**Comment by Hook25** [comment]
https://github.com/canonical/checkbox/issues/946

This is the source of that CPU id, is it wrong?
