### ISSUE TITLE
LP1872040: Attach journal to checkbox

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#155]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1872040

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2020-04-10 09:37:42	| 6	| Wishlist	| False  	|

## Description
Recently we've received a few requests to have journals included in checkbox as attachments to easily compare the current logs with those of previous images and/or checkbox runs.

Ideally this would be either (1) journal outputs saved as a file that we can easily retrieve inside submission.tar.xz, or (2) having it listed in a job's i/o output, or (3) having it somewhere inside the device's c3 submission page.

## Attachments
No attachments

Tags:
['ce-qa-concern']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~hyac109 wrote on 2020-04-10 09:41:37:
snippets of related discussion 

<spineau> snap set core service.rsyslog.disable=false
<robertliu> spineau, on uc18, the option was removed. there is no rsyslogd in core18.
<spineau> ah
<robertliu> you can just 'mkdir /var/log/journal && reboot'
...
<robertliu> maybe restart journald also apply the setting.
...
<robertliu> spineau, btw, journalctl can show a time range of logs. it's not necessary to include all logs.
<spineau> robertliu: we could record the session start to use it later as a marker, I'm already doing that for connections tests where I want to extract logs for NM/MM only for the time window of the corresponding test, e.g:
<spineau> https://git.launchpad.net/plainbox-provider-checkbox/tree/units/wwan/jobs.pxu#n40
<spineau> setting an arbitrary value won't work for sure even if the average is ~2h for lab runs
<robertliu> spineau, cool


##### https://launchpad.net/~pieq wrote on 2020-12-07 07:55:08:
Recently faced a similar request from SWE/WHE for lp:1902668.

While investigating this issue (a systemd service fails to start, leading to a test case failure in Checkbox), we wanted to check if it was a regression of some sort.

For now, there might be several culprits:

1. The new image has a regression (missing driver) that leads to this error
2. The new image has some new configuration that lead this error (e.g. service should not be there at all, but is there and system tries to start it)
3. The failing Checkbox test case has been recently modified to include items that were not taken into account in the past

I wanted to compare the kernel logs or the list ofsystemd services, but none of these are available in the submission archive. Note that, for that specific case, only consistency matters (i.e. *when* the log gathering is done – at the beginning of Checkbox run for instance).

**Comment by pieqq** [comment]
Marked as enhancement, it will be tracked on Jira. Closing this issue here.
