### ISSUE TITLE
LP1936681: [remote] if connection lost, would be nice if it displayed what test was running

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#157]
This issue was migrated from https://bugs.launchpad.net/checkbox-ng/+bug/1936681

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Confirmed	| 2021-07-16 16:38:32	| 10	| Wishlist	| False  	|

## Description
I've configured a CDTS master to run an automated test set against a DUT.

I'm now at home and wanted to check on the progress of the tests but all I see is a screen of "Reconnecting..."

I know some tests require the DUT to reboot or otherwise lose connection for a bit, but other times there's a situation that prevents the DUT from ever coming back. (in this case, I probably forgot to change something in the BIOS.)

It's for this reason that it'd be nice if CDTS displayed which test was waiting for reconnection.  This way when I address the issue with the DUT, I know which test to start with.  Or if it's an issue, I know which test to tell the engineers to run for debugging.

## Attachments
No attachments

Tags:
['cdts']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~jocave wrote on 2021-08-06 09:56:55:
@Doug here is an example of a test run being carried out and the connection to the SUT being lost:

18:11:12 ---------------------------[ Running job 101 / 139 ]----------------------------
18:11:12 --------------------------------[ Warm reboot ]---------------------------------
18:11:12 ID: com.canonical.certification::power-management/warm-reboot
18:11:12 Category: Power Management tests
18:11:12 --------------------------------------------------------------------------------
18:11:12 Connection lost!
18:11:12 connection closed by peer
18:11:12 Reconnecting...
18:11:12 Reconnecting...
18:11:12 Reconnecting...
18:11:12 Reconnecting...
18:11:12 Reconnecting...

So the information is there about what the test run was doing. It sounds like you are describing a different scenario. Could you provider more details?

##### https://launchpad.net/~djacobs98 wrote on 2021-08-11 06:16:28:
In the office, I have a separate laptop set up as the CDTS master and run CDTS in a screen session.

This way I can monitor the test session even when I'm at home and don't have to worry about my laptop's network connection interfering with the test run.

I started a test run on the CDTS master, disconnected the screen and went home. 

After dinner, I ssh'd to the CDTS master and reattached the screen session to check on the progress.  I'm presented with a window full of "Reconnecting..." and that's it.  The screen command does not provide a scroll back buffer, so I had no clue what test was running, or how long it had been waiting in total for the SUT to come back online.

(turns out it was a reboot test, and the SUT had completely shut down instead of rebooting.)

##### https://launchpad.net/~pieq wrote on 2021-11-15 01:29:13:
@jocave, actually, even running this in a GNOME Terminal, if your terminal history is not infinite, at some point the lines of `Reconnecting...` will erase everything else.

**Comment by Hook25** [comment]
The reconnecting text in the terminal was changed to be an animation instead of printing a newline per second. This should fix the problem you are having here. If not, please do re-open this!
