### ISSUE TITLE
LP1952389: Checkbox Remote should allow you to use the Host's settings instead of changing the config on the DUT

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#158]
This issue was migrated from https://bugs.launchpad.net/checkbox-ng/+bug/1952389

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2021-11-26 06:26:43	| 6	| Wishlist	| False  	|

## Description
When using Checkbox Remote (or CDTS in my case) you install on the Host, and the DUT.  The Host then connects to the DUT and drives the tests.

If you need to alter the configuration, such as the location of the iperf3 server, or how many reps the stress tests should use, you do so on the DUT, and you have to do so each and every time you install a new DUT.

It would be nice if you could make these changes (once) on the Host and have them pushed to the DUT. One less thing for the tester to worry about.

## Attachments
No attachments

Tags:
['checkbox']

**Comment by Hook25** [comment]
I feel like this is adressed by providing a launcher to remote. This was recently-ish fixed and now should act exactly like you would expect. Please do check it and report back if it works. If not, we will reopen this issue.
