### ISSUE TITLE
Turin CPU (AMD EPYC 9755) is not identified by cpuid test

### ISSUE THREAD

**Issue by rodwsmith** [canonical/checkbox#1600]
### Bug Description

A test run on a server with an AMD Turin (EPYC 9755) CPU produced a failure of the miscellanea/cpuid test (output below). The relevant CPU ID should be added to this script. The certification request in question is:

https://certification.canonical.com/certificates/2410-16226/

### Cert-blocker Test Case

- [ ] cert-blocker

### To Reproduce

1. Run Checkbox (presumably any launcher that include miscellanea/cpuid).

### Environment

- System with an AMD EPYC 9755 CPU

### Relevant log output

```shell
Script output is:


CPU Model: AMD EPYC 9755 128-Core Processor
Unable to determine CPU Family for this CPUID: <__main__.CPUID object at 0x73caa15bb380>
```

**Comment by Hook25** [comment]
This test is using a very old version of checkbox, please do check if it is still relevant and feel free to reopen this
