### ISSUE TITLE
LP1982561: checkbox.shell should make it clear you're inside checkbox

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#163]
This issue was migrated from https://bugs.launchpad.net/checkbox-ng/+bug/1982561

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2022-07-22 08:51:34	| 6	| Wishlist	| False  	|

## Description
checkbox.shell opens a runtime shell inside checkbox.

However, unlike other runtime shells (pyenv comes to mind) there is no visible hint that you're in a checkbox shell.

It would be nice if your CLI prompt changed to let you know you're inside checkbox.

Example:

u@u:~$ checkbox.shell
checkbox runtime shell, type 'exit' to quit the session
[checkbox] u@u:~$ exit
exit
u@u:~$ _

## Attachments
No attachments

Tags:
['checkbox']

**Comment by kissiel** [comment]
Good idea.
Let's have a `checkbox-shell` information in the prompt (PS1) within the shell.

**Comment by kissiel** [comment]
in other words, let's get from:
```
~/checkbox/metabox on  metabox-improvements [$!+?] via 🐍 v3.11.6 
❯ checkbox.shell 
checkbox runtime shell, type 'exit' to quit the session
kissiel@venus:~/checkbox/metabox$
```
to
```
~/checkbox/metabox on  metabox-improvements [$!+?] via 🐍 v3.11.6 
❯ checkbox.shell 
checkbox runtime shell, type 'exit' to quit the session
kissiel@venus (checkbox-shell):~/checkbox/metabox$
```

**Comment by fernando79513** [comment]
Python virtual environment is not creating another bash session, so they can modify the prompt (PS1) and works fine.
Since our script is creating a new bash session, it is calling `.bashrc` and PS1 gets reseted.

A way to go over this is adding a new line to your `.bashrc` with the new PS1 update and parse it as an argument to bash:

```
# shell-wrapper
- exec bash
+ exec bash --rcfile <(cat ~/.bashrc; echo 'PS1="(checkbox-shell) $PS1"')
```

**Comment by fernando79513** [comment]
Closed with https://github.com/canonical/checkbox/pull/871
