### ISSUE TITLE
LP1875399: removable_storage_test detecting non-removable devices as removable

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#165]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1875399

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2020-04-27 13:46:39	| 6	| Undecided	| False  	|

## Description
The removable_storage_test script incorrectly identifies some (but not all) non-removable devices as removable. This happens, for instance, with the OBv3 hardware in 18T:

https://certification.canonical.com/hardware/201908-27304/submission/160695/test-results/

The /dev/sdb device on this system is an internal (non-removable) SSD, which the test identifies as removable. The test passes, so it doesn't jump out as a problem in this specific case, but the test script could conceivably run on the wrong device(s) in other cases. On my own laptop, for instance, when I insert an SD card, the test runs against both the SD card (/dev/mmcblk0p1) and against two partitions on the internal SSD (/dev/sda1 and /dev/sda3).

## Attachments
No attachments

Tags:
[]

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~rodsmith wrote on 2020-04-27 16:29:36:
To further complicate matters, I was looking into using the contents of /sys/class/block/{devicename}/removable to filter out non-removable devices, but it doesn't look quite reliable enough. It works correctly to identify removable SD card slots on two machines I've tested (a MacBook Air and a desktop with a PCI-based third-party media-card reader), but on another laptop (a Samsung Notebook 7 Spin), an SD card shows up as being non-removable via this test. I don't know how common this sort of failure is in client devices. On the server side, servers with SD card slots are extremely rare, and we don't happen to have any in-house.

**Comment by pieqq** [comment]
This script does not work on Ubuntu Core, so another method was developed. This method actually works with both UC and classic images, so `removable_storage_test` should be replaced by `run_watcher`.

**Comment by pieqq** [comment]
Part of enhancement to be tracked in Jira.
