### ISSUE TITLE
LP1879848: Record fwupdmgr get-devices results when perform test

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#167]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1879848

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2020-05-21 03:19:53	| 6	| Undecided	| False  	|

## Description
TBT function is heavily depend on firmware.
Sometimes, new firmware might trigger the regression issue.
However due to we does not record firmware version during the test, so it is hard for us to track.
Could we record the fwupdmgr get-devices in checkbox report

## Attachments
No attachments

Tags:
[]

**Comment by pieqq** [comment]
Feedback from @nancyc12:

> Testflinger firmware_update phase does provide the output of fwupdmgr get-devices (in user's terminal or [here](https://testflinger.canonical.com/jobs/69da10b8-f70c-4008-b302-30a1c219f40a)). However, the phase is not designed for querying the fw data,  it would trigger an action to upgrade firmware (downgrade is not supported yet due to the compatibility concern) by the given [TF yaml input](https://testflinger.readthedocs.io/en/latest/reference/test-phases/#firmware-update). I don't think the current design fit this requirement as it seems more like data collection.
> 
> I think there's already some discussion in [this spec](https://docs.google.com/document/d/1padyHQBDuz4sVBYWlG3aWk0sE9j55mPSzDq510x3-b8/edit) regarding hardware data collection in checkbox, including firmware info. It seems to fit the requirement.

Assigning this to @Hook25 as it falls into the HW specs data gathering work he's been doing.

**Comment by pieqq** [comment]
This is actually already in Jira: https://warthogs.atlassian.net/browse/CHECKBOX-906

Closing this issue as enhancements are tracked in Jira.
