### ISSUE TITLE
LP1883533: on s390 disks are being tested twice

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#168]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-resource/+bug/1883533

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2020-06-15 13:20:35	| 6	| Undecided	| False  	|

## Description
On recent s390 testing (Z14) I found that checkbox is testing the same disk twice.

the instance has a disk device called dasda.  On any other system, as this is the equivalent of "sda", the stress-ng test would run against the largest partition on dasda.  Thus:

/dev/dasda
  /dev/dasda1 <- would test this as the largest partition

HOWEVER, what's happening is that it is identifying dasda as a disk and setting up a stress-ng run against dasda1 properly, but THEN identifying dasda1 as a disk and again detecting dasda1 as a partiion and running against that.

https://certification.canonical.com/hardware/201709-25713/submission/171161/test-results/

This is the output header from running against dasda correctly:

```
STRESS_NG_DISK_TIME env var is not found, stress_ng disk running time is default value
Disk device is /dev/dasda
Testing partition /dev/dasda1
/dev/dasda1 is already mounted at /
Using test directory: '//tmp/stress-ng-a8217bfc-a67b-11ea-a88f-37a5913d6af9'
Estimated total run time is 104 minutes
```

and this is the header from running incorrectly against dasda1:

```
STRESS_NG_DISK_TIME env var is not found, stress_ng disk running time is default value
Disk device is /dev/dasda1
Testing partition /dev/dasda1
/dev/dasda1 is already mounted at /
Using test directory: '//tmp/stress-ng-46b01e78-a68a-11ea-a88f-37a5913d6af9'
Estimated total run time is 104 minutes
```

So this test run was about 1:45 longer than it needed to be.

## Attachments
No attachments

Tags:
[]

**Comment by pieqq** [comment]
Closing this here as we will track the work to be done in Jira.
