### ISSUE TITLE
LP1884229: tpm2_createprimary failed on non-supported algorithm sha3_256

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#169]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-tpm2/+bug/1884229

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2020-06-19 10:36:07	| 8	| Undecided	| False  	|

## Description
tpm2-tss not yet support sha3_256.

In this test case on a machine reported it support sha3_256 then call
`tpm2_createprimary -Q -g sha3_256 -G rsa -c context.out`

The this test case will be marked as error.

tpm2_createprimary should returned "5 - Non supported scheme.  Applicable to tpm2_testparams." , so that we can skip the non-supported algorithm.

upstream bug: https://github.com/tpm2-software/tpm2-tools/issues/2110

## Attachments
No attachments

Tags:
['oem-priority', 'originate-from-1880048', 'somerville']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~alextu wrote on 2020-06-19 10:44:35:
hmm the tpm2_createprimary not actually return 5 when it encounters an unsupported algorithm.

##### https://launchpad.net/~alextu wrote on 2020-06-19 10:54:53:
created an upstream issue there as well : https://github.com/tpm2-software/tpm2-tools/issues/2110

##### https://launchpad.net/~ycheng-twn wrote on 2020-07-02 05:12:36:
The upstream bug is closed and a patch is merged.

Given so, do we still need this MP?

##### https://launchpad.net/~alextu wrote on 2020-07-03 13:41:23:
No, we don't need this MP while upstream fixed it. But we need another MP to check the return code.


##### https://launchpad.net/~alextu wrote on 2020-07-10 05:49:53:
this issue is waiting for upstream release a new version included the fix. [1] [2]

[1] https://github.com/tpm2-software/tpm2-tools/issues/2110
[2] https://github.com/tpm2-software/tpm2-tools/releases

**Comment by yphus** [comment]
fix released in jammy. (see https://bugs.launchpad.net/plainbox-provider-tpm2/+bug/1884229/comments/7)
