### ISSUE TITLE
LP1886916: Use Xorg log to get the running Gfx driver information is not reliable

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#170]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1886916

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2020-07-09 08:11:10	| 6	| Undecided	| False  	|

## Description
[Summary]
Use Xorg log as API isn't reliable at all, it can break at anytime, and this impacts all of the certificate process in oem team. Please use method like [1] to properly find out which DDX is opened by Xorg process.

[Steps to reproduce]
Run graphics/1_driver_version_GP102GL__Quadro_P620 by checkbox

[Expected result]
Can pass the test

[Actual result]
ERROR: No video driver loaded! Possibly in failsafe mode!
------------- VIDEO DRIVER INFORMATION -------------
------------- HYBRID GRAPHICS CHECK ----------------
Graphics Chipset: NVIDIA (10de:1cb6)
Loaded DDX Drivers: nouveau, modesetting, fbdev, vesa
Hybrid Graphics: no

[Additional information]
1. Nvidia P400
2. Nvidia P620
3. Nvidia P2200
4. Nvidia P6000
5. AMD RX 550

[Failure rate]
100%

[1] https://unix.stackexchange.com/a/452582

## Attachments
No attachments

Tags:
['oem-priority', 'originate-from-1886009', 'stella']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~hugh712 wrote on 2020-07-10 11:11:49:
@Sylvain

mind help to take a look of this issue, this will impact all oem projects, thanks.

##### https://launchpad.net/~williamhsu wrote on 2020-07-15 08:19:09:
A patch is under review.
- https://code.launchpad.net/~williamhsu/plainbox-provider-checkbox/+git/plainbox-provide-checkbox/+merge/386796

##### https://launchpad.net/~sylvain-pineau wrote on 2020-07-15 08:22:01:
@Hugh,

Adding a new method to find the loaded drivers is a good idea. Mind developing a patch for https://git.launchpad.net/plainbox-provider-checkbox/tree/bin/graphics_driver ? 

##### https://launchpad.net/~hugh712 wrote on 2020-07-16 05:15:55:
@Sylvain 

sure, William is working on this :)

**Comment by pieqq** [comment]
Patch was merged at https://code.launchpad.net/~williamhsu/plainbox-provider-checkbox/+git/plainbox-provide-checkbox/+merge/386796. Closing this one.
