### ISSUE TITLE
LP1909208: suspend/bluetooth_obex_send_after_suspend_auto needs more retries if the server side is busy

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#175]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1909208

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2020-12-24 09:57:19	| 8	| Undecided	| False  	|

## Description
The obex protocol only support one-to-one connection.
We need to design a way to queue the task or more retries.

## Attachments
No attachments

Tags:
['oem-priority', 'originate-from-1901683', 'originate-from-1901871', 'originate-from-1904146', 'originate-from-1906593', 'originate-from-1907029', 'originate-from-1907036', 'originate-from-1907226', 'originate-from-1908666', 'originate-from-1908679', 'originate-from-1909205', 'originate-from-1909206', 'originate-from-1909276', 'originate-from-1910388', 'originate-from-1910487', 'originate-from-1910645', 'originate-from-1910655', 'originate-from-1910722', 'originate-from-1914213', 'originate-from-1914342', 'originate-from-1914707', 'originate-from-1918117', 'originate-from-1918118', 'originate-from-1918247', 'originate-from-1918248', 'originate-from-1955545', 'originate-from-1959210', 'somerville', 'stella', 'sutton']

**Comment by pieqq** [comment]
Closing this as a change was proposed by @hanhsuan
