### ISSUE TITLE
LP1914539: info/buildstamp display error on C3

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#181]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1914539

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Confirmed	| 2021-02-04 06:17:31	| 4	| Medium	| False  	|

## Description
for PC projects, buildstamp info on C3 will show "# For more information see http://wiki.ubuntu.com/DistributionChannelDescriptor" 

e.g stella
https://certification.canonical.com/hardware/202009-28221/submission/200759/
e.g Somerville
https://certification.canonical.com/hardware/202012-28457/submission/200223/

## Attachments
No attachments

Tags:
[]

**Comment by yphus** [comment]
Fixed via https://github.com/canonical/checkbox/commit/7c41c04aab000051e9d016232430507a1b522b55
