### ISSUE TITLE
LP1968002: Manifest evaluates always false while sideloading the project provider

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#182]
This issue was migrated from https://bugs.launchpad.net/checkbox-ng/+bug/1968002

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2022-04-06 07:39:32	| 6	| Medium	| False  	|

## Description
[Summary]
Manifest evaluates always false while sideloading the project provider. However, if it been built in a live checkbox, then it will work as expected.

I tried to add com.canonical.plain::collect-manifest into my plan. And also I can saw the manifest question that I add for this project. But after I ticked manifest question as yes. It will still evaluate as false while the job executed.

[Steps to reproduce]
1.boot into system
2.Add a manifest entry for project provider
  unit: manifest entry
  id: has_dio_equipment
  _name: Zhongyi DIO equipment connected
  value-type: bool
3.Add a job include "requires" of manifest entry.
  requires:  manifest.has_dio_equipment == 'True'
4.Sideloading both manifest and jobs.

[Expected result]
Checkbox should get the correct evaluation of manifest question even provider is sideloaded.

[Actual result]
Checkbox will always evaluate manifest question as false if provider is sideloaded.

[Other Information]
checkbox20 1.25 rev:812

## Attachments
[manifest_debug.log](https://api.launchpad.net/devel/bugs/1968002/+attachment/5577532/data)

Tags:
['checkbox']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~kissiel wrote on 2022-04-06 10:24:45:
Have you rerun the collect-manifest job after adding that entry?

**Comment by rickwu666666** [comment]
I found that I can not reproduce this issue anymore.
checkbox20    2.7    rev 1299
