### ISSUE TITLE
LP1926683: Need a resource job to log TPM2 capabilities

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#184]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-resource/+bug/1926683

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2021-04-30 02:46:29	| 6	| Undecided	| False  	|

## Description
A TPM2 capabilities resource job to help us:

- log the TPM2 capabilities of a device
- potentially filter and customize each device's TPM2 tests with the outputs of this resource job

## Attachments
No attachments

Tags:
['ce-qa-concern']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~hyac109 wrote on 2021-04-30 03:00:37:
Discussed with HWE Ivan; a possible way to achieve this:

With tpm2-tools v.4-x, use the following command to list a device's TPM2 capabilities:

`sudo tpm2_getcap <capability category>`[1]

The following categories' outputs are parts that we MUST capture:

- commands
- algorithms
- properties-fixed
- pcrs

Example outputs of the above commands:
https://pastebin.canonical.com/p/bDnM4KYXhp/

Related Trello card: 
https://trello.com/c/vc1SH4aA/557-create-checkbox-tpm-capabilities-resource-job

[1] available categories can be found with `sudo tpm2_getcap -l`

**Comment by yphus** [comment]
tpm2 tests moved to clevis
