### ISSUE TITLE
LP1927220: [New test cases needed] WiFi-6E

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#185]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1927220

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2021-05-05 12:44:02	| 6	| Undecided	| False  	|

## Description
We are starting to see WiFi-6E in Dell roadmap. The kernel code for Intel AX210 is landing in 5.11 Kernel.
So we need test cases for this new feature.

## Attachments
No attachments

Tags:
['cbox-41']

**Comment by pieqq** [comment]
We have Wifi AX tests (see all the `wireless_connection_wpa_ax***` related jobs in https://github.com/canonical/checkbox/blob/main/providers/base/units/wireless/jobs.pxu for instance).

Closing this. @linjuiche  If tests that are specific to the 6GHz band are required, please open another issue.
