### ISSUE TITLE
LP1927663: [Checkbox deb] the checkbox session won't resume automatically while running power-automated test plan

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#20]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1927663

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Confirmed	| 2021-05-07 02:45:38	| 10	| Critical	| False  	|

## Description
[Summary]
The checkbox session won't resume automatically while running power-automated test plan

[Steps to reproduce]
1. Power on system and boot into OS.
2. checkbox-cli run com.canonical.certification::power-automated

[Expected result]
checkbox session will be resume automatically after restart system.

[Actual result]
checkbox session won't resume automatically after restart system.

[Additional information]
kernel-version: 5.10.0-1023-oem
ubuntu-version: 20.04

dpkg -l | grep checkbox
ii  checkbox-ng                                1.13.0~ppa~ubuntu20.04.1                 all          CheckBoxNG test runner
ii  plainbox-provider-checkbox                 0.58.0~ppa~ubuntu20.04.1                 amd64        CheckBox provider for PlainBox
ii  python3-checkbox-ng                        1.13.0~ppa~ubuntu20.04.1                 all          CheckBoxNG test runner (Python 3 library)
ii  python3-checkbox-support                   0.50.0~ppa~ubuntu20.04.1                 all          collection of Python modules used by PlainBox providers

## Attachments
[checkbox-session.tgz](https://api.launchpad.net/devel/bugs/1927663/+attachment/5495368/data)
[snap_list.log](https://api.launchpad.net/devel/bugs/1927663/+attachment/5495369/data)
[acpidump.log](https://api.launchpad.net/devel/bugs/1927663/+attachment/5495370/data)
[sosreport-u-ThinkStation-P520c-2021-05-06-cvighup.tar.gz](https://api.launchpad.net/devel/bugs/1927663/+attachment/5495371/data)

Tags:
['cbox-1', 'checkbox-session-resume', 'go-to-jira']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~stanley31 wrote on 2021-05-07 02:46:12:
Automatically attached

##### https://launchpad.net/~stanley31 wrote on 2021-05-07 02:46:14:
Automatically attached

##### https://launchpad.net/~stanley31 wrote on 2021-05-07 02:46:18:
Automatically attached

##### https://launchpad.net/~stanley31 wrote on 2021-05-07 02:46:20:
Automatically attached

**Comment by pieqq** [comment]
This was fixed with #859. Closing this issue. If the problem appears again, please file a new issue.
