### ISSUE TITLE
LP1928195: [Nvidia + NVLINK] Checkbox would switch prime profile to intel during graphic testing

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#21]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1928195

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2021-05-12 10:17:13	| 6	| Critical	| False  	|

## Description
Description:
The checkbox would switch PRIME profile to intel when there're only two nVidia discrete GPU cards on the system.

I have investigated the source code about graphic resource, and found we didn't check is integrated GPU is installed or not.

# Script block #
switch_cmds['nvidia'] = ('prime-select nvidia', 'prime-select intel')
...
record['switch_to_cmd'] = switch_cmds[record['driver']][0]
if index == 2 and len(video_devices) == 2:
    # we're at GPU number 2 and there are two, so here we assume
    # that video_devices[0] is the built-in one
    video_devices[0]['switch_to_cmd'] = (switch_cmds[record['driver']][1])

Steps to reproduce:
1. Install two nVidia GPU w/ NVLINK. (The machine has not integrated GPU).
2. Install OS and checkbox.
3. Run client-cert-20-04 test plan.
Note: the screen would become blank after graphics/1_auto_switch_card_.* job.

Expected result:
The checkbox should not switch to intel profile.

Observed result:
The checkbox issue a command to switch PRIME profile to intel. So the screen become blank due to no integrated GPU on the machine.

Test Environment:
- A workstation w/o integrated GPU.
- Two nVidia discrete GPU are installed.

## Attachments
No attachments

Tags:
['cbox-3']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~stanley31 wrote on 2021-05-19 07:31:58:
there are two scenario for switch rendering profile.
first bug, lp:1922917 it's reported by ODM. And they run checkbox under a desktop w/ iGPU and dGPU, but they connect the monitor on dGPU to run graphic testing.
And the checkbox would switch the rendering profile to iGPU during testing.

this bug it's reported by me. And I run checkbox under a desktop w/o iGPU, but with two nvidia GPU w/ NVLINK. and the checkbox would also switch the rendering profile to intel. But there's no iGPU at the moment.

**Comment by pieqq** [comment]
This won't be needed once #400 is merged.

**Comment by kissiel** [comment]
The related PR landed so the problem should be gone now. If it's not, please reopen the issue.
