### ISSUE TITLE
[Checkbox-Remote] System turns off during stress test and won't wake up to complete rest tests

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#224]
This issue was migrated from https://bugs.launchpad.net/checkbox-ng/+bug/1973255

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2022-05-13 04:08:14	| 6	| Undecided	| False  	|

## Description
During the stress testing, checkbox would start to run next job even the previous job (reboot_30 and poweroff_30) is not completed. And then the system was turning off. Please refer to attachment.

[Steps to reproduce]
1. Prepare a host and connect to DUT
$ checkbox-cli remote {DUT IP}

2. Select test plan com.canonical.certification::client-cert-desktop-20-04-stress and start testing

[Expected result]
Stress test complete successfully

[Actual result]
test cases below passed with only 1 cycle and system turned off
1. reboot_30
2. poweroff_30

## Attachments
[remote_stress_test.log](https://api.launchpad.net/devel/bugs/1973255/+attachment/5589368/data)
[remote-2022-05-12T02.40.07.session.tar.xz](https://api.launchpad.net/devel/bugs/1973255/+attachment/5589395/data)

Tags:
[]

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~stanley31 wrote on 2022-05-13 06:20:27:
attached the checkbox session in DUT.

##### https://launchpad.net/~pieq wrote on 2022-05-17 08:26:04:
I

1. ran checkbox remote from my laptop to the DUT
2. selected com.canonical.certification::client-cert-desktop-20-04-stress
3. only selected the stress/reboot_30 and stress/reboot_30_log jobs and started the test

Checkbox seems to be working as expected:

1. the DUT reboots, then shows a dialog mentioning "Reboot 2/30" while it gathers data and wait for the next reboot
2. at the end of the 30 reboots, the stress/reboot_30_log job is executed
3. in the session archive, I can see that the reboot was executed 30 times ("reboot operations remaining:" can be found 31 times in the log file)

So the problem might come from the poweroff job instead. I'll investigate this next.

##### https://launchpad.net/~pieq wrote on 2022-05-18 03:40:16:
I ran a similar test, but this time only selected stress/poweroff_30, and I got results similar to my previous comment:

The job runs 30 poweroffs, after which the host can connect back to the DUT, wrap up the session and generate the archive and the HTML reports.

A few things I forgot to mention yesterday, and that apply to both comment #3 and this comment:

1. During the whole time the stress/*_30 job is running, the host outputs:

    Reconnecting...
    Reconnecting...
    Reconnecting...

2. When the stress/*_30 job is finished, a terminal window is shown on the DUT with the following text:

    Created symlink /etc/systemd/system/multi-user.target.wants/checkbox-ng.service -> /lib/systemd/system/checkbox-ng.service.

I assume it's this that allows the host to reconnect to the DUT and finish the session.

##### https://launchpad.net/~kent-jclin wrote on 2022-06-02 05:56:29:
@Pierre,

I got 1 system that faces a similar issue. The console log could be found in following link:
http://10.102.135.50:8080/job/sanity-3-testflinger-dummy-202201-29865-staging/12/console

**Comment by pieqq** [comment]
Fixed by #477
