### ISSUE TITLE
LP1974222: slow data transfer speeds when using remote

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#225]
This issue was migrated from https://bugs.launchpad.net/checkbox-ng/+bug/1974222

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2022-05-19 18:01:28	| 6	| Undecided	| False  	|

## Description
That's what I'm seeing waiting to finish up a test executed like so:

checkbox-cli remote IPADDR /usr/bin/test-network

it takes several minutes to obtain all the files from the SUT using whatever mechanism remote is using here...  

not a showstopper, just a painfully slow process that becomes obvious when I'm trying to run tests manually via checkbox remote.

5.33MB [01:17, 72.1kB/s, file=/home/bladernr/.local/share/checkbox-ng/submission_2022-05-19T17.56.33.579627.html]                                                   
file:///home/bladernr/.local/share/checkbox-ng/submission_2022-05-19T17.56.33.579627.html
32.0kB [00:00, 59.1kB/s, file=/home/bladernr/.local/share/checkbox-ng/submission_2022-05-19T17.56.33.579627.junit.xml]                                              
file:///home/bladernr/.local/share/checkbox-ng/submission_2022-05-19T17.56.33.579627.junit.xml
7.06MB [01:48, 68.0kB/s, file=/home/bladernr/.local/share/checkbox-ng/submission_2022-05-19T17.56.33.579627.tar.xz]                                                 
file:///home/bladernr/.local/share/checkbox-ng/submission_2022-05-19T17.56.33.579627.tar.xz

More annoying is that there's no way to ctrl-c out of this once the download begins...

## Attachments
No attachments

Tags:
['servcert-365']

**Comment by Hook25** [comment]
The original issue is closed. The problem may be that the submission file set is too big. You can try pruning it if you don't need something it is trying to send you. I also noticed that the original issue is rejected. Closing this.
