### ISSUE TITLE
LP1979294: wifi/wwan test fail due to access io.netplan.Netplan fail

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#234]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1979294

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2022-06-21 09:19:59	| 6	| Undecided	| False  	|

## Description
[Summary]
wifi/wwan test fail due to access io.netplan.Netplan fail. However, if we apply netplan manually, then it will be no any issue. And wifi can be applied and worked.

[Steps to reproduce]
1. Run job "wireless/wireless_connection_open_ac_np.*"

[Expected result]
WiFi connection test should be pass.

[Actual result]
WiFi connection test fail due to access io.netplan.Netplan fail.

## Apply the test configuration
+ netplan --debug apply
Call failed: Failed to execute program io.netplan.Netplan: Permission denied
ERROR: failed netplan apply call

[Failure rate]
100%

[Additional information]
image: iot-zhongyi-classic-server-2004-classic-x06-20220620-94
kernel: 5.4.0-1015-imx #15
snap: checkbox20  1.28  rev 976

## Attachments
[wifi_fail.log](https://api.launchpad.net/devel/bugs/1979294/+attachment/5598637/data)

Tags:
[]

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~rickwu4444 wrote on 2022-07-12 00:33:10:
I found that if adding "sudo" in front of "netplan --debug apply" then this issue won't happen.

https://git.launchpad.net/plainbox-provider-checkbox/tree/bin/wifi_client_test_netplan.py#n184

**Comment by yphus** [comment]
All jobs from  https://github.com/canonical/checkbox/blob/main/providers/base/units/wireless/wireless-connection-netplan.pxu are now running as root.
