### ISSUE TITLE
LP1982863: Another fake USB NIC that we need to account for

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#241]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-resource/+bug/1982863

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2022-07-26 17:17:58	| 6	| Undecided	| False  	|

## Description
This needs to be accounted for so that it is skipped when testing is run.

I think this was fixed before in either the checkbox provider or the resource provider but not sure which right now... so I'll add tasks for each.

Here's the result where the card was seen:
 

https://certification.canonical.com/hardware/202207-30439/submission/271725/

## Attachments
No attachments

Tags:
['servcert-436']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~beliaev-maksim wrote on 2022-11-28 17:47:49:
Bug was migrated to GitHub: https://github.com/canonical/checkbox/issues/240.
Bug is no more monitored here.

**Comment by Hook25** [comment]
Closing as duplicated in https://github.com/canonical/checkbox/issues/240.
