### ISSUE TITLE
LP1987000: Add Milan-X Support to CPUID script

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#245]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1987000

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2022-08-18 20:38:35	| 6	| Undecided	| False  	|

## Description

The cpuid script does not identify Milan-X CPUs.

Update the script to identify Milan-X CPUs

## Attachments
No attachments

Tags:
[]

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~mreed8855 wrote on 2022-08-18 20:52:00:
I have created a fix here.

https://code.launchpad.net/~mreed8855/plainbox-provider-checkbox/+git/plainbox-provider-checkbox/+ref/milan-x_cpuid

##### https://launchpad.net/~mreed8855 wrote on 2022-09-19 15:39:12:
I am combining this fix with another addition.  The branch proposed in comment #1 is no longer valid.

https://code.launchpad.net/~mreed8855/plainbox-provider-checkbox/+git/plainbox-provider-checkbox/+merge/430110

**Comment by Hook25** [comment]
Closing as already fixed (support is in the file). If you need another id, please do reopen this.
