### ISSUE TITLE
LP1995936: graphics/cycle_resolution failed with intel graphic on NVIDIA Hybrid Graphics

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#250]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1995936

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2022-11-08 10:03:51	| 6	| Undecided	| False  	|

## Description
Wayland still not support on NVIDIA Hybrid Graphics

graphics/*_switch_card_* change to intel graphic only, not on-demand.
Therefore, graphics/cycle_resolution failed if output to WAYLAND.

stderr
------
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  139 (RANDR)
  Minor opcode of failed request:  7 (RRSetScreenSize)
  Serial number of failed request:  22
  Current serial number in output stream:  23
Failed to set mode 1440x1080 for output XWAYLAND0
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  139 (RANDR)
  Minor opcode of failed request:  7 (RRSetScreenSize)
  Serial number of failed request:  22
  Current serial number in output stream:  23
Failed to set mode 1280x1024 for output XWAYLAND0
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  139 (RANDR)
  Minor opcode of failed request:  7 (RRSetScreenSize)
  Serial number of failed request:  22
  Current serial number in output stream:  23
Failed to set mode 1680x1050 for output XWAYLAND0
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  139 (RANDR)
  Minor opcode of failed request:  7 (RRSetScreenSize)
  Serial number of failed request:  22
  Current serial number in output stream:  23
Failed to set mode 1368x768 for output XWAYLAND0

## Attachments
[checkbox-run-resolution.zip](https://api.launchpad.net/devel/bugs/1995936/+attachment/5629733/data)

Tags:
[]

**Comment by yphus** [comment]
gnome_randr_cycle should be used when this job runs on a wayland session. Please reopen if needed
