### ISSUE TITLE
LP1995944: suspend/*_rotation_after_suspend_*_graphics failed with intel graphic

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#251]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1995944

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2022-11-08 11:29:40	| 6	| Undecided	| False  	|

## Description
graphics/*_switch_card_* change to intel graphic only then reboot that triggers the pm_test.py script, which respawns Checkbox as root. 
It's a problem which have to run as the current user, not root.

stderr
------
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  139 (RANDR)
  Minor opcode of failed request:  7 (RRSetScreenSize)
  Serial number of failed request:  22
  Current serial number in output stream:  23
Traceback (most recent call last):
  File "/tmp/nest-2jy426wc.eaa0136a0c9823ca6ddf5bd2892a41cd834761194e4f7bd7e584c0eff371f85a/rotation_test.py", line 53, in <module>
    exit(main())
  File "/tmp/nest-2jy426wc.eaa0136a0c9823ca6ddf5bd2892a41cd834761194e4f7bd7e584c0eff371f85a/rotation_test.py", line 47, in main
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['xrandr', '--output', 'XWAYLAND0', '--rotation', 'right']' returned non-zero exit status 1.

## Attachments
[session_rotation.zip](https://api.launchpad.net/devel/bugs/1995944/+attachment/5629740/data)

Tags:
[]

**Comment by yphus** [comment]
This bug should be fixed with recent version of the rotation script (on 22.04+). Please reopen if needed.
