### ISSUE TITLE
camera/still_video0 can't work with MIPI camera

### ISSUE THREAD

**Issue by seankingyang** [canonical/checkbox#260]
### Bug Description

It cannot run **camera/still_videio** test. It got errors.

Run with `./camera_test.py detect`
```
ubuntu@ubuntu:/usr/lib/checkbox-provider-base/bin$ ./camera_test.py detect
/dev/video0: OK
    name   : Intel MIPI Camera
    driver : v4l2 loopback
    version: 6.0.9
    flags  : 0x85200001 [ CAPTURE READWRITE STREAMING ]
    Format: NV12 (Y/CbCr 4:2:0)
    Resolutions: 1280x720
```
Run with `./camera_test.py still`
```
ubuntu@ubuntu:/usr/lib/checkbox-provider-base/bin$ ./camera_test.py still
../src/intel/isl/isl.c:2220: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.
/usr/lib/checkbox-provider-base/bin/./camera_test.py:324: DeprecationWarning: Clutter.Texture.new_from_file is deprecated
  still_texture = Clutter.Texture.new_from_file(filename)
Traceback (most recent call last):
  File "/usr/lib/checkbox-provider-base/bin/./camera_test.py", line 589, in <module>
    sys.exit(getattr(camera, args.test)())
  File "/usr/lib/checkbox-provider-base/bin/./camera_test.py", line 290, in still
    self._still_helper(f.name, self._width, self._height,
  File "/usr/lib/checkbox-provider-base/bin/./camera_test.py", line 324, in _still_helper
    still_texture = Clutter.Texture.new_from_file(filename)
gi.repository.GLib.GError: gdk-pixbuf-error-quark: Image file “/tmp/camera_test_1cf8zraz.jpg” contains no data (0)
```
Run with `fswebcam`
```
ubuntu@ubuntu:~$ fswebcam ~/Desktop/cameraTest.jpg
--- Opening /dev/video0...
Trying source module v4l2...
/dev/video0 opened.
No input was specified, using the first.
Unable to find a compatible palette format.
ubuntu@ubuntu:~$
```

### To Reproduce

1. Boo to OS
2. Run camera/still test case.

### Environment

-checkbox version:
> checkbox-ng: 2.0.0
>   checkbox-support: 2.0.0
>   com.canonical.ce:oem: 1.0
>   checkbox-provider-base: 2.0.0
>   checkbox-provider-certification-client: 2.0.0
>   checkbox-provider-resource: 2.0.0
>   checkbox-provider-tpm2: 2.0.0

**Comment by pieqq** [comment]
Hello! Does the camera actually work?

For instance, can you use it in Cheese, or in https://webcamtests.com/ ?

**Comment by seankingyang** [comment]
Hi Pierre,
Yes, it can work with both Cheese app and https://webcamtests.com/.

**Comment by scotthu27** [comment]
@pieqq 

It seems NV12 format which not supported by fswebcam
https://bugs.launchpad.net/somerville/+bug/1996561/comments/5

**Comment by yphus** [comment]
camera_test.py first tries a still capture with fswebcam but if it fails, a camerabin gstreamer pipeline is used instead.
it would be interesting to know why the gstreamer method is also failing since it should be similar to Cheese.

**Comment by scotthu27** [comment]
It's the workaround to make Cheese work for Dell platforms 
https://bugs.launchpad.net/somerville/+bug/1996671

**Comment by seankingyang** [comment]
The RC of not use the `camerabin`: will not error when running `fswebcam`, so the retrn code is zero.
