### ISSUE TITLE
[Core] Checkbox be interrupted due to failed to start plainbox-autostart.service

### ISSUE THREAD

**Issue by baconYao** [canonical/checkbox#261]
### Bug Description

It interrupts the running job, shows `[FAILED] Failed to start plainbox-autostart.service.` and you need to login into OS again.

QA found this issue often occurs after executing `power-management/cold-reboo`t and `power-management/warm-reboot` for a while, then the checkbox will be interrupted and user be logged out.

See the following picture, 

1. problem suddenly occurs, shows `[FAILED] Failed to start plainbox-autostart.service.` while running bluetooth case.
2. After problem happened, I have to login into system again since I was logged out automatically.
3. Check the plainbox-autostart.service status

![plainbox-autostart_service](https://user-images.githubusercontent.com/8318678/205880117-75c54c75-fcec-4b46-945c-f2f312acfb96.jpg)

### To Reproduce

1. sudo snap install checkbox22
2. sudo snap install checkbox --edge --devmode
3. checkbox.checkbox-cli
4. Choose and run  `com.canonical.certification::client-cert-iot-ubuntucore-22-automated` test plan

### Environment

- OS: UC20, UC22
- Checkbox Type: Snap
- Checkbox Version: 2.1.0

### Additional context

[sosreport-ubuntu-2022-12-02-ufumvpz.tar.gz](https://github.com/canonical/checkbox/files/10165072/sosreport-ubuntu-2022-12-02-ufumvpz.tar.gz)

This is the sosreport from `intel iotg aaeon-ehl`

### Failure Rate
High failure rate (80-90%) on aaeon-ehl (cid: 202109-29492) & aaeon-tgl (cid: 202110-29509)

**Comment by baconYao** [comment]
Video record

https://user-images.githubusercontent.com/8318678/205904101-4f2a5915-236b-41d6-985b-039c45f666aa.mp4

**Comment by yphus** [comment]
@baconYao please use checkbox [remote](https://checkbox.readthedocs.io/en/latest/remote.html) for core/headless testing

**Comment by baconYao** [comment]
Issue can solved via checkbox remote
