### ISSUE TITLE
[snap] Command "pactl" cannot work properly

### ISSUE THREAD

**Issue by baconYao** [canonical/checkbox#262]
### Bug Description

 if a user runs the audio test cases which are using `pactl` command via checkbox snap, he will get the weird output and those job will be failed in the end.

For example, the following screenshot is the output I executed the command `checkbox.checkbox-cli run com.canonical.certification::audio/detect_sinks_sources`
![Screenshot from 2022-12-06 18-36-31](https://user-images.githubusercontent.com/8318678/205890151-632b6b99-add7-440c-b33e-a0d5d0841a98.png)

Another example is I type `pactl info` in checkbox.shell environment
![Screenshot from 2022-12-06 18-46-25](https://user-images.githubusercontent.com/8318678/205890720-f3712b3e-6185-4a5d-81d1-d6ad4e711ea2.png)

Both result shows `Permission` and `Connection` problem.

### To Reproduce

1. Boot into OS
2. `sudo snap install checkbox22`
3. `sudo snap install checkbox --edge --classic`
4. `checkbox.checkbox-cli run com.canonical.certification::audio/detect_sinks_sources`

### Environment

OS: Desktop 22.04 LTS
Checkbox Type: Snap
Checkbox Version:
```
Name                            Version             Rev    Tracking         Publisher            Notes
bugit                           1.0                 4      latest/edge      pieq                 devmode
checkbox                        2.4                 2084   latest/stable    ce-certification-qa  classic
checkbox22                      1.31                197    latest/stable    ce-certification-qa  -
```

**Comment by yphus** [comment]
@baconYao please try running the same job `com.canonical.certification::audio/detect_sinks_sources` but using checkbox [remote](https://checkbox.readthedocs.io/en/latest/remote.html).

**Comment by baconYao** [comment]
Issue can solved via checkbox remote
