### ISSUE TITLE
Store information about all the CPUs in checkbox.json reports

### ISSUE THREAD

**Issue by nadzyah** [canonical/checkbox#270]
### Enhancement Proposal

According to [the code lines there](https://github.com/canonical/checkbox/blob/main/checkbox-ng/plainbox/impl/providers/exporters/data/checkbox.json#L157-L162), a report contains information about only one CPU under the “processor” key.

The idea is to store the value under this key as a list of dicts rather than just a dictionary. Hence, under the “processor” key we should store the information about all the CPUs a machine can have, not just the “first” one.

**Comment by bladernr** [comment]
Some questions:

- What is checkbox.json used for?
- Is this propsal to store a list of dicts with cpuinfo for everything reported by the system?
- If so, how does this scale if run on, say, a system with cpuinfo reporting 256 or 512 identical cores?
- How does that scale affect the size of checkbox.json and whatever is using that?

**Comment by kissiel** [comment]
> What is checkbox.json used for?

checkbox.json is a jinja2 template (yuck) that gets interpolated with the session state to produce a valid checkbox report.

> Is this propsal to store a list of dicts with cpuinfo for everything reported by the system?
everything == physical processors

> If so, how does this scale if run on, say, a system with cpuinfo reporting 256 or 512 identical cores?
Let's say this 256 cores come from 4P 64 core config. This would mean reporting 4 CPUs.

> How does that scale affect the size of checkbox.json and whatever is using that?
That one entry would grow proportionally to the number of physical processors. Shouldn't be a noticeable hit to perf.

**Comment by pieqq** [comment]
After discussion with @nadzyah , this needs more syncing with C3, so when it needs to land, an update to the submission schema is required alongside C3 specs.

Closing it for now.
