### ISSUE TITLE
ipdt/PCH-x86_64: No permission to access I/O ports

### ISSUE THREAD

**Issue by baconYao** [canonical/checkbox#276]
### Bug Description

Run `ipdt/PCH-x86_64` on Focal will always get the permission issue like below

```
[Checkbox job `com.intel.ipdt::ipdt/PCH-x86_64` output]

stdout
------

--- Platform Controller Hub Test ---
...
Version: 1.0.9.64b.L
...

stderr
------
pcilib: No permission to access I/O ports (you probably have to be root).
```

### To Reproduce

1. Install OS (UC20 / Server 20.04 / Desktop 20.04)
2. Install snap checkbox
    ```bash
    # suppose we are using Desktop 20.04
    sudo snap install checkbox20
    sudo snap install checkbox --channel=20.04/edge --classic
    ```
6. Checkbox local\remote run the `com.intel.ipdt::ipdt-plan` test plan

### Environment

OS: UC20, Server 20.04, Desktop 20.04
Checkbox Type: Snap & Deb
Checkbox Version: 2.1.0

### Relevant log output

```shell
- Test Submission: https://certification.canonical.com/hardware/202206-30375/submission/293313/
```

**Comment by pieqq** [comment]
According to @zongminl this might be due to running this on a device with Secure Boot enabled.

**Comment by zongminl** [comment]
Reference for the comment above: https://bugs.launchpad.net/newparis/+bug/1908994

**Comment by xnox** [comment]
raw I/O ports access is restricted under lockdown. lockdown is turned on by default under secureboot, one can also turn on lockdown by booting with `lockdown=1` kernel command line.

We have had regressions in the past in lockdown not locking down I/O ports. Thus ideally this test should assert that it indeed doesn't work under Secureboot and does work without Secureboot.

Something like: 
 * if secureboot is on, test passes the reported result should be failure.
 * if secureboot is on, test fails the reported result should be skipped
 * if secureboot is off, the test pass/fail should be reported as pass/fail (normal)

**Comment by baconYao** [comment]
Close issue sine ipdt providers had been retired.
