### ISSUE TITLE
microphone/headphone detect encounter ParseException

### ISSUE THREAD

**Issue by weizhenwu** [canonical/checkbox#278]
### Bug Description

Run mircophone/headphone detect case 
after press enter, it will encounter ParseException and finised directly

### To Reproduce

1. checkbox-cli run com.canonical.certification::audio/microphone-plug-detection

### Environment

OS: Desktop 22.04
Kernel: 6.0.0-1008-oem
checkbox version: 2.0.0
type: Debian

### Relevant log output

```shell
- Checkbox session(s) (located in `/var/tmp/checkbox-ng/sessions/`, you usually want to select the most recent one)

- logs from the impacted components (e.g. `lsblk` if this is related to an issue when testing a disk...); a safe opTraceback (most recent call last):
  File "/tmp/nest-iktrhdi3.32562a7a1c74649eb8594ffd8a25040a35e68cb302ce6e868cbfd4dbe2885a18/pulse_active_port_change.py", line 156, in <module>
    raise SystemExit(AudioPlugDetection.main())
  File "/tmp/nest-iktrhdi3.32562a7a1c74649eb8594ffd8a25040a35e68cb302ce6e868cbfd4dbe2885a18/pulse_active_port_change.py", line 113, in main
    return cls(ns.timeout, ns.mode).run()
  File "/tmp/nest-iktrhdi3.32562a7a1c74649eb8594ffd8a25040a35e68cb302ce6e868cbfd4dbe2885a18/pulse_active_port_change.py", line 126, in run
    initial_cfg = self.get_sound_config()
  File "/tmp/nest-iktrhdi3.32562a7a1c74649eb8594ffd8a25040a35e68cb302ce6e868cbfd4dbe2885a18/pulse_active_port_change.py", line 76, in get_sound_config
    doc = parse_pactl_output(text)
  File "/usr/lib/python3/dist-packages/checkbox_support/parsers/pactl.py", line 604, in parse_pactl_output
    return Document.Syntax.parseString(output, parseAll=True)[0]
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1955, in parseString
    raise exc
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 3814, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected end of text, found '\t'  (at char 6942), (line:184, col:1)tion is to install and run `sosreport` to gather as much log as possible.
```

**Comment by pieqq** [comment]
Hi! Are you using the Debian version or the snap version of Checkbox?

If you are running the Debian version, could you try with the latest daily build? We fixed an issue related to pyparsing recently and I'm wondering if it could be the same root cause.

**Comment by weizhenwu** [comment]
hi @pieqq, I was testing with Debian version.
Just tried with daily bulid and got the same ParseException with these 2 cases

**Comment by eugene-yujinwu** [comment]
@weizhenwu Hi, do you use an external HDMI or such kind of external monitor? Or could you attach log of "pactl list" here, thanks!

**Comment by weizhenwu** [comment]
No I didn't use external monitor during testing.
and here is the log from another platform which also encounter this issue
[pactl.log](https://github.com/canonical/checkbox/files/10358400/pactl.log)

**Comment by eugene-yujinwu** [comment]
@weizheenwu BTW, could you get the output of "pactl --version" here, thanks.

**Comment by weizhenwu** [comment]
> @weizheenwu BTW, could you get the output of "pactl --version" here, thanks.

15.99.1

**Comment by eugene-yujinwu** [comment]
This issue was caused by the "availability group" in the port attribute, which seems only present at Dell's platform. And a new PR was submitted to suppress this field since it seems by now nowhere will need it by now.

**Comment by eugene-yujinwu** [comment]
This issue was caused by the "availability group" in the port attribute, which seems only present at Dell's platform. And a new PR was submitted to suppress this field since it seems by now nowhere will need it by now.

**Comment by eugene-yujinwu** [comment]
one thing should be mentioned here:

For the attached paclt_Normal.log provided by @seankingyang , It also have the "availability group" but would not cause the exception. The reason is that when there was no "**_[OUT]/[IN]_**" before **_analog-output-headphones: Headphones (type: Headphones, priority: 9900, latency offset: 0 usec, availability group: Legacy 2, not available)_**
, it will be parsed as a GenericSimpleAttribute, like this: **_GenericSimpleAttribute(name='analog-output-headphones', value='Headphones (type: Headphones, priority: 9900, latency offset: 0 usec, availability group: Legacy 2, not available)') ,_** other than a **_GenericListAttribute(name='Ports', value=[Port(name='analog-input-internal-mic', label='Internal Microphone', priority=8900, availability='availability unknown')_**

[pactlList_Abnormal.log](https://github.com/canonical/checkbox/files/10454995/pactlList_Abnormal.log)
[pactlList_Normal.log](https://github.com/canonical/checkbox/files/10455002/pactlList_Normal.log)

**Comment by eugene-yujinwu** [comment]
@weizhenwu @seankingyang, I had submitted a pull request  to fix this issue. Just replace the file /usr/lib/python3/dist-packages/checkbox_support/parsers/pactl.py with  [checkbox-support/checkbox_support/parsers/pactl.py](https://github.com/canonical/checkbox/pull/307/commits/dad34d09bb76306d09bdb1a405c28cff047e1e62#diff-79d7cfa7871a3a9338ce044e0d9d0f51951c4319e6388fd79ae06a91bfa453c4) and run the microphone/headphone detect test. 
Thanks!
