### ISSUE TITLE
dupl

### ISSUE THREAD

**Issue by baconYao** [canonical/checkbox#28]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1988030

## Summary
The Sink will be changed during audio/playback_headphones testing

## Description
[Steps to reproduce]
1. Connect monitor via DP cable
2. Boot into OS
3. Run "checkbox-cli run com.canonical.certification::audio/playback_headphones"
4. Follow the steps to plug a headset and choose headphone on popup dialog
5. Check the Sink in Settings -> Sound, it should turn to the "Headphones - Build in-Audio" from "Speakers - Build in-Audio"
6. Press Enter to perform case
7. The Sink becomes "HDMI/Displayport-HDA NVDIA" and no sound from headset (issue happened)

[Expected result]
Sink should keep as "Headphones - Build in-Audio" and can hear sound from headset

[Actual result]
Sink is changed to "HDMI/Displayport-HDA NVDIA" during testing and back automatically.
See comment 2 (Video record)

[Failure rate]
Always

[Additional Info]
SKU ：KRPL-CFF-EVT-C1 (Desktop)
BIOS Version : 0.4.18
Image/Manifest : CFF X19
CPU : Raptor Lake 8+16 65W LGA ES2
GPU : T400 dGFx

## Attachment
[sink_will_be_changed_while_running_case.webm](https://user-images.githubusercontent.com/8318678/197912332-cd17c731-6ae8-4648-95a5-f5de97c1079d.webm)

**Comment by beliaev-maksim** [comment]
closed in favor of #72
