### ISSUE TITLE
Upgrade stress-ng to V0.15.04

### ISSUE THREAD

**Issue by LiaoU3** [canonical/checkbox#322]
### Bug Description

I was breaking the tests  run in stress/stress-ng-test-for-class-{stress-ng-class} from class based jobs into stressor based jobs.
You could view the code from here [my repo](https://github.com/LiaoU3/checkbox/tree/stress-ng-test-for-stressor).
However I found that while running the stressor **syscall**, it won't automatically kill its child process after the command end which cause the test job cannot be done(either pass, failed etc.), it just stuck there.
After discussing with [ColinIanKing](https://github.com/ColinIanKing)(the author of stress-ng) in [this issue](https://github.com/ColinIanKing/stress-ng/issues/256), we found that it's a bug before V0.14.06 and it's fixed after V0.15.03.
 - Snap : Then I tried manually build checkbox and checkbox-core snap locally, it worked!
 - Debian : I also tried manually upgrade stress-ng package, it worked too!

Hence I recommend we could upgrade stress-ng to V0.15.03(the latest version).
By the way, stress-ng in snap is V0.14.03 and in debian is V0.14.06, both of them have this bug.
### To Reproduce

1. run command **stress-ng --syscall 0 --timeout 30 --skip-silent --verbose** 
2. wait for 30 seconds
3. run command **top** or **htop**
4. we could find **syscall** child process is still there

### Environment

 - checkbox type (Debian and Snap)
 - checkbox version V2.0.0
 - stress-ng V0.14.03, V0.14.06

**Comment by bladernr** [comment]
Colin has a new version, 0.15.4 that should sync to Lunar tomorrow, could we get that pulled into the PPA?

And really, we need a way to build this in daily and stable PPAs that is reliable... maybe a recipe to build from Colin's github tree so that we can get his bug fixes quickly?

**Comment by dannf** [comment]
+1 on 0.15.04 - that version has a fix for LP:#1999731 that has been causing a lot of false positives.

**Comment by bladernr** [comment]
Also, Colin is building this periodically in an LP  PPA: https://launchpad.net/~colin-king/+archive/ubuntu/stress-ng/+packages for us, so maybe the answer is to just sync from there for the stable PPA...

**Comment by pieqq** [comment]
I just copied stress-ng 0.15.4 from Colin's PPA over to our Tetsting PPA:

https://launchpad.net/~checkbox-dev/+archive/ubuntu/testing/+packages?field.name_filter=stress&field.status_filter=published&field.series_filter=

@LiaoU3 you can give it a try and check if the new Checkbox release (in the Testing PPA) combined with this version of stress-ng fixes your issues.
