### ISSUE TITLE
New version of glmark2-es2 causes OpenGL doesn't render the canvas

### ISSUE THREAD

**Issue by baconYao** [canonical/checkbox#353]
### Bug Description

The new version, `2023.01`, of glmark2-es2 command leads to the OpenGL couldn't render the canvas.
snap info:
  - checkbox22, version:2.1, revision: 257

The previous versin of glmark2-es2 is 2021.12.
I've tried the checkbox22 with revision 208 (Built at 2022.12) and it contains the old version of glmark2-es2 (2021.12). DUT can run it without any problems.

### To Reproduce

1. Boot into OS
2. Install checkbox
  ```
  $ sudo snap install checkbox22
  $ sudo snap install checkbox-limerick-classic --classic --edge
  ```
3. Run `checkbox-limerick-classic.test-runner-kv260`
4. choose automated test plan
5. Execute the job "com.canonical.certification::graphics/1_glmark2-es2_drm-platform-fd4a0000_display" in graphic set

### Environment

- OS: Ubuntu 22.04 Desktop
- Checkbox Type: Snap
- Checkbox Version: 2.1.0 (revision: 257)

### Relevant log output

```shell
[Checkbox job `com.canonical.certification::graphics/1_glmark2-es2_drm-platform-fd4a0000_display` output]

stderr
------
Error: Failed to find suitable EGL config
Error: Error: Couldn't get GL visual config!
Error: main: Could not initialize canvas
```

### Additional context

- [glmark2 release info](https://github.com/glmark2/glmark2/tags)
- [Test result with 2021.12 version of glmark2](https://certification.canonical.com/hardware/202204-30240/submission/302691/test-results/) 
- [Test result with 2023.01 version of glmark2](https://certification.canonical.com/hardware/202204-30240/submission/302472/test-results/fail/?term=glm)

**Comment by pieqq** [comment]
We have a project starting soon that will be using Ubuntu desktop on an ARM platform, so this bug needs to be fixed by then.

**Comment by petitfou** [comment]
@baconYao hi, does it bug happen on Intel platforms ?

**Comment by zongminl** [comment]
On an x86/AMD64 platform, [graphics/{index}_glxgears_{product_slug}](https://github.com/canonical/checkbox/blob/016d878a88135b9f6968ce5070c08ae5150c423f/providers/base/units/graphics/jobs.pxu#LL294C5-L294C45) is the job being used, this job ([graphics/{index}_glmark2-es2_{product_slug}](https://github.com/canonical/checkbox/blob/016d878a88135b9f6968ce5070c08ae5150c423f/providers/base/units/graphics/jobs.pxu#LL557C5-L557C48)) is only adopted on ARM platforms

**Comment by zongminl** [comment]
The glmark2 part built in checkbox-core snap is actually pulled from it’s latest git commit: 
https://github.com/canonical/checkbox/blob/58148f92da037693e980b9600119337f4103100e/checkbox-core-snap/series22/snap/snapcraft.yaml#L412

The glmark2 package available in Ubuntu archive for Jammy is still 2021.02 so maybe we can use staged-package directly then it should be good enough

**Comment by pieqq** [comment]
I tested on one of these platform using the version of `glmark2-es2` coming from the repo:

2021.02-0ubuntu1, from the jammy/universe pocket

and running the `glmark2-es2` command works as expected. I guess we don't have to compile from source and we should rely on the version in the repos. That said, this also means there is problem upstream with the latest version, so I'll try to open a bug upstream.

**Comment by pieqq** [comment]
I've filed an issue upstream: https://github.com/glmark2/glmark2/issues/202
