### ISSUE TITLE
WIFI network test of WPA3-encrypted isn't workable for ubuntu 20.04

### ISSUE THREAD

**Issue by hanhsuan** [canonical/checkbox#361]
### Bug Description

According to [wiki](https://en.wikipedia.org/wiki/Wi-Fi_Protected_Access#WPA3), **The WPA3 standard also replaces the [pre-shared key](https://en.wikipedia.org/wiki/Pre-shared_key) (PSK) exchange with [Simultaneous Authentication of Equals](https://en.wikipedia.org/wiki/Simultaneous_Authentication_of_Equals) (SAE) exchange**. However the command in the test job is
 ```shell
nmcli c add con-name TEST_CON ifname wlp3s0 type wifi ssid 'cert-ax-wpa3-tel-l3-01' -- wifi-sec.key-mgmt wpa-psk wifi-sec.psk insecure ipv4.method auto ipv4.dhcp-timeout 30 ipv6.method ignore
```

if change wpa-psk to sae, it works fine for 20.04.
```shell
nmcli c add con-name TEST_CON ifname wlp3s0 type wifi ssid 'cert-ax-wpa3-tel-l3-01' -- wifi-sec.key-mgmt sae wifi-sec.psk insecure ipv4.method auto ipv4.dhcp-timeout 30 ipv6.method ignore
```

Have not idea why wpa-psk is workable for ubuntu 22.04.

### To Reproduce

run com.canonical.plainbox::wireless/wireless_connection_wpa3_ax_nm_{device} on Ubuntu 20.04

### Environment

- OS: ubuntu 20.04
- checkbox type: debian
- checkbox version: 2.1.0

### Relevant log output

```shell
+ nmcli c add con-name TEST_CON ifname wlp3s0 type wifi ssid 'cert-ax-wpa3-tel-l3-01' -- wifi-sec.key-mgmt wpa-psk wifi-sec.psk insecure ipv4.method auto ipv4.dhcp-timeout 30 ipv6.method ignore
Connection 'TEST_CON' (5fce0b3f-f561-40f2-8d55-d41a0d5302ee) successfully added.
+ nmcli c up TEST_CON
Error: Connection activation failed: The base network connection was interrupted
Hint: use 'journalctl -xe NM_CONNECTION=5fce0b3f-f561-40f2-8d55-d41a0d5302ee + NM_DEVICE=wlp3s0' to get more details.
```

**Comment by pieqq** [comment]
Hello @hanhsuan,

could you confirm a few things:

- Does the current version of the job work on 22.04? You wrote "Have not idea why wpa-psk is workable for ubuntu 22.04", so I suppose you tried, I just want to confirm
- Does your workaround (replacing `wpa-psk` with `sae`) work with 22.04?

Thanks!

**Comment by hanhsuan** [comment]
Hi @pieqq

* We have use checkbox 2.1.0 for multiple devices with ubuntu 22.04 last week, and could use nmcli command directly with no error.
* replacing `wpa-psk` to `sae` is working with ubuntu 22.04 for wpa3 only. 

Therefore, one more argument for `secured_connection` from `wifi_nmcli_test.py` will be needed, then modify job `id: wireless/wireless_connection_wpa3_ax_nm_{{ interface }}`

My option is that we could add `exchange` as argument, and the default value is `wpa-psk`.

**Comment by pieqq** [comment]
Yes, this is a good idea. Keep the script retro-compatible, but enhance it with additional features :)
