### ISSUE TITLE
If Checkbox snap updates while you are running Checkbox, you will lose your session due to a mismatch in test cases

### ISSUE THREAD

**Issue by djacobs98** [canonical/checkbox#366]
### Bug Description

I started running Checkbox on a DUT. (Automated test plan)
While the tests were running, Checkbox22 snap got updated.

Then the test plan did one of the reboot tests.  Due to a separate issue, Checkbox does not automatically resume after this test.

When I ran Checkbox to resume my test session, it was using the newer Checkbox.  There was now a mismatch in the test cases in Checkbox versus those in the session.  This caused a Python traceback.  The only recourse was to delete the session and start a new one.

There should be protections from having the Checkbox snap update itself while you are running Checkbox.

Currently when testing Core, I run this command to postpone updates:
sudo snap set system refresh.hold=$(date --date="+ 50 day" +%Y-%m-%dT%H:%M:%S%:z)

However it's quite a long command and not easily memorized.

If there was an easier way to delay or disable all snaps from updating that would be great.

### To Reproduce

Install previous version of Checkbox22.
Run Checkbox (test plan does not matter.)
While Checkbox is running, update Checkbox22.
Run the reboot test in the Automated test plan, or just reboot the box yourself.
Run Checkbox again and try to resume your session.

### Environment

OS: Desktop (Jammy)
Test plan: IIOTG Automated tests for Desktop.

### Relevant log output

```shell
I do not have the traceback any longer.  I had seen this before, and figured it just bad luck that I had had this happen to me twice within the past 3 weeks.
```

**Comment by Hook25** [comment]
Hello, this is the intended behaviour. To lock the updates of a package you can run the following:
```
# for snaps:
$ sudo snap refresh --hold=forever checkbox checkbox22
# for debs:
$ sudo apt-mark hold checkbox-ng checkbox-provider-resource checkbox-provider-certification-client checkbox-provider-base
```
remember to eventually run the following:
```
# for snaps
$ sudo snap refresh --unhold checkbox checkbox22
# for debs 
$ sudo apt-mark unhold checkbox-ng checkbox-provider-resource checkbox-provider-certification-client checkbox-provider-base
```

Hope this answers your question, if not please do reopen this issue!
