### ISSUE TITLE
The TPM test clevis-encrypt-tpm2/precheck always returns True

### ISSUE THREAD

**Issue by djacobs98** [canonical/checkbox#376]
### Bug Description

This precheck test is supposed to determine if the DUT has TPM (either a physical chip, or firmware implementation)

However this precheck always returns True. It doesn't seem to actually check anything. 

As a result, some TPM tests still run even though the system doesn't have TPM which causes confusion. (and more errors.)

### To Reproduce

1. Run the Desktop Automated tests for TPM on a system that doesn't have TPM (or TPM is disabled in the BIOS.)

Expectation: All TPM tests should skip.
Reality: 
TPM/precheck, detect-ecc and detect-rsa-capabilities all pass but shouldn't.

The TPM ecc and rsa functional tests fail as expected but should not have run at all if TPM is not supported by this system.

### Environment

IOTG Jammy Desktop proposed image 20230224.
Checkbox22 snap.  Checkbox-iiotg-classic provider as a snap.

Automated test plan for Desktop chosen.

Run the TPM tests.

If the DUT does not support TPM, the expectation is all tests should skip.  However, 4 of them still run, and 2 

### Relevant log output

```shell
This is the checkbox test component of another bug filed on Launchpad:
https://bugs.launchpad.net/lookout-canyon/+bug/2012030

All the logs are there.

You can also view this DUT's C3 submission (scroll to TPM):
https://certification.canonical.com/hardware/202212-30958/submission/304871/
```

**Comment by yphus** [comment]
Problem here is that the manifest entry corresponding to TPM2 was set to true:

```
ns: com.canonical.certification
name: checkbox-provider-tpm2
has_tpm2_chip: True 
```

I then suggest to fix the manifest for 202212-30958 to avoid running a single TPM test.

**Comment by djacobs98** [comment]
202212-30958 is supposed to support TPM however for some reason, this one uses PTT as opposed to a physical TPM chip like its "identical" brother. Furthermore, PTT wasn't implemented until a later version of the BIOS.  So we unknowingly had 1 unit that really had TPM and one that really didn't.

The real danger here is that the entire TPM feature was marked as "Pass" on 202212-30958 because one test erroneously passed and the rest were skipped.  It wasn't until I was checking the BIOS for another issue that I noticed that TPM was actually disabled on this device.

This is why I am requesting there is a test that actually checks the hardware for the presence of TPM or PTT, and  actually fails.
