### ISSUE TITLE
Interrupt menu uses outdated master/slave nomenclature

### ISSUE THREAD

**Issue by Hook25** [canonical/checkbox#444]
### Bug Description

The interrupt menu is still using the outdated nomenclature to refer to remote and service

### To Reproduce

1. Launch `checkbox-cli service`
2. Lauch `checkbox-cli remote $SERVICE_IP`
3. Ctrl+C in the checkbox remote CLI

### Environment

N/A

### Relevant log output

```shell
What do you want to interrupt?
    (X) Cancel the interruption and resume the session (ESC)
    ( ) Kill test in progress and move on to next
    ( ) Disconnect the master (Same as CTRL+C)
    ( ) Stop the checkbox slave @127.0.0.1
    ( ) Abandon the session on the slave @127.0.0.1
```

**Comment by yphus** [comment]
Tracked [here](https://warthogs.atlassian.net/browse/CHECKBOX-657)
