### ISSUE TITLE
checkbox remote partially ignores configuration 

### ISSUE THREAD

**Issue by Hook25** [canonical/checkbox#446]
### Bug Description

In [439](https://github.com/canonical/checkbox/pull/439#issuecomment-1536050413) it seems that some of the parameters in configuration files are not propagated/ignored on the remote. 

This configuration file has no effect on remote, who still presents the test selection screen
```ini
[test selection]
forced = yes
```

### To Reproduce

1. Create a configuration file as described and put it in `/etc/xdg` or `~/.config/`
2. Launch remote/service
3. Select a test plan on remote

### Environment

N/A

### Relevant log output

```shell
N/A
```

**Comment by pieqq** [comment]
Once this gets fixed, Metabox scenarios should be updated to test this. At the very basic, we should make sure than if we put any UI-related config in a config file on the device under test (e.g. a `forced` test selection in `/etc/xdg/checkbox.conf`) and launch it using Checkbox remote without providing any launcher, the job selection screen is skipped.

**Comment by kissiel** [comment]
Where 

> 1. Create a configuration file as described and put it in `/etc/xdg` or `~/.config/`

On which host is the file located?

**Comment by Hook25** [comment]
Closing as this is now fixed
