### ISSUE TITLE
Check criteria for wifi reconnect in warm-reboot stress

### ISSUE THREAD

**Issue by rickwu666666** [canonical/checkbox#450]
### Enhancement Proposal

The one of current criteria is checking if the WiFi re-connects back to the previous AP or not ( by checking if WiFi is connected to the same BSSID). 
However, if the test environment has multiple AP broadcasts with the same SSID. And user connected to WiFi by SSID at first, then it has a chance that re-connect to a different AP that has the same SSID. In this kind of scenario, the warm-reboot stress check will be failed. This will be a false alarm for this test job.

**Comment by pieqq** [comment]
Another issue mentions this: #457.

@rickwu666666 do you confirm this happens in `warm-boot-stress-test` and `cold-boot-stress-test` jobs? If so, I think we can close this issue.

**Comment by rickwu666666** [comment]
Yes, it's the same story. thanks Pierre.
