### ISSUE TITLE
cold/warm boot stress jobs check the BSSID of the wireless AP, not the SSID

### ISSUE THREAD

**Issue by yphus** [canonical/checkbox#457]
### Bug Description

After warm or cold reboots, the test  checks that the system re-connects to the same AP.
But it check the BSSID of the AP, not the SSID.
it's basically assuming that there's a single physical access point vs. a typical roaming setup which has more than one physical AP all with the same SSID.

Current command: `nmcli -t -f active,BSSID d w l`
Expected command: `nmcli -t -f active,SSID d w l`

The command above is used multiple time in jobs defined in the [stress/boot.pxu](https://github.com/canonical/checkbox/blob/main/providers/base/units/stress/boot.pxu) file. All of them should be fixed of course.

In addition to the command itself, it would be nice to expand the tests description to actually explain what's being checked (wireless AP, lspci and lsusb after reboots).

### To Reproduce

Start a checkbox remote session and select one of the boot stress test plan:

- Warm boot stress test (id: warm-boot-stress-test)
- Cold boot stress test (id: cold-boot-stress-test)

### Environment

Reported on UC20 but it's not UC specific.

**Comment by pieqq** [comment]
Closed with #517
