### ISSUE TITLE
LP1956293: "audio/valid-sof-firmware-sig" Should not be tested with the machine does not use Intel DMIC to PCH or Soundwire  feature

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#48]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1956293

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2022-01-04 06:44:48	| 6	| Critical	| False  	|

## Description
Not all machines use Intel DMIC to PCH or Soundwire Feature.  When this test is run on those machines, it always fail. The test case needs to add more resource check to make sure it only run on the machine which uses DMIC or Soundwire.

plugin: shell
category_id: com.canonical.plainbox::audio
id: audio/valid-sof-firmware-sig
requires:
 device.category == 'AUDIO'
 package.name == 'linux-firmware'
command:
 fail=0
 for fw in /lib/firmware/intel/sof/sof-*.ri;
 do
     # shellcheck disable=SC2016
     if xxd "${fw}" | grep -q '$CPD'; then
         if ! sof_ri_info.py --valid "${fw}";
         then
             fail=1
         fi
     fi
 done
 exit $fail
_description: Valid sof firmware signature

## Attachments
No attachments

Tags:
['cbox-5']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~chihchun wrote on 2022-01-04 06:58:50:
This test job does not depends on the hardware features of DMIC, SoF, but simply checking if the firmware shipped with the image is signed with the correct key from Intel.

##### https://launchpad.net/~chihchun wrote on 2022-01-06 08:28:56:
The issue is missing production key for ehl[1] and ADL[2], which are all landed as well.

[1] Add JSL, TGL_H and TGL_LP production key - https://git.launchpad.net/plainbox-provider-checkbox/commit/?id=611bc1f9e888aec621e6c88a0fcab2c7e3d9348f
[2] Add ADL production key - https://git.launchpad.net/plainbox-provider-checkbox/commit/bin/sof_ri_info.py?id=da7353fdafacd7d5aefa9bb622a962df53aeeead

**Comment by pieqq** [comment]
@linjuiche Is this still happening, or did adding the productions keys as mentioned by Rex help?

**Comment by scotthu27** [comment]
@pieqq it fixed by TGL_H & TGL_L/P production key. Here is the patch on [github](https://github.com/thesofproject/sof/commit/d2a3ec2273f2efc6e63221ec8022cbd5a713e869)
