### ISSUE TITLE
com.canonical.plainbox::networking info_device1_enp1s0 requires ethtool but still passes if it's not installed

### ISSUE THREAD

**Issue by djacobs98** [canonical/checkbox#488]
### Bug Description

The informational tests for the Ethernet interfaces relies on ethtool to get some information about them.

However if ethtool is not installed, the test still passes with the result of "ethtool not installed."

If this test requires ethtool, ethtool should be provided by checkbox.

### To Reproduce

1. Select Desktop Manual test plan.
2. Select Informational tests for Ethernet interfaces.

### Environment

OS: Jammy Desktop + RT kernel.
Checkbox22 snap ver. 2.6
Checkbox-iiotg-classic (latest/stable, rev 49)

**Comment by djacobs98** [comment]
Screenshot
![No_Ethtool_Screenshot](https://github.com/canonical/checkbox/assets/79291680/08de0b45-c235-4e4c-8517-bbf4d721f560)

**Comment by kissiel** [comment]
Fix is here:
https://github.com/canonical/checkbox/pull/492

**Comment by kissiel** [comment]
@djacobs98 should the test be skipped or failed if there's no ethtool?

**Comment by djacobs98** [comment]
This is a tangled problem.
There are 2 problems here.
1. ethtool is actually installed, so this error message is incorrect.
2. The script got some sort of error trying to probe this Ethernet interface - which is accurate, it's not a real interface.  So the test should fail for it.

**Comment by djacobs98** [comment]
This is a tangled problem.
There are 2 problems here.
1. ethtool is actually installed, so this error message is incorrect.
2. The script got some sort of error trying to probe this Ethernet interface - which is accurate, it's not a real interface.  So the test should fail for it.
I think it will be easier to open new issues for these.
