### ISSUE TITLE
LP1958482: The test job led/mute and led/microphone-mute does not included in the  test plan led-cert-manual

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#49]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1958482

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2022-01-20 04:14:52	| 6	| Critical	| False  	|

## Description
The test job 'com.canonical.certification::led/mute' and 'com.canonical.certification::led/microphone-mute' does not include in the test plan 
led-cert-manual, but the test job after-suspend-led/mute and after-suspend-led/microphone-mute was include in the after-suspend-led-cert-full. For those test plan include the led-cert-manual and after-suspend-led-cert-full, it will not run led/mute and led/microphone-mute before suspend, but run twice after suspend.

I thought the led/mute and led/microphone-mute here is just missed and should be added into the led-cert-manual.

## Attachments
[microphone_mute_led.png](https://api.launchpad.net/devel/bugs/1958482/+attachment/5555738/data)

Tags:
['cbox-6']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~eugene2021 wrote on 2022-02-24 02:44:36:
A merge request had been submitted.
https://code.launchpad.net/~eugene2021/plainbox-provider-checkbox/+git/plainbox-provider-checkbox/+merge/414388

##### https://launchpad.net/~kent-jclin wrote on 2022-02-24 02:46:54:
Checkbox merge request for the fix: https://code.launchpad.net/~eugene2021/plainbox-provider-checkbox/+git/plainbox-provider-checkbox/+merge/414388

**Comment by kissiel** [comment]
This got fixed in [9bfdcf68882377faab9d69b7a338b744f4c3d2dd](https://git.launchpad.net/~eugene2021/plainbox-provider-checkbox/commit/?id=9bfdcf68882377faab9d69b7a338b744f4c3d2dd). 

I checked the repo, and it has really landed even though the breadcrumbs are not available.
