### ISSUE TITLE
fwts test, uefirtvariable, aborts due to missing efi test driver, but Checkbox simply says the test was killed and the log file is corrupt.

### ISSUE THREAD

**Issue by djacobs98** [canonical/checkbox#510]
### Bug Description

This test should produce a log file of the output for the fwts test, uefirtvariable regardless of whether the test passes, fails, or aborts.

However, the wrapper for this test simply reports "Killed" with no other output, and no log file.

firmware/fwts_uefirtvariable uses a wrapper script that eventually calls fwts with the following flags:

fwts -q --stdout-summary -r "$PLAINBOX_SESSION_SHARE"/fwts_{name}.log uefirtvariable
(name=uefirtvariable)

If you run this command from the command line, you are informed that the test aborts, but the logfile is written and contains information on why the test was aborted. In this case, my DUT is lacking the efi test driver. (LP#2021561)

However when run by Checkbox, the test simply reports "Killed" and the resulting log file that is attached is corrupted.  The log file is not a text file, gzip archive, or tar.xz tarball.

### To Reproduce

Install the checkbox22 snap
Install checkbox-iiotg-classic --classic --channel=latest/edge
checkbox-iiotg-classic.test-runner

Select Automated for Desktop
Select Firmware
Select fwts_uefirtvariable & its attach log file task.

Test should pass, logfile should be added to the attachments in the submission tarball.
Instead, the test fails but the only output is "Killed" and the logfile is corrupted.

### Environment

IOTG Jammy Desktop with RT-GA kernel installed post-install.

### Relevant log output

```shell
Additional information about the actual output from when this test fails can be found at LP#2021561.
```

**Comment by pieqq** [comment]
Related to #501 and #502.

**Comment by pieqq** [comment]
This might be a project-related issue, or a FWTS issue. QA team is investigating.

**Comment by pieqq** [comment]
I'll close this one. If QA finds something, they will open a new bug.
