### ISSUE TITLE
LP1976100: CPU Stress test was deleted from bionic suitte

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#52]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-certification-server/+bug/1976100

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| In Progress	| 2022-05-27 16:41:04	| 6	| Critical	| False  	|

## Description
in commit 9cda18c I accidentally removed stress/cpu_stress_ng_test from server-full-18.04 while doing a cleanup and moving many things to nested testplans.

This restores that test to the testplan.

## Attachments
No attachments

Tags:
['servcert-380']

**Comment by kissiel** [comment]
Fixed by this MR:
https://code.launchpad.net/~bladernr/plainbox-provider-certification-server/+git/plainbox-provider-certification-server/+merge/423559
