### ISSUE TITLE
AMD Hygon Dhyana CPUID

### ISSUE THREAD

**Issue by mreed8855** [canonical/checkbox#529]
### Bug Description

Currently, the cpuid.py script cannot identify  Hygon Dhyana CPUS.  

https://certification.canonical.com/hardware/202306-31645/submission/316082/test/82097/result/33739244/

### To Reproduce

1. Run the canonical-certification-server test suite. 

### Environment

-Jammy, Kinetic, Lunar

**Comment by Hook25** [comment]
Closing as fixed in #928
