### ISSUE TITLE
LP1982288: Displayport job be skipped since gnome-randr cannot get DP information

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#56]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1982288

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Confirmed	| 2022-07-20 03:13:19	| 6	| Critical	| False  	|

## Description
[Summary]
There are two output port, HDMI and Displayport, on "All In One" DUT.
But "gnome-randr" cannot get the information of Displayport, cause the checkbox cases related to Displayport are skipped automatically.
  - See: https://certification.canonical.com/hardware/202207-30419/submission/272693/test/168578/result/27221500/

If Windowing System is Wayland, checkbox grabs the info of monitor via  "gnome-randr" command.
   commit: https://git.launchpad.net/plainbox-provider-resource/commit/?id=8901ac96bb0b52d54c9501240b07b6a95783ced9

[Steps to reproduce]
1. Boot into OS
2. Run 'gnome-randr' command to get the information of physical monitors

[Expected result]
It should give HDMI and DP information

[Actual result]
Only HDMI information

gnome-randr's output on DAKAR-DGPU-EVT-C6

```
supports-mirroring: true
layout-mode: physical
supports-changing-layout-mode: false
global-scale-required: false
renderer: "native"
legacy-ui-scaling-factor: 1

logical monitor 0:
x: 0, y: 0, scale: 1, rotation: normal, primary: yes
associated physical monitors:
 HDMI-1 DEL OptiPlex AIO 0x44474c78

HDMI-1 DEL OptiPlex AIO 0x44474c78
  1920x1080@62.040439605712891	1920x1080 	62.04*+   	[x1.00+, x2.00]
                  1920x1080@60	1920x1080 	60.00     	[x1.00+, x2.00]
  1680x1050@59.883251190185547	1680x1050 	59.88     	[x1.00+, x2.00]
   1440x900@59.901458740234375	1440x900  	59.90     	[x1.00+]
  1280x1024@60.019741058349609	1280x1024 	60.02     	[x1.00+]
                   1280x720@60	1280x720  	60.00     	[x1.00+]
   1024x768@60.003841400146484	1024x768  	60.00     	[x1.00+]
    800x600@60.316539764404297	800x600   	60.32     	[x1.00+]
is-builtin: false
display-name: "Dell Inc. 23\""
```

[Failure rate]
always

[Additional Info]
CID: 202207-30419, 202207-30420
SKU: DAKAR-DGPU-EVT-C6, DAKAR-UMA-EVT-C4
Image: dell-bto-jammy-jellyfish-chansey-X21-20220704-2.iso

## Attachments
[HDMI and Displayport output port](https://api.launchpad.net/devel/bugs/1982288/+attachment/5604199/data)
[DAKAR-UMA-EVT-C2_only_DP_output](https://api.launchpad.net/devel/bugs/1982288/+attachment/5604201/data)
[output.tar.xz](https://api.launchpad.net/devel/bugs/1982288/+attachment/5611831/data)

Tags:
['jammy-test']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~baconyao wrote on 2022-07-20 03:18:12:
Other information:

SKU: DAKAR-UMA-EVT-C2  (202207-30418) and DP case is skipped as well.

This SKU has one Displayport only, its gnome-randr info

=============================================================
supports-mirroring: true
layout-mode: physical
supports-changing-layout-mode: false
global-scale-required: false
renderer: "native"
legacy-ui-scaling-factor: 1

logical monitor 0:
x: 0, y: 0, scale: 1, rotation: normal, primary: yes
associated physical monitors:
	eDP-1 RTK 0x40b0 0x12345678

eDP-1 RTK 0x40b0 0x12345678
                  1920x1080@60	1920x1080 	60.00*+   	[x1.00+, x2.00]
  1680x1050@59.954250335693359	1680x1050 	59.95     	[x1.00+, x2.00]
   1600x900@59.946022033691406	1600x900  	59.95     	[x1.00+]
  1440x1080@59.988838195800781	1440x1080 	59.99     	[x1.00+, x2.00]
   1440x900@59.887443542480469	1440x900  	59.89     	[x1.00+]
  1400x1050@59.978443145751953	1400x1050 	59.98     	[x1.00+]
   1368x768@59.882049560546875	1368x768  	59.88     	[x1.00+]
   1280x960@59.939048767089844	1280x960  	59.94     	[x1.00+]
   1280x800@59.810325622558594	1280x800  	59.81     	[x1.00+]
   1280x720@59.855125427246094	1280x720  	59.86     	[x1.00+]
   1152x864@59.958633422851562	1152x864  	59.96     	[x1.00+]
   1024x768@59.920131683349609	1024x768  	59.92     	[x1.00+]
    800x600@59.861404418945312	800x600   	59.86     	[x1.00+]
is-builtin: true
display-name: "Built-in display"
=============================================================

##### https://launchpad.net/~clairlin wrote on 2022-07-29 05:54:09:
Issue can reproduce on Boggle24 (stella AIO project)

CID:202112-29751
C3 results:https://certification.canonical.com/hardware/202112-29751/submission/274256/test-results/?term=displayport

##### https://launchpad.net/~pieq wrote on 2022-08-26 07:05:00:
@PeiYao, I would like to compare the output from gnome-randr to the one from xrandr.

Could you follow these steps and attach the output here?

1. Connect a screen to the DisplayPort
2. In a Wayland session (the default), run the following commands and capture their output:
    - gnome-randr
    - xrandr (even though you are in a Wayland session, this command should still output something)
3. Log out, and using the little cog icon at the bottom right of the user selection screen, select "Ubuntu on Xorg" (see screenshot[1])
4. Now that you are in the X11 session, run the following command and capture their output:
    - xrandr

Thanks!

[1] https://linuxconfig.org/wp-content/uploads/2022/01/02-how-to-enable-disable-wayland-on-ubuntu-22-04-desktop.png

##### https://launchpad.net/~baconyao wrote on 2022-08-26 09:49:17:
@Pier

Attachment is the gnome-randr and xrandr output for #5

##### https://launchpad.net/~weichenwu wrote on 2022-09-21 05:19:51:
This issue is also observed on OAS4-DVT1-C4/OAS6-DVT1-C2. 
The system has bulid-in HDMI port but test cases were skipped since display.hdmi was marked as non-supported

**Comment by pieqq** [comment]
1. Create manifests (in `providers/base/graphics/manifest.pxu`) for the different ports expected to be tested (VGA, DVI, HDMI, DP...): `has_vga`, `has_hdmi`, `has_displayport`, etc.
2. Review all the graphics jobs and add a requirement based on the manifest, e.g.:

```
imports: from com.canonical.plainbox import manifest
requires: manifest.has_hdmi == 'True'
```
3. Check that nothing breaks...
