### ISSUE TITLE
Missing the Audio category in device resource on Raspberry Pi 4

### ISSUE THREAD

**Issue by baconYao** [canonical/checkbox#563]
### Problem

On Raspberry PI 4, I found there's no AUDIO related record in the device resource, but I could found lot's of audio record via `udevadm info --export-db`.

Since missing AUDIO resource, a bunch of jobs require `device.category == AUDIO` are judged as `not supported`.

### To Reproduce

1. Install Checkbox Snap
2. Run `checkbox.checkbox-cli run com.canonical.certification::audio/list_devices`

### Environment

- OS: Jammy Desktop LTS
- Checkbox Type: Snap
- Chebox Version: 
  ```
  u@u-desktop:~$ snap list
  Name                       Version           Rev    Tracking         Publisher            Notes
  checkbox                   2.7               2474   latest/stable    ce-certification-qa  classic
  checkbox22                 2.7+git2eb1a03    428    latest/edge      ce-certification-qa  -
  ```
- Hardware being tested: Raspberry PI 4 Model B

### Relevant log output

```shell
==============[ Running job 3 / 3. Estimated time left: 0:00:01 ]===============
-----------------------------[ audio/list_devices ]-----------------------------
ID: com.canonical.certification::audio/list_devices
Category: com.canonical.plainbox::audio
Job cannot be started because:
 - resource expression "device.category == 'AUDIO'" evaluates to false
Outcome: job cannot be started
Finalizing session that hasn't been submitted anywhere: checkbox-run-2023-06-15T04.51.26
==================================[ Results ]===================================
 ☑ : Collect information about hardware devices (udev)
 ☑ : Collect information about installed software packages
 ☐ : audio/list_devices
```

### Additional context

A simple submission of running Audio Test Set in Cert Desktop 22.04 Test Plan

[missing-audio-category-submission_2023-06-15T04.40.24.363685.zip](https://github.com/canonical/checkbox/files/11752907/missing-audio-category-submission_2023-06-15T04.40.24.363685.zip)

**Comment by baconYao** [comment]
Hi @pieqq, I think this is critical and urgent issue since all of the devices who are ARM architecture have this problem.

**Comment by diohe0311** [comment]
This is fixed!
https://certification.canonical.com/hardware/201911-27506/submission/343677/
