### ISSUE TITLE
LP1982450: No Gtk window while executing camera/display_video0 job

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#58]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1982450

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Confirmed	| 2022-07-21 05:56:25	| 6	| Critical	| False  	|

## Description
[Summary]
While running display_video0 case, the Gtk window doesn't show up

[Steps to reproduce]
1. Boot into OS
2. Run 'checkbox-cli'
3. Choose 'com.canonical.certification::client-cert-desktop-22-04-manual' test plan
4. Run Camera tests

[Expected result]
The Gtk Window should appear on the screen while testing display_video0

[Actual result]
1. No Gtk window
2. Camera works well via Cheese App or Webcamtests.com website.

Video record: https://drive.google.com/file/d/1870WQaPAGyWebEGQhqtBTH2QBL-hYeN_/view?usp=sharing

[Failure rate]
Always

[Checkbox job `com.canonical.certification::camera/display_video0` output]

stderr
------
../src/intel/isl/isl.c:2216: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.

[Additional information]
CID: 202207-30419, 202207-30416
SKU: DKR-DGPU-EVT-C6
Image: canonical-oem-somerville-jammy-amd64-20220504-33+jellyfish-chansey+X21
system-manufacturer: Dell Inc.
system-product-name: OptiPlex AIO Plus 7410
bios-version: 0.4.16
CPU: Genuine Intel(R) 0000 (32x)
GPU: 0000:00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:a780] (rev 0c)
0000:03:00.0 Display controller [0380]: Advanced Micro Devices, Inc. [AMD/ATI] Device [1002:743f] (rev c3)
kernel-version: 5.17.0-1012-oem

[Stage]
Issue reported and logs collected at a later stage

## Attachments
[checkbox-session.tgz](https://api.launchpad.net/devel/bugs/1982450/+attachment/5604495/data)
[snap_list.log](https://api.launchpad.net/devel/bugs/1982450/+attachment/5604496/data)
[acpidump.log](https://api.launchpad.net/devel/bugs/1982450/+attachment/5604497/data)
[sosreport-u-OptiPlex-AIO-Plus-7410-2022-07-21-ctyxbqx.tar.gz](https://api.launchpad.net/devel/bugs/1982450/+attachment/5604498/data)

Tags:
['oem-camera']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~kent-jclin wrote on 2022-07-21 05:56:49:
Automatically attached

##### https://launchpad.net/~kent-jclin wrote on 2022-07-21 05:56:51:
Automatically attached

##### https://launchpad.net/~kent-jclin wrote on 2022-07-21 05:56:59:
Automatically attached

##### https://launchpad.net/~kent-jclin wrote on 2022-07-21 05:57:14:
Automatically attached

**Comment by yphus** [comment]
Please reopen if the problem is found on another certified system.
