### ISSUE TITLE
miscellanea/cpuid doesn't recognize 0xaa0f02 as code for AMD EPYC 9754

### ISSUE THREAD

**Issue by rodwsmith** [canonical/checkbox#611]
### Bug Description

The miscellanea/cpuid test is failing when presented with an AMD EPYC 9754 CPU with an ID of 0xaa0f02. This code should be added to the script.

### To Reproduce

Observed in the following certificate requests:

https://certification.canonical.com/certificates/2307-14800/
https://certification.canonical.com/certificates/2307-14817/

### Environment

Lenovo ThinkSystem SR645 V3 (oahu) under Ubuntu 20.04 and 22.04

### Relevant log output

```shell
CPU Model: AMD EPYC 9754 128-Core Processor
Unable to determine CPU Family for this CPUID: 0xaa0f02
```

**Comment by Hook25** [comment]
Closing as solved in #612
