### ISSUE TITLE
LP1829970: [Drift-3] [Ironhide-T-3] Test case 'graphics/x_driver_version_PCI_ID_0xXXXX' is always failed on Nvidia driver 430.

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#63]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1829970

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Confirmed	| 2019-05-22 06:32:43	| 6	| High	| False  	|

## Description
Test machine: Drift-3
Image: sutton-mccarthy-bionic-amd64-20190520-115
CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
GPU: VGA compatible controller [0300]: Intel Corporation Device [8086:3ea0] (prog-if 00 [VGA controller]) + 3D controller [0302]: NVIDIA Corporation Device [10de:1d13] (rev a1)
BIOS: N2IET62W (1.40)

Steps:
1. Install image on Drift-3.
2. Install checkbox and execute it.
3. Checked test case 'graphics/1_driver_version_PCI_ID_0x3ea0'.
4. Checked test case 'graphics/2_driver_version_PCI_ID_0x1d13'.
5. Checked test case 'Manual test of suspend function'
6. Checked test case 'Test X driver/version after suspend for Intel Corporation PCI ID 0x3ea0'
7. Checked test case 'Test X driver/version after suspend for NVIDIA Corporation PCI ID 0x1d13'
8. Test those cases and verify the results.

Expected result:
All test cases should be pass.

Actual result:
Test cases are failed always
'graphics/1_driver_version_PCI_ID_0x3ea0';
'graphics/2_driver_version_PCI_ID_0x1d13';
'Test X driver/version after suspend for Intel Corporation PCI ID 0x3ea0';
'Test X driver/version after suspend for NVIDIA Corporation PCI ID 0x1d13'.

*******************************************************************
--------------[ Running job 1 / 2. Estimated time left: 0:00:01 ]---------------
---------[ Test X driver/version for NVIDIA Corporation PCI ID 0x1d13 ]---------
ID: com.canonical.certification::graphics/2_driver_version_PCI_ID_0x1d13
Category: com.canonical.plainbox::graphics
... 8< -------------------------------------------------------------------------
------------- VIDEO DRIVER INFORMATION -------------
------------- HYBRID GRAPHICS CHECK ----------------
Graphics Chipset: Intel (8086:3ea0)
Graphics Chipset: NVIDIA (10de:1d13 (rev a1))
Loaded DDX Drivers: modesetting, fbdev, vesa
Hybrid Graphics: yes
ERROR: No video driver loaded! Possibly in failsafe mode!
------------------------------------------------------------------------- >8 ---
Outcome: job failed
--------------[ Running job 2 / 2. Estimated time left: 0:00:00 ]---------------
---------[ Test X driver/version for Intel Corporation PCI ID 0x3ea0 ]----------
ID: com.canonical.certification::graphics/1_driver_version_PCI_ID_0x3ea0
Category: com.canonical.plainbox::graphics
... 8< -------------------------------------------------------------------------
ERROR: No video driver loaded! Possibly in failsafe mode!
------------- VIDEO DRIVER INFORMATION -------------
------------- HYBRID GRAPHICS CHECK ----------------
Graphics Chipset: Intel (8086:3ea0)
Graphics Chipset: NVIDIA (10de:1d13 (rev a1))
Loaded DDX Drivers: modesetting, fbdev, vesa
Hybrid Graphics: yes
------------------------------------------------------------------------- >8 ---
Outcome: job failed
********************************************************************

Notes:
Run those test cases on a laptop with nvidia-418

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
-------------[ Running job 31 / 32. Estimated time left: unknown ]--------------
---------[ Test X driver/version for Intel Corporation PCI ID 0x3e9b ]----------
ID: com.canonical.certification::graphics/1_driver_version_PCI_ID_0x3e9b
Category: com.canonical.plainbox::graphics
... 8< -------------------------------------------------------------------------
------------- VIDEO DRIVER INFORMATION -------------
Video Driver: nvidia
Driver Version: 418.56

------------- HYBRID GRAPHICS CHECK ----------------
Graphics Chipset: Intel (8086:3e9b)
Graphics Chipset: NVIDIA (10de:1cbd)
Loaded DDX Drivers: nouveau, modesetting, fbdev, vesa
Hybrid Graphics: yes
------------------------------------------------------------------------- >8 ---
Outcome: job passed
-------------[ Running job 32 / 32. Estimated time left: unknown ]--------------
---------[ Test X driver/version for NVIDIA Corporation PCI ID 0x1cbd ]---------
ID: com.canonical.certification::graphics/2_driver_version_PCI_ID_0x1cbd
Category: com.canonical.plainbox::graphics
... 8< -------------------------------------------------------------------------
------------- VIDEO DRIVER INFORMATION -------------
Video Driver: nvidia
Driver Version: 418.56

------------- HYBRID GRAPHICS CHECK ----------------
Graphics Chipset: Intel (8086:3e9b)
Graphics Chipset: NVIDIA (10de:1cbd)
Loaded DDX Drivers: nouveau, modesetting, fbdev, vesa
Hybrid Graphics: yes
------------------------------------------------------------------------- >8 ---
Outcome: job passed

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

## Attachments
[nvidia-dpkg.list](https://api.launchpad.net/devel/bugs/1829970/+attachment/5265466/data)
[nvidia-bug-report.log.gz](https://api.launchpad.net/devel/bugs/1829970/+attachment/5265467/data)
[system-logs.tar.gz](https://api.launchpad.net/devel/bugs/1829970/+attachment/5265468/data)

Tags:
['affect-submission', 'ce-qa-concern']

**Comment by kissiel** [comment]
I think this was a platform specific bug, as such this as a checkbox bug should be closed.
