### ISSUE TITLE
LP1831824: Missing after suspend amdgpu glxgears and valid_opengl_renderer test

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#64]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1831824

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2019-06-06 02:20:47	| 6	| High	| False  	|

## Description
Because of "suspend/{index}_glxgears_after_suspend_{product_slug}" depends on "suspend/{index}_suspend_after_switch_to_card_{product_slug}", for amdgpu the test "suspend/{index}_glxgears_after_suspend_{product_slug}" won't run when "suspend/{index}_suspend_after_switch_to_card_{product_slug}" failed.

Since the "suspend/{index}_suspend_after_switch_to_card_{product_slug}" will fail when the graphic is amdgpu, but we do need to confirm amdgpu still can run glxgears without problem after suspend.

The tests affect with amdgpu are:
graphics/{index}_valid_opengl_renderer_{product_slug}
graphics/{index}_switch_card_{product_slug}_xenial
graphics/{index}_auto_switch_card_{product_slug}

Also, we found graphics/{index}_valid_opengl_renderer_{product_slug} not in any after suspend test plan too.

## Attachments
No attachments

Tags:
['ce-qa-concern']

**Comment by kissiel** [comment]
This got fixed by:
a4fd6e84a5d173ffde12ec72db2404c2cfe4ac44
and
161e9f3ffa95ca6a12ec96162411f7c9a44d38aa
