### ISSUE TITLE
The stress-ng version needs to be bumped to a version later than 0.15.10.

### ISSUE THREAD

**Issue by rickwu666666** [canonical/checkbox#641]
### Enhancement Proposal

We are facing stress-ng stressor _af-alg_ test failures on the NXP platform. However, the issue has been fixed in stress-ng versions later than 0.15.10. For more details, please take a look at the [stress-ng issue](https://github.com/ColinIanKing/stress-ng/issues/294)
Many thanks.

**Comment by bladernr** [comment]
Please test what is in the daily PPA, as that is at 0.16.02 currently.  If that works, then we can just copy that into the stable PPA at some point.

**Comment by rickwu666666** [comment]
I tried stress-ng v0.16.02, but it seems to have another issue on the i.MX platform.
https://certification.canonical.com/hardware/202304-31534/submission/324547/test-results/fail/

**Comment by zongminl** [comment]
Fixed by https://github.com/canonical/checkbox/pull/1425, now stress-ng comes from maintainer's PPA (ppa: colin-king/stress-ng)

Now the stress-ng version in checkbox is: stress-ng, version 0.18.03 (gcc 9.4.0, x86_64 Linux 5.15.0-119-generic)
