### ISSUE TITLE
LP1832688: Improve lid tests

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#65]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1832688

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Confirmed	| 2019-06-13 08:16:09	| 6	| High	| False  	|

## Description
LP:868678 lid_open and lid_close tests need to be re-written
​LP:1103925 lid_open test does not make sense
LP:1832683 Test case lid_open was done immediately
LP:1832678 Automated power-management/lid test

Following the idea to automated power-management/lid test (suspend), I am thinking we could merge lid(suspend), lid_close and lid_open into one or improve the tests.

The idea is tester doing the lid close/open one time, then checkbox can verify the status of suspend/resume, lid_close/open from dmesg/kernel log and /proc/acpi/button/lid/*/state automatically

## Attachments
No attachments

Tags:
['ce-qa-concern']

**Comment by yphus** [comment]
Set as won't fix. A zapper add-on will cover lid tests next cycle.
