### ISSUE TITLE
Confusing error message: "Remote API version mismatch. Service uses: 11. Remote uses: 12"

### ISSUE THREAD

**Issue by Saviq** [canonical/checkbox#659]
### Bug Description

When your CLI and remote use incompatible API versions, Checkbox complains:

```
Remote API version mismatch. Service uses: 11. Remote uses: 12
```

But what is Service? What is Remote here?

### To Reproduce

Install checkbox22 2.9 on the host; and 2.8 on the… remote… DUT.

`checkbox-cli remote <IP>`

### Environment

N/A

### Relevant log output

```shell
Remote API version mismatch. Service uses: 11. Remote uses: 12
```

**Comment by Hook25** [comment]
We agree that the error message is unclear, we are working on making it clearer! thank you for your report. 

Remote is the checkbox program that you are using (the one you start with checkbox-cli remote ...), service is the one that is running on the device that you are testing. This error basically states, "I have detected that the two versions of checkbox that you are using are incompatible (Remote is newer than Service)"

Also note: we are changing the nomenclature of remote/service to something better soon, that should also make the error message more comprehensible overall
