### ISSUE TITLE
parts_meta_info_attachment job failed due to missing parts_meta_info 

### ISSUE THREAD

**Issue by baconYao** [canonical/checkbox#692]
### Problem

The job `com.canonical.certification::parts_meta_info_attachment` is failed because missing the `parts_meta_info`.

### Checkbox Snap

```
$ checkbox.checkbox-cli run com.canonical.certification::parts_meta_info_attachment               
$PROVIDERPATH is defined, so following provider sources are ignored ['/home/baconyao/.local/share/plainbox-providers-1', '/var/tmp/checkbox-providers-develop'] 
===========================[ Running Selected Jobs ]============================
==============[ Running job 1 / 1. Estimated time left: 0:00:00 ]===============
-----[ Attaches an information about all parts that constituted this snap ]-----
ID: com.canonical.certification::parts_meta_info_attachment
Category: com.canonical.plainbox::info
... 8< -------------------------------------------------------------------------
cat: /snap/checkbox/2779/parts_meta_info: No such file or directory
cat: /snap/checkbox22/current/parts_meta_info: No such file or directory
------------------------------------------------------------------------- >8 ---
Outcome: job failed
```

### Checkbox Deb
```
$ checkbox-cli run com.canonical.certification::parts_meta_info_attachment                       
===========================[ Running Selected Jobs ]============================
--------------[ Running job 1 / 1. Estimated time left: 0:00:00 ]---------------
-----[ Attaches an information about all parts that constituted this snap ]-----
ID: com.canonical.certification::parts_meta_info_attachment
Category: com.canonical.plainbox::info
... 8< -------------------------------------------------------------------------
cat: /parts_meta_info: No such file or directory
cat: /parts_meta_info: No such file or directory
------------------------------------------------------------------------- >8 ---
Outcome: job failed
Finalizing session that hasn't been submitted anywhere: checkbox-run-2023-08-30T06.11.22
==================================[ Results ]===================================
 ☒ : Attaches an information about all parts that constituted this snap
```

### To Reproduce

1. Install Checkbox Snap via commands
```
$ sudo snap install checkbox22 --beta
$ sudo snap install checkbox --channel="latest/beta" --classic
```

2. Run job via command `$ checkbox.checkbox-cli run com.canonical.certification::parts_meta_info_attachment `

### Environment

- OS: Jammy Desktop & Server
- Checkbox Type: [Snap, Deb]
- Checkbox22 Version:  2.9.1 (Rev 478)

**Comment by baconYao** [comment]
There's a commit d0b0db97d7fa095c0474d68c8535784a6a4b583d to remove `parts-meta-info` from snapcraft.yaml. 

- Is it the root cause?
- Does we have any action for Job `parts_meta_info_attachment`?
  - Update or retire?

**Comment by Hook25** [comment]
We have removed `parts-meta-info` as a step toward a unified version, that job should probably be retired as well. It is unclear to me when it broke for debs (I did not touch/do not recall touching it for debs) but I think we can take this occasion to retire it. How did you stumble upon this? Is this a part of your infra?

**Comment by baconYao** [comment]
- The `parts_meta_info_attachment` job is still included in lots of [test plans](https://github.com/search?q=repo%3Acanonical%2Fcheckbox%20parts_meta_info_attachment&type=code), therefore, it still be executed in lots of projects.
- For IOT project, the project Checkbox is generated by using [checkbox-configure](https://git.launchpad.net/~checkbox-dev/checkbox/+git/checkbox-configure/) tool, so the [parts-meta-info](https://git.launchpad.net/~checkbox-dev/checkbox/+git/checkbox-configure/tree/snap/snapcraft_classic.yaml.in_v2#n41) still exists in each project Checkbox which is generated by this tool.
  - For instance, [baoshan](https://git.launchpad.net/~baoshan-team/baoshan/+git/checkbox-baoshan-classic/tree/snap/snapcraft.yaml#n54)

So I want to make sure three things here

- Retire the `parts_meta_info_attachment` job from Checkbox ?
- Someone need to update the template of [checkbox-configure](https://git.launchpad.net/~checkbox-dev/checkbox/+git/checkbox-configure/) tool ?
- Update the snapcraft.yaml in Project Checkbox is needed ?

**Comment by baconYao** [comment]
Content of parts_meta_info_attachment

![Screenshot from 2023-09-01 12-01-50](https://github.com/canonical/checkbox/assets/8318678/32ea9186-507d-4dc4-98a6-7483e4be56a1)

**Comment by pieqq** [comment]
Now that Checkbox and its providers are all stored in a monorepo, and we release the whole thing as a whole and not as independent packages with independent versioning, the rationale for having `parts_meta_info` becomes less useful.

@kissiel since you have more history on this, can you decide whether or not we can drop this? In this case, we would need to do what @baconYao mentioned in a [previous comment](https://github.com/canonical/checkbox/issues/692#issuecomment-1700245099).

**Comment by patliuu** [comment]
Hi Cert team,

This attachment job failed on every IoT project. PMs and customers sometimes are curious about why it failed. I found that we are not able to exclude attachment jobs from the test plan, and our QA tool to edit submissions is not able to modify the attachment results/comments either. So it's a bit annoying for QA testing.

I think the action should be a quick one once Cert team has a decision on this. Could you help to take a look if possible?

**Comment by Hook25** [comment]
I have re-introduced the parts_meta_info file (that now just contains the snap version) for backward compatibility. Feel free to re-open this if it is not enough to fix this issue
