### ISSUE TITLE
fan_stress_reaction is marginal pass/fail

### ISSUE THREAD

**Issue by seankingyang** [canonical/checkbox#697]
### Bug Description

Not sure if this test case designed is only need to check the fan rpm will drop down after colling.
Actually we found some dut on this test case is marginal pass/fail.

Marginal PASS:
https://certification.canonical.com/hardware/202308-31965/submission/328555/test-results/pass/?term=fan

Marginal FAIL:
https://certification.canonical.com/hardware/202308-31965/submission/329067/test-results/fail/?term=fan

Also do some experiment on two different platforms [google sheet](https://docs.google.com/spreadsheets/d/1WBjx2kU5xbtNIs1K4-8tePpCHkYjObgUSY1jIjNqKH8/edit?usp=sharing).
There are two config's fan will not increase (obvious, most of time is keep almost the same range) fan speed.

I suggest to remove this test case from the cert plan, because:
1. This test case can't correctly identify  the true pass/fail on each machine.
2. The fan is controlled by EC/ME on PC.
3. The cooling mechanism on INTEL platform not using the increasing fan speed at the first priority.

If we need to test if the DUT haing the cooling mechanism, we should find another way~~

### To Reproduce

1. Boot in OS
5. checkbox-cli run com.canonical.certification::miscellanea/fan_stress_reaction

### Environment

1. Checkbox dev version 2.9.1
2. kernel: 6.5.0-9002-oem

**Comment by hanhsuan** [comment]
Other submissions

[Marginal PASS](https://certification.canonical.com/hardware/202307-31889/submission/328088/test/83456/result/35536077/)
[Marginal FAIL](https://certification.canonical.com/hardware/202307-31898/submission/328089/test/83456/result/35536214/)

**Comment by seankingyang** [comment]
Could we remove this test case from the cert plan, because:
1. This test case can't correctly identify the true pass/fail on each machine.
2. The fan is controlled by EC/ME on PC.
3. The cooling mechanism on INTEL platform not using the increasing fan speed at the first priority.

**Comment by diohe0311** [comment]
Based on the discussion in MM: https://chat.canonical.com/canonical/pl/frak6f8rp7yq3q8cgmfn4den7o
Sylvain agreed to remove it for now since it's not reliable.

Created a card: https://warthogs.atlassian.net/browse/CHECKBOX-940

**Comment by diohe0311** [comment]
Hi @seankingyang, I've created a PR for this: https://github.com/canonical/checkbox/pull/763
