### ISSUE TITLE
88f3b98cba re-added a job that we had previously deleted.

### ISSUE THREAD

**Issue by bladernr** [canonical/checkbox#698]
### Bug Description

commit 88f3b98cba was merged and somehow reverted merge https://github.com/canonical/checkbox/pull/319.  the apste_support job which is not applicable to servers was removed, and then re-added.

So now we need to delete that again.

### To Reproduce

git blame providers/base/units/disk/test-plan.pxu
look at the last line in the file:
287e3b6dab (Jeff Lane      2022-04-12 18:00:17 -0400 82)     disk/disk_cpu_load_.*                      certification-status=blocker
88f3b98cba (Weichen Wu     2023-03-09 10:41:21 +0800 83)     disk/apste_support_on_.*                   certification-status=non-blocker

### Environment

na

**Comment by Hook25** [comment]
Closing as fixed in #699
