### ISSUE TITLE
LP1858573: Need a job for screen auto-rotation in 2-in-1

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#71]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1858573

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Confirmed	| 2020-01-07 02:57:07	| 6	| High	| False  	|

## Description
In 2-in-1 section of certification coverage guide, it said

Convertible Laptops (aka 2-in-1s)
The system must support display rotation (0°, 90°, 180°, 270°)
The desktop environment must rotate automatically when sensors detect a rotation

We need a test case for auto-rotation. It should only apply to 2-in-1.
It could be a user-interact job.

## Attachments
No attachments

Tags:
[]

**Comment by kissiel** [comment]
I checked the coverage guide for 22.04 and the repo and this is indeed missing.

**Comment by kissiel** [comment]
So I guess it should be closed.
