### ISSUE TITLE
Incorrect buildstamp information in Somerville submissions 

### ISSUE THREAD

**Issue by cyruslien** [canonical/checkbox#754]
### Bug Description

The buildstamp information in submissions from Somerville platforms always shows "base image" information instead of OEM image information.

e.g.
https://certification.canonical.com/hardware/202304-31521/submission/321667/
info/buildstamp:
Ubuntu 22.04 LTS "Jammy Jellyfish" - somerville-jammy-amd64-20220504-33

It should be something like this:
canonical-oem-somerville-jammy-amd64-20220504-33+jellyfish-rattata+X94

### To Reproduce

checkbox-cli
run any job
check info/buildstamp in submission

### Environment

OS: Ubuntu 22.04 (somerville platform image)
Kernel: 6.1.0-1007
DUT: Any somerville platform
Checkbox type: Debian
Checkbox version: 2.6

**Comment by kissiel** [comment]
This was fixed in https://github.com/canonical/checkbox/pull/756
