### ISSUE TITLE
power-management/suspend-30-cycles-log-check-with-reboots  Test fails after 30 suspend cycles and single reboot.

### ISSUE THREAD

**Issue by cvelloth** [canonical/checkbox#766]
### Bug Description

The test is giving an error like below ::

High failures:
  s3: 1 failures
========================================
    Found 1 differences in device configuration during s2idle cycle. (x 1)

There is no detailed description about what exactly is the difference, so as to debug further.
Not able to pass this test with any type of hardware configuration.

### To Reproduce

1. Launch checkbox.checkbox-cli
2. Run job "power-management/suspend-30-cycles-log-check-with-reboots"

### Environment

-OS Ubuntu 22.04
-Checkbox version 2.8
- Hardware Intel RVP 
[submission_2023-10-17T15.19.27.869902.zip](https://github.com/canonical/checkbox/files/12930552/submission_2023-10-17T15.19.27.869902.zip)

### Relevant log output

```shell
- Logs are attached with this bug.
```

**Comment by pieqq** [comment]
I was able to locate the following information in `/test_output/com.canonical.certification__suspend_suspend_advanced_auto` from the submission archive:

```
DRM Device configurations differ, before:
  Name:       card0-eDP-1
  Status:     connected
  Enabled:    enabled

  Name:       card0-DP-4
  Status:     disconnected
  Enabled:    disabled

  Name:       card0-DP-2
  Status:     disconnected
  Enabled:    disabled

  Name:       card0
  Status:     
  Enabled:    

  Name:       card0-DP-5
  Status:     disconnected
  Enabled:    disabled

  Name:       card0-DP-3
  Status:     disconnected
  Enabled:    disabled

  Name:       card0-DP-1
  Status:     disconnected
  Enabled:    disabled

versus after:
  Name:       card0-eDP-1
  Status:     connected
  Enabled:    disabled

  Name:       card0-DP-4
  Status:     disconnected
  Enabled:    disabled

  Name:       card0-DP-2
  Status:     disconnected
  Enabled:    disabled

  Name:       card0
  Status:     
  Enabled:    

  Name:       card0-DP-5
  Status:     disconnected
  Enabled:    disabled

  Name:       card0-DP-3
  Status:     disconnected
  Enabled:    disabled

  Name:       card0-DP-1
  Status:     disconnected
  Enabled:    disabled


FAILED [HIGH] DevConfigDiffAfterSleep: Test 1, Found 1 differences in device
configuration during s2idle cycle.
```

The difference is that the first item goes from

```
 Name:       card0-eDP-1
  Status:     connected
  Enabled:    enabled
```

to 

```
 Name:       card0-eDP-1
  Status:     connected
  Enabled:    disabled
```

This is not a Checkbox issue. It could be either because the screen was turned off while the test was ongoing, or it can be an actual issue with what the GPU driver reports, or another type of firmware issue. You should report this to the hardware manufacturer, or the Canonical rep if this is a Certification project.

**Comment by cvelloth** [comment]
Still seeing the issue even without the eDP related error message. Opening new issue ticket to track the same.
