### ISSUE TITLE
LP1906216: need a way to switch back to default mode after graphics/1_auto_switch_card_* or graphics/2_auto_switch_card_*

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#78]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1906216

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2020-11-30 05:46:32	| 6	| High	| False  	|

## Description
We are counting on graphics/1_auto_switch_card_* switching to dGPU rendering and graphics/2_auto_switch_card_* to switch back to Intel gpu rendering [1].

But there's no way to switch back to default mode in the current design and we used to assume the default mode is powersaving(Intel rendering) mode so some existed plan[2]just switch back to powersaving(Intel gpu) mode in the end.

This operation cause problem on the following 2 exceptions:
1. Some platforms are asked to be shipped with default performance(Nvidia rendering) mode.
2. After Focal, some platform is asked to be shipped with default on-demand(runtime selecting rendering gpu[3]) mode.

In these 2 cases with current test plans, it will switch to intel in the end and it could impact the following tests.

We might need to redesign the graphic testing based on the current new dGPU using cases:

On Intel only(UMA):
 - default pwersaving(Intel rendering) mode.

On Intel + Nvidia:
 - default pwersaving(Intel rendering) mode by `prime-select intel`.
 - default performance(Nvidia rendering) mode by `prime-select nvidia`.
 - default pwersaving(runtime selecting rendering gpu [3]) mode by `prime-select on-demand`.

On Nvidia only:
 - default pwersaving(Intel rendering) mode by `prime-select nvidia`.
 - default pwersaving(runtime selecting rendering gpu [3]) mode by `prime-select on-demand`.

On Intel + AMD:
 - default pwersaving(runtime selecting rendering gpu by `DRI_PRIME=1`) mode.

On AMD only:
 - default pwersaving(runtime selecting rendering gpu by `DRI_PRIME=1`) mode.

[1] https://git.launchpad.net/plainbox-provider-checkbox/tree/units/graphics/test-plan.pxu
[2] https://git.launchpad.net/plainbox-provider-certification-client/tree/units/client-cert-auto.pxu
[3] https://docs.google.com/document/d/12zbZfGI_a4azR7a5UvVIib6gDyiK43ZFJOBlt0LPrEU/edit#

## Attachments
No attachments

Tags:
['oem-priority']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~stanley31 wrote on 2021-01-18 11:28:18:
@sylvain-pineau,

Just an idea that we could add a property to store default graphic mode in the "graphics_card_resource" job, and create a new job to switch to default mode.

So we could include the new job after testing. How do you think?

**Comment by yphus** [comment]
Reworking graphic cards test is now tracked [here](https://warthogs.atlassian.net/browse/CHECKBOX-643)
