### ISSUE TITLE
`pm_test.py` couldn't auto-restart on Mantic

### ISSUE THREAD

**Issue by hanhsuan** [canonical/checkbox#785]
### Bug Description

While using checkbox on Mantic, the `power-management/reboot` and `power-management/poweroff` couldn't auto restart. If the latest job is one of them, the session flag will be set to `submitted` and couldn't be resumed.

### To Reproduce

1. Install checkbox on Mantic
2. checkbox-cli run com.canonical.plainbox::power-management/reboot

### Environment

- Ubuntu 23.10
- Checkbox type: Debian & snap
- Checkbox version: 2.10.1

**Comment by zongminl** [comment]
Fixed by #904
