### ISSUE TITLE
power-management/suspend-30-cycles-log-check-with-reboots Test fails after 30 suspend cycles and single reboot.

### ISSUE THREAD

**Issue by cvelloth** [canonical/checkbox#790]
### Bug Description

High failures:
  s3: 1 failures
========================================
    Found 1 differences in device configuration during s2idle cycle. (x 1)

### To Reproduce

1. Launch checkbox.checkbox-cli
2. Run job "power-management/suspend-30-cycles-log-check-with-reboots"

### Environment

-OS Ubuntu 22.04
-Checkbox version 2.8
-Hardware Intel RVP

[submission_2023-10-25T04.11.49.203383.zip](https://github.com/canonical/checkbox/files/13161316/submission_2023-10-25T04.11.49.203383.zip)

### Relevant log output

```shell
- Logs are attached with this bug.
```

### Additional context

Continuation of https://github.com/canonical/checkbox/issues/766

**Comment by pieqq** [comment]
Can you attach the content of `/var/tmp/checkbox-ng/sessions/`? The log files are unfortunately absent from the submission.zip you sent.

**Comment by cvelloth** [comment]
[session_title-2023-10-25T03.36.06.session.zip](https://github.com/canonical/checkbox/files/13162187/session_title-2023-10-25T03.36.06.session.zip)
Attached

**Comment by pieqq** [comment]
Thanks!

In `session-share/pm_test.reboot.3.log` we can see the following logs, generated by [FWTS](https://wiki.ubuntu.com/FirmwareTestSuite) V23.05.00 (2023-05-23 04:00:48).:

```
s3: Sleep suspend/resume test.
--------------------------------------------------------------------------------
Test 1 of 1: Sleep suspend/resume test.
Defaulted to 1 test, use --s3-multiple=N to run more s2idle cycles 
s2idle cycle 1 of 1 
Detecting the power method.
Response to CanSuspend is yes 
User allowed to execute the CanSuspend action 
Using logind as the default power method.
Requesting Suspend action 
Skipping the minimum delay (0) and using a 3 seconds delay instead 
s2idle duration = 30.
pm-action returned 0 after 30 seconds.
DRM Device configurations differ, before:
  Name:       card0-eDP-1
  Status:     connected
  Enabled:    disabled

  Name:       card0-DP-4
  Status:     disconnected
  Enabled:    disabled

  Name:       card0-DP-2
  Status:     disconnected
  Enabled:    disabled

  Name:       card0
  Status:     
  Enabled:    

  Name:       card0-DP-5
  Status:     disconnected
  Enabled:    disabled

  Name:       card0-DP-3
  Status:     disconnected
  Enabled:    disabled

  Name:       card0-DP-1
  Status:     disconnected
  Enabled:    disabled

versus after:
  Name:       card0-eDP-1
  Status:     connected
  Enabled:    enabled

  Name:       card0-DP-4
  Status:     disconnected
  Enabled:    disabled

  Name:       card0-DP-2
  Status:     disconnected
  Enabled:    disabled

  Name:       card0
  Status:     
  Enabled:    

  Name:       card0-DP-5
  Status:     disconnected
  Enabled:    disabled

  Name:       card0-DP-3
  Status:     disconnected
  Enabled:    disabled

  Name:       card0-DP-1
  Status:     disconnected
  Enabled:    disabled


FAILED [HIGH] DevConfigDiffAfterSleep: Test 1, Found 1 differences in device
configuration during s2idle cycle.
```

So it seems to be the same issue: `card0-eDP-1` goes from `disabled` to `enabled` on the first iteration, but does not change afterwards.

**Comment by pieqq** [comment]
I asked a FWTS engineer about this, and he said:

> When doing S3 testings, will compare the devices status differences with s3-device-check-delay. It seems the card0-eDP-1 Enabled status just happen to change from disabled to enabled and was just caught within --s3-device-check-delay by the FWTS s3 tests. I don't think it is an issue, it could be set as won't fix.

I hope it answers your question.

**Comment by cvelloth** [comment]
Hi Pierre,

Quick follow-up question.
When it is said that issue is won't fix, are you saying that this can be considered a hardware problem and it cannot be fixed, because the code will always see it like that? Or do you mean that this particular test can be considered pass, as this issue cannot be fixed.  

If there is any workaround that we can use to remove eDP check and see if there are no other issues...we could rule it out as a hardware issue.

Thanks and Regards,
Chandana
