### ISSUE TITLE
`wireless_connection_wpa3_ax_np_.*` fail because of incorrect yaml config 

### ISSUE THREAD

**Issue by pieqq** [canonical/checkbox#811]
### Bug Description

Netplan had [a bug](https://bugs.launchpad.net/netplan/+bug/2023238) preventing it from supporting WPA3 connections. This was addressed with https://github.com/canonical/netplan/pull/369 and the fix landed in Jammy with netplan 0.106.1 being backported through SRU.

To get it to work, the yaml netplan config must include `key-management: sae` in the `auth` section (see [example](https://github.com/canonical/netplan/blob/main/examples/wireless_wpa3.yaml#L8)).

`providers/base/bin/wifi_client_test_netplan.py` needs to be modified to take this into account.

### To Reproduce

1. Launch Checkbox
2. Select a test plan that has the wireless jobs
3. Select `wireless_connection_wpa3_ax_np_.*` job(s)

Expected outcome: tests pass

Actual outcome: tests fail with output such as https://certification.canonical.com/hardware/202310-32205/submission/341216/test-results/fail/

### Environment

- OS: 22.04
- Checkbox v3.0.0

**Comment by baconYao** [comment]
I still run into this issue.

I can make sure the wpa3 connection through netplan is good.
  - [LP#2044200](https://bugs.launchpad.net/baoshan/+bug/2044200) [uc22] Fail to establish the 802.11ax wpa3 connection through Netplan

Baoshan:

- G1200: https://certification.canonical.com/hardware/202307-31859/submission/364836/test-results/?term=wpa3
- G700: https://certification.canonical.com/hardware/202308-31931/submission/365231/test-results/?term=wpa3
- G510: https://certification.canonical.com/hardware/202312-33205/submission/365161/test-results/?term=wpa3

**Comment by zongminl** [comment]
Fixed by #1237
