### ISSUE TITLE
LP1917701: KVM/LXD tests do not run on checkbox-snappy

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#82]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-resource/+bug/1917701

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Confirmed	| 2021-03-04 04:10:22	| 8	| High	| False  	|

## Description
KVM/LXD tests do not run on checkbox-snappy with Ubuntu Core 20

[steps]
$ Install Ubuntu Core 20
$ snap install checkbox-snappy --devmode --channel=20/stable
$ checkbox-snappy.checkbox-cli # make sure KVM and LXD are selected

[expected]
KVM/LXD tested and passed

[actual]
Tests do not run with

job cannot be started: resource expression "package.name == 'qemu-system'" evaluates to false
job cannot be started: resource expression "executable.name == 'lxc'" evaluates to false

https://kernel.ubuntu.com/~ikepanhc/uc20-checkbox/submission_2021-03-03T14.39.06.645877.html

[details]
$ snap list
Name             Version               Rev    Tracking       Publisher            Notes
checkbox-snappy  20.16                 2108   20/stable      ce-certification-qa  devmode
checkbox20       1.20                  428    latest/stable  ce-certification-qa  -
core20           20210216              958    latest/edge    canonical✓           base
pc               20-0.4                115    20/edge        canonical✓           gadget
pc-kernel        5.4.0-66.74.1         722    20/edge        canonical✓           kernel
snapd            2.49+git549.g07e33f2  11343  latest/edge    canonical✓           snapd

## Attachments
No attachments

Tags:
[]

**Comment by yphus** [comment]
The executable redsource job correctly reports the lxc command:
```

xargs -n1 -d: <<< "$PATH" | xargs -I{} find -H {} -maxdepth 1 -xtype f -executable -printf "name: %f\n\n" 2> /dev/null | sort -u | awk '{print}' ORS='\n\n' | grep lx
name: glxdemo
name: glxgears
name: glxheads
name: glxinfo
name: lxc
name: lxd
name: lxd.benchmark
name: lxd.buginfo
name: lxd.check-kernel
name: lxd.lxc
name: lxd.lxc-to-lxd
name: lxd.migrate

```
