### ISSUE TITLE
LP1929543: audio/1_playback_hdmi_* always fail: ERROR:Failed to find status for device: hdmi

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#84]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1929543

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2021-05-25 11:03:35	| 6	| High	| False  	|

## Description
[Summary]

[Steps to reproduce]
Run test com.canonical.certification::audio/1_playback_hdmi_PCI_ID_0x9a49

[Expected result]
Test pass

[Actual result]
Test always fail, but can hear sound from monitor and video & music can be played normally

INFO:===========================[ Saving audio settings ]============================
INFO:==========================[ HDMI / DisplayPort ports ]==========================
INFO:Card #0 Port: PortWithProfile(name='HDMI3', label='HDMI3/DP3 Output', priority=700, latency_offset=0, availability='not available', properties=[], profile_list=['HiFi'])
INFO:Card #0 Port: PortWithProfile(name='HDMI2', label='HDMI2/DP2 Output', priority=600, latency_offset=0, availability='not available', properties=[], profile_list=['HiFi'])
INFO:Card #0 Port: PortWithProfile(name='HDMI1', label='HDMI1/DP1 Output', priority=500, latency_offset=0, availability='available', properties=[Property(name='device.product.name', value='DELL P2415Q')], profile_list=['HiFi'])
Traceback (most recent call last):
  File "/tmp/nest-d9c8j5_5.a5412f3f1f04af24efab9aa1494248a48b23d88e8a751ef10c79d5e6985235d5/audio_settings.py", line 9, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/checkbox_support/scripts/audio_settings.py", line 383, in main
    set_profile_hdmi()
  File "/usr/lib/python3/dist-packages/checkbox_support/scripts/audio_settings.py", line 138, in set_profile_hdmi
    card, profile = _guess_hdmi_profile(pactl_list)
  File "/usr/lib/python3/dist-packages/checkbox_support/scripts/audio_settings.py", line 123, in _guess_hdmi_profile
    profile = min([p for p in port.profile_list if ('stereo' in p) or ('Hdmi' in p)], key=len)
ValueError: min() arg is an empty sequence
ERROR:Failed to find status for device: hdmi
Attempting to initialize Gstreamer pipeline: audiotestsrc wave=sine freq=512 ! audioconvert ! audioresample ! autoaudiosink
Pipeline initialized, now starting playback.
INFO:==========================[ Restoring audio settings ]==========================

[Additional information]
CID: 202012-28492
CPU: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8x)
GPU: 00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:9a49] (rev 01)
kernel-version: 5.10.0-1028-oem

[Stage]
Issue reported and logs collected right after it happened

## Attachments
[checkbox-session.tgz](https://api.launchpad.net/devel/bugs/1929543/+attachment/5500193/data)
[snap_list.log](https://api.launchpad.net/devel/bugs/1929543/+attachment/5500194/data)
[acpidump.log](https://api.launchpad.net/devel/bugs/1929543/+attachment/5500195/data)
[sosreport-u-Latitude-9420-2021-05-25-lplnbks.tar.gz](https://api.launchpad.net/devel/bugs/1929543/+attachment/5500196/data)

Tags:
['cbox-10', 'checkbox', 'test-case']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~huntu207 wrote on 2021-05-25 11:04:09:
Automatically attached

##### https://launchpad.net/~huntu207 wrote on 2021-05-25 11:04:11:
Automatically attached

##### https://launchpad.net/~huntu207 wrote on 2021-05-25 11:04:19:
Automatically attached

##### https://launchpad.net/~huntu207 wrote on 2021-05-25 11:04:30:
Automatically attached

**Comment by yphus** [comment]
Please reopen the issue if the problem occurs on another device
