### ISSUE TITLE
[Checkbox Control] Unable resume from suspend since operation not permitted problem causes RTC cannot be configured properly

### ISSUE THREAD

**Issue by baconYao** [canonical/checkbox#857]
### Problem
When testing via `Checkbox Control` with specific jobs combination, there's high possibility that DUT cannot resume from suspend, then tester can only observer that Host is reconnecting at suspend_advanced_auto job (like screenshot below)
![Screenshot from 2023-12-01 10-55-16](https://github.com/canonical/checkbox/assets/8318678/450805e7-e594-43cf-a2a9-4dd7a7552b7c)

In the beginning, I believed this was a real issue where the Device Under Test (DUT) couldn't enter suspend or hang in suspend. Therefore, I monitored the journal log through SSH or the serial console. However, in this situation, I couldn't reproduce the problem.

Therefore, I eliminated all connections (SSH or serial console) and conducted the test using checkbox locally. I still couldn't reproduce the issue.

Only by using Checkbox Control and without any connections (SSH or serial console), I can consistently reproduce this issue.

Finally, I attempted to manually press the power button when the issue occurred. The result was that the Device Under Test (DUT) could resume normally, and some messages were displayed in the suspend_advanced_auto job (like screenshot below).
![Screenshot from 2023-12-01 10-57-17](https://github.com/canonical/checkbox/assets/8318678/a40fde70-358c-4db2-b8cb-7a35481e99ad)
From the above image, it can be seen that `rtcwake: /dev/rtc0: unable to find device: Operation not permitted` is exposed.
Therefore, I reasonably suspect that during the test execution with Checkbox Control, there might be a chance of encountering `Operation not permitted`, leading to the inability to correctly set the time for rtc.

### Failure Rate

- `Checkbox Control` with `suspend_advanced_auto` job: 0/5
- `Checkbox Control` with `bluetooth/detect-output` + `suspend_advanced_auto` job: 7/10
- `sudo Checkbox Local` with `bluetooth/detect-output` + `suspend_advanced_auto` : 0/5

### Another similar issue of `operation not permitted`

- `rfkill: cannot open /dev/rfkill: Operation not permitted `
  - submission: https://certification.canonical.com/hardware/202308-31931/submission/346071/test/9/result/38010572/
    - `rtcwake: /dev/rtc0: unable to find device: Operation not permitted` can also be observed in same session
      - https://certification.canonical.com/hardware/202308-31931/submission/346071/test/892/result/38010575/

Notice: when `rtcwake: /dev/rtc0: unable to find device: Operation not permitted` occurs, `rfkill: cannot open /dev/rfkill: Operation not permitted ` might not occur, please see the following submission
  - https://certification.canonical.com/hardware/202308-31931/submission/346263/test-results/

### To Reproduce

1. Install checkbox22 via command `$ sudo snap install checkbox22 --beta`
2. Install checkbox via command `$ sudo snap install checkbox --channel="uc22/beta" --devmode`
3. Install bluez via command `$ sudo snap install bluez`
4. Connect checkbox and bluez via command `$sudo snap connect checkbox:bluez bluez:service`
5. Reboot DUT and make sure there's no connection such as SSH, serial console to it.
6. Start testing via Checkbox Control on Host `$ checkbox.checkbox-cli control <IP address of DUT>`
7. Choose `IoT Client Certification for 22.04 classic images (Automated Tests)` test plan
8. Choose `bluetooth/detect-output` and `suspend/suspend_advanced_auto` jobs
9. Execute testing

### Environment

- OS: UC22
- Checkbox Type: Snap
- Checkbox Version: 3.2.0
- Run method: Checkbox Control
- Hardware being tested:
  - CID: 202308-31931  (Genio 700)
  - CID: 202307-31859  (Genio 1200)
  - CID: 202307-31864  (Genio 1200)

### Relevant log output

```shell
1. The hci0 interface is down by default. I didn't bring it up before testing

ceqa@ubuntu:~$ hciconfig 
hci0:	Type: Primary  Bus: USB
	BD Address: E8:FB:1C:BD:31:FE  ACL MTU: 1021:6  SCO MTU: 240:8
	DOWN 
	RX bytes:15253 acl:0 sco:0 events:2120 errors:0
	TX bytes:534707 acl:0 sco:0 commands:2120 errors:0
```

2.
```


### Additional context

_No response_

**Comment by kissiel** [comment]
After multiple tries to reproduce that on various systems I noticed that the steps to reproduce written by the OP mention running a classic TP on a Core installation. That is not supported and can yield to multiple problems like that. So please don't run TPs meant for the Classic images on UC.

**Comment by baconYao** [comment]
> After multiple tries to reproduce that on various systems I noticed that the steps to reproduce written by the OP mention running a classic TP on a Core installation. That is not supported and can yield to multiple problems like that. So please don't run TPs meant for the Classic images on UC.

Hi @kissiel, I don't quite understand the meaning of those abbreviations such as `OP` and `TP`, could you please explain here?

**Comment by kissiel** [comment]
Sorry for that.
OP = Original Poster -> you, the author of the issue.
TP = Test Plan.

**Comment by baconYao** [comment]
Hi @kissiel, I don't think it's about the problem of Classic or Core Test Plan was running on Core Image. Because [client-cert-iot-ubuntucore-22-automated](https://github.com/canonical/checkbox/blob/main/providers/certification-client/units/client-cert-iot-server-22-04.pxu#L34) TP is the nested part of [client-cert-iot-server-22-04-automated](https://github.com/canonical/checkbox/blob/main/providers/certification-client/units/client-cert-iot-server-22-04.pxu#L26C5-L26C43) TP. Therefore, execute the Server TP is equal to Core TP for automated test.

This issue was found by running the [genio-baoshan-core-22-automated](https://git.launchpad.net/~baoshan-team/baoshan/+git/checkbox-provider-baoshan/tree/units/genio-baoshan-core-22-test-plan.pxu#n52) and it included the [com.canonical.certification::client-cert-iot-ubuntucore-22-automated](https://git.launchpad.net/~baoshan-team/baoshan/+git/checkbox-provider-baoshan/tree/units/genio-baoshan-core-22-test-plan.pxu#n73) TP as nested part.

**Comment by baconYao** [comment]
I retried this issue under same UC22 image with following conclusion:

Test Plan: IoT Client Certification for Ubuntu Core 22 (Automated Tests) 
  - id: com.canonical.certification::client-cert-iot-ubuntucore-22-automated

- CID: 202308-31931 (Genio 700)
  - Failure Rate: 50% (1/2)
  - Failed submission:
    - https://certification.canonical.com/hardware/202308-31931/submission/354259/test/892/result/39044644/
- CID: 202307-31864 (Genio 1200)
  - Failure Rate: 0% (0/4)

```bash
ceqa@ubuntu:~$ snap list
Name                   Version         Rev    Tracking       Publisher            Notes
bluez                  5.64-4          357    22/stable      canonical✓           -
checkbox               3.3.0-dev19     5228   uc22/beta      ce-certification-qa  devmode
checkbox22             3.3.0-dev19     727    latest/beta    ce-certification-qa  -
core22                 20230801        867    latest/stable  canonical✓           base
mediatek-genio         22-0.4.1        5      22/beta        canonical✓           gadget
mediatek-genio-kernel  5.15.0-1029.33  4      22/beta        canonical✓           kernel,devmode
snapd                  2.61.1          20674  latest/stable  canonical✓           snapd
```

**Comment by rmartin013** [comment]
Interesting… I have hit the exact same issue on Riverside (arm64 device), with a classic server image. It was happening quite regularly over the past 2 weeks, but seems now it seems stable again… I prepared a patch for this suspend_advanced_auto tests which could hopefully help (at least to debug the issue).

**Comment by baconYao** [comment]
Thanks @rmartin013, I think @kissiel  has similar thoughts as you.
@kissiel Could you please help review #979 ?

**Comment by baconYao** [comment]
Unable to reproduce this issue by using the following version of Checkbox (Including the patch from #979 )
```bash
ceqa@ubuntu:~$ snap list
Name                   Version         Rev    Tracking       Publisher            Notes
checkbox               4.0.0-dev126    6026   uc22/edge      ce-certification-qa  devmode
checkbox22             4.0.0-dev126    825    latest/edge    ce-certification-qa  devmode
core22                 20230801        867    latest/stable  canonical✓           base
mediatek-genio         22-0.4.1        5      22/beta        canonical✓           gadget
mediatek-genio-kernel  5.15.0-1029.33  4      22/beta        canonical✓           kernel,devmode
snapd                  2.61.1          20674  latest/stable  canonical✓           snapd
```

OS: UC22
Checkbox Type: Snap
Checkbox Version: 4.0.0-dev126
Run method: Checkbox Control
Hardware being tested:

- CID: 202308-31931 (Genio 700)

Failure Rate: 0/4 (0%)
Submissions:

- https://certification.canonical.com/hardware/202308-31931/submission/358652/test-results/pass/
- https://certification.canonical.com/hardware/202308-31931/submission/358653/test-results/pass/
- https://certification.canonical.com/hardware/202308-31931/submission/358654/test-results/pass/
- https://certification.canonical.com/hardware/202308-31931/submission/358657/test-results/pass/
-
