### ISSUE TITLE
LP1953118: graphics/*_gl_support_* fail: because binary unity_support_test is missing

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#88]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1953118

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2021-12-03 06:57:33	| 6	| High	| False  	|

## Description
Checkbox snaps:
Name               Version             Rev    Tracking         Publisher            Notes
cdts               0.9.dev             232    latest/edge/…    ce-certification-qa  classic
checkbox20         1.24                717    latest/stable    ce-certification-qa  -

graphics/1_gl_support_PCI_ID_0x4571 	fails with error:

    bash: /usr/lib/nux/unity_support_test: No such file or directory 

See:

https://certification.canonical.com/hardware/202109-29496/submission/238308/test-results/fail/?term=gl_support

This is due to commit 184487acc3442d45afd0d619fa7d30faf681d171 in plainbox-provider-checkbox:

https://git.launchpad.net/plainbox-provider-checkbox/commit/?id=184487acc3442d45afd0d619fa7d30faf681d171

## Attachments
No attachments

Tags:
['cbox-15']

**Comment by djacobs98** [comment]
The manual workaround is install nux-tools yourself then rerun checkbox:

$ sudo apt update
$ sudo apt install nux-tools

**Comment by yphus** [comment]
nux-tools was added to the checkbox core snaps: https://github.com/canonical/checkbox/blob/main/checkbox-core-snap/series22/snap/snapcraft.yaml#L286
