### ISSUE TITLE
LP1954375: the summary() in bin/pm_test.py missing some test cases condition when QA runs a bigger test plan

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#89]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1954375

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Confirmed	| 2021-12-10 06:14:27	| 8	| High	| False  	|

## Description
When a checkbox session contains many pm_test calls[1], then it will append the "Completed S3 cycle(s) \n" and "Completed s2idle cycle(s) \n" to the same path (e.g. --log=/var/tmp/checkbox-ng/sessions/session_title-2021-12-06T10.25.57.session/session-share/fwts).

When the second (or later) pm_test be called, it will count previous fwts logs.

```
                with open(fwts_log_path, 'rt') as f:
                    magic_line_s3 = 'Completed S3 cycle(s) \n'
                    magic_line_s2idle = 'Completed s2idle cycle(s) \n'
                    lines = f.readlines()
                    count_s3 = lines.count(magic_line_s3)
                    count_s2idle = lines.count(magic_line_s2idle)
                    count = count_s3 + count_s2idle
                    if count != total_suspends_expected:
                        problems = (
                            "Found {} occurrences of S3/S2idle."
                            " Expected {}".format(
                                count, total_suspends_expected))
```

In the case that Stella met, it shows:
```
[Actual result]
Stress_suspend_30_cycles_with_reboots test failed
Log:Found 126 occurrences of S3/S2idle. Expected 90
```

The potential solution is to create fwts-cmd.log per test case or check the timestamp[2] whether inside the range.

Feel free to find the detail logs on https://bugs.launchpad.net/stella/+bug/1953597.

[1] https://bugs.launchpad.net/stella/+bug/1953597
[2] "This test run on 06/12/21 at 22:21:08 on host Linux u 5.14.0-1007-oem #7-Ubuntu"

## Attachments
No attachments

Tags:
['cbox-16', 'oem-priority', 'originate-from-1953597', 'stella']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~os369510 wrote on 2021-12-10 06:23:11:
Copied the comment from private bug:

```
There is no log, the log been cut.
```
1:================================= Iteration 1 ==================================
9:This test run on 06/12/21 at 05:36:14 on host Linux u 5.14.0-1007-oem #7-Ubuntu
35:Completed S3 cycle(s)
72:================================= Iteration 2 ==================================
80:This test run on 06/12/21 at 05:37:08 on host Linux u 5.14.0-1007-oem #7-Ubuntu
106:Completed S3 cycle(s)
143:================================= Iteration 3 ==================================
151:This test run on 06/12/21 at 05:38:02 on host Linux u 5.14.0-1007-oem #7-Ubuntu
177:Completed S3 cycle(s)
214:================================= Iteration 4 ==================================
222:This test run on 06/12/21 at 05:38:56 on host Linux u 5.14.0-1007-oem #7-Ubuntu
...
```
Dec 06 06:22:13 u pm_test.py.desktop[1529]: [Desktop Entry]
Dec 06 06:22:13 u pm_test.py.desktop[1529]: Name=reboot test
Dec 06 06:22:13 u pm_test.py.desktop[1529]: Comment=Verify reboot works properly
Dec 06 06:22:13 u pm_test.py.desktop[1529]: Exec=sudo /usr/bin/python3 /usr/lib/plainbox-provider-checkbox/bin/pm_test.py -r 0 -w 0 --hardware-delay 30 --pm-delay 5 --min-pm-time 0 --max-pm-time 300 --append --to
Dec 06 06:22:13 u pm_test.py.desktop[1529]: Type=Application
Dec 06 06:22:13 u pm_test.py.desktop[1529]: X-GNOME-Autostart-enabled=true
Dec 06 06:22:13 u pm_test.py.desktop[1529]: Hidden=false
Dec 06 06:22:13 u pm_test.py.desktop[1529]: INFO reboot operations remaining: 1
Dec 06 06:22:13 u pm_test.py.desktop[1529]: INFO Reboot time: 0:27:46.401842
Dec 06 06:22:13 u pm_test.py.desktop[1529]: INFO Running suspend/resume cycles
Dec 06 06:22:13 u pm_test.py.desktop[1529]: DEBUG Executing: 'checkbox-support-fwts_test --log=/var/tmp/checkbox-ng/sessions/session_title-2021-12-06T10.25.57.session/session-share/fwts -s s3 --s3-device-check
```
241:================================= Iteration 1 ==================================
249:This test run on 06/12/21 at 05:54:27 on host Linux u 5.14.0-1007-oem #7-Ubuntu
277:Completed S3 cycle(s)
315:================================= Iteration 2 ==================================
323:This test run on 06/12/21 at 05:55:03 on host Linux u 5.14.0-1007-oem #7-Ubuntu
349:Completed S3 cycle(s)
386:================================= Iteration 3 ==================================
394:This test run on 06/12/21 at 05:55:57 on host Linux u 5.14.0-1007-oem #7-Ubuntu
420:Completed S3 cycle(s)
457:================================= Iteration 4 ==================================
465:This test run on 06/12/21 at 05:56:51 on host Linux u 5.14.0-1007-oem #7-Ubuntu
491:Completed S3 cycle(s)
528:================================= Iteration 5 ==================================
536:This test run on 06/12/21 at 05:57:45 on host Linux u 5.14.0-1007-oem #7-Ubuntu
562:Completed S3 cycle(s)
599:================================= Iteration 6 ==================================
607:This test run on 06/12/21 at 05:58:39 on host Linux u 5.14.0-1007-oem #7-Ubuntu
633:Completed S3 cycle(s)
670:================================= Iteration 7 ==================================
678:This test run on 06/12/21 at 05:59:33 on host Linux u 5.14.0-1007-oem #7-Ubuntu
704:Completed S3 cycle(s)
741:================================= Iteration 8 ==================================
749:This test run on 06/12/21 at 06:00:27 on host Linux u 5.14.0-1007-oem #7-Ubuntu
775:Completed S3 cycle(s)
812:================================= Iteration 9 ==================================
820:This test run on 06/12/21 at 06:01:21 on host Linux u 5.14.0-1007-oem #7-Ubuntu
846:Completed S3 cycle(s)
883:================================= Iteration 10 =================================
891:This test run on 06/12/21 at 06:02:15 on host Linux u 5.14.0-1007-oem #7-Ubuntu
917:Completed S3 cycle(s)
954:================================= Iteration 11 =================================
962:This test run on 06/12/21 at 06:03:09 on host Linux u 5.14.0-1007-oem #7-Ubuntu
988:Completed S3 cycle(s)
1025:================================= Iteration 12 =================================
1033:This test run on 06/12/21 at 06:04:03 on host Linux u 5.14.0-1007-oem #7-Ubuntu
1059:Completed S3 cycle(s)
1096:================================= Iteration 13 =================================
1104:This test run on 06/12/21 at 06:04:57 on host Linux u 5.14.0-1007-oem #7-Ubuntu
1130:Completed S3 cycle(s)
1167:================================= Iteration 14 =================================
1175:This test run on 06/12/21 at 06:05:51 on host Linux u 5.14.0-1007-oem #7-Ubuntu
1201:Completed S3 cycle(s)
1238:================================= Iteration 15 =================================
1246:This test run on 06/12/21 at 06:06:45 on host Linux u 5.14.0-1007-oem #7-Ubuntu
1272:Completed S3 cycle(s)
1309:================================= Iteration 16 =================================
1317:This test run on 06/12/21 at 06:07:39 on host Linux u 5.14.0-1007-oem #7-Ubuntu
1343:Completed S3 cycle(s)
1380:================================= Iteration 17 =================================
1388:This test run on 06/12/21 at 06:08:33 on host Linux u 5.14.0-1007-oem #7-Ubuntu
1414:Completed S3 cycle(s)
1451:================================= Iteration 18 =================================
1459:This test run on 06/12/21 at 06:09:27 on host Linux u 5.14.0-1007-oem #7-Ubuntu
1485:Completed S3 cycle(s)
1522:================================= Iteration 19 =================================
1530:This test run on 06/12/21 at 06:10:21 on host Linux u 5.14.0-1007-oem #7-Ubuntu
1556:Completed S3 cycle(s)
1593:================================= Iteration 20 =================================
1601:This test run on 06/12/21 at 06:11:15 on host Linux u 5.14.0-1007-oem #7-Ubuntu
1627:Completed S3 cycle(s)
1664:================================= Iteration 21 =================================
1672:This test run on 06/12/21 at 06:12:09 on host Linux u 5.14.0-1007-oem #7-Ubuntu
1698:Completed S3 cycle(s)
1735:================================= Iteration 22 =================================
1743:This test run on 06/12/21 at 06:13:03 on host Linux u 5.14.0-1007-oem #7-Ubuntu
1769:Completed S3 cycle(s)
1806:================================= Iteration 23 =================================
1814:This test run on 06/12/21 at 06:13:57 on host Linux u 5.14.0-1007-oem #7-Ubuntu
1840:Completed S3 cycle(s)
1877:================================= Iteration 24 =================================
1885:This test run on 06/12/21 at 06:14:51 on host Linux u 5.14.0-1007-oem #7-Ubuntu
1911:Completed S3 cycle(s)
1948:================================= Iteration 25 =================================
1956:This test run on 06/12/21 at 06:15:44 on host Linux u 5.14.0-1007-oem #7-Ubuntu
1982:Completed S3 cycle(s)
2019:================================= Iteration 26 =================================
2027:This test run on 06/12/21 at 06:16:38 on host Linux u 5.14.0-1007-oem #7-Ubuntu
2053:Completed S3 cycle(s)
2090:================================= Iteration 27 =================================
2098:This test run on 06/12/21 at 06:17:32 on host Linux u 5.14.0-1007-oem #7-Ubuntu
2124:Completed S3 cycle(s)
2161:================================= Iteration 28 =================================
2169:This test run on 06/12/21 at 06:18:26 on host Linux u 5.14.0-1007-oem #7-Ubuntu
2195:Completed S3 cycle(s)
2232:================================= Iteration 29 =================================
2240:This test run on 06/12/21 at 06:19:20 on host Linux u 5.14.0-1007-oem #7-Ubuntu
2266:Completed S3 cycle(s)
2303:================================= Iteration 30 =================================
2311:This test run on 06/12/21 at 06:20:14 on host Linux u 5.14.0-1007-oem #7-Ubuntu
2337:Completed S3 cycle(s)
2374:================================= Iteration 1 ==================================
2382:This test run on 06/12/21 at 06:22:13 on host Linux u 5.14.0-1007-oem #7-Ubuntu
2408:Completed S3 cycle(s)
2445:================================= Iteration 2 ==================================
2453:This test run on 06/12/21 at 06:23:07 on host Linux u 5.14.0-1007-oem #7-Ubuntu
2479:Completed S3 cycle(s)
2516:================================= Iteration 3 ==================================
2524:This test run on 06/12/21 at 06:24:01 on host Linux u 5.14.0-1007-oem #7-Ubuntu
2562:Completed S3 cycle(s)
2600:================================= Iteration 4 ==================================
2608:This test run on 06/12/21 at 06:24:55 on host Linux u 5.14.0-1007-oem #7-Ubuntu
2634:Completed S3 cycle(s)
2671:================================= Iteration 5 ==================================
2679:This test run on 06/12/21 at 06:25:49 on host Linux u 5.14.0-1007-oem #7-Ubuntu
2705:Completed S3 cycle(s)
2742:================================= Iteration 6 ==================================
2750:This test run on 06/12/21 at 06:26:43 on host Linux u 5.14.0-1007-oem #7-Ubuntu
2776:Completed S3 cycle(s)
2813:================================= Iteration 7 ==================================
2821:This test run on 06/12/21 at 06:27:37 on host Linux u 5.14.0-1007-oem #7-Ubuntu
2847:Completed S3 cycle(s)
2884:================================= Iteration 8 ==================================
2892:This test run on 06/12/21 at 06:28:31 on host Linux u 5.14.0-1007-oem #7-Ubuntu
2918:Completed S3 cycle(s)
2955:================================= Iteration 9 ==================================
2963:This test run on 06/12/21 at 06:29:25 on host Linux u 5.14.0-1007-oem #7-Ubuntu
2989:Completed S3 cycle(s)
3026:================================= Iteration 10 =================================
3034:This test run on 06/12/21 at 06:30:19 on host Linux u 5.14.0-1007-oem #7-Ubuntu
3060:Completed S3 cycle(s)
3097:================================= Iteration 11 =================================
3105:This test run on 06/12/21 at 06:31:13 on host Linux u 5.14.0-1007-oem #7-Ubuntu
3131:Completed S3 cycle(s)
3168:================================= Iteration 12 =================================
3176:This test run on 06/12/21 at 06:32:07 on host Linux u 5.14.0-1007-oem #7-Ubuntu
3202:Completed S3 cycle(s)
3239:================================= Iteration 13 =================================
3247:This test run on 06/12/21 at 06:33:01 on host Linux u 5.14.0-1007-oem #7-Ubuntu
3273:Completed S3 cycle(s)
3310:================================= Iteration 14 =================================
3318:This test run on 06/12/21 at 06:33:55 on host Linux u 5.14.0-1007-oem #7-Ubuntu
3344:Completed S3 cycle(s)
3381:================================= Iteration 15 =================================
3389:This test run on 06/12/21 at 06:34:49 on host Linux u 5.14.0-1007-oem #7-Ubuntu
3415:Completed S3 cycle(s)
3452:================================= Iteration 16 =================================
3460:This test run on 06/12/21 at 06:35:43 on host Linux u 5.14.0-1007-oem #7-Ubuntu
3486:Completed S3 cycle(s)
3523:================================= Iteration 17 =================================
3531:This test run on 06/12/21 at 06:36:37 on host Linux u 5.14.0-1007-oem #7-Ubuntu
3557:Completed S3 cycle(s)
3594:================================= Iteration 18 =================================
3602:This test run on 06/12/21 at 06:37:31 on host Linux u 5.14.0-1007-oem #7-Ubuntu
3628:Completed S3 cycle(s)
3665:================================= Iteration 19 =================================
3673:This test run on 06/12/21 at 06:38:25 on host Linux u 5.14.0-1007-oem #7-Ubuntu
3699:Completed S3 cycle(s)
3736:================================= Iteration 20 =================================
3744:This test run on 06/12/21 at 06:39:19 on host Linux u 5.14.0-1007-oem #7-Ubuntu
3770:Completed S3 cycle(s)
3807:================================= Iteration 21 =================================
3815:This test run on 06/12/21 at 06:40:13 on host Linux u 5.14.0-1007-oem #7-Ubuntu
3841:Completed S3 cycle(s)
3878:================================= Iteration 22 =================================
3886:This test run on 06/12/21 at 06:41:07 on host Linux u 5.14.0-1007-oem #7-Ubuntu
3912:Completed S3 cycle(s)
3949:================================= Iteration 23 =================================
3957:This test run on 06/12/21 at 06:42:01 on host Linux u 5.14.0-1007-oem #7-Ubuntu
3983:Completed S3 cycle(s)
4020:================================= Iteration 24 =================================
4028:This test run on 06/12/21 at 06:42:55 on host Linux u 5.14.0-1007-oem #7-Ubuntu
4054:Completed S3 cycle(s)
4091:================================= Iteration 25 =================================
4099:This test run on 06/12/21 at 06:43:49 on host Linux u 5.14.0-1007-oem #7-Ubuntu
4125:Completed S3 cycle(s)
4162:================================= Iteration 26 =================================
4170:This test run on 06/12/21 at 06:44:43 on host Linux u 5.14.0-1007-oem #7-Ubuntu
4196:Completed S3 cycle(s)
4233:================================= Iteration 27 =================================
4241:This test run on 06/12/21 at 06:45:37 on host Linux u 5.14.0-1007-oem #7-Ubuntu
4267:Completed S3 cycle(s)
4304:================================= Iteration 28 =================================
4312:This test run on 06/12/21 at 06:46:31 on host Linux u 5.14.0-1007-oem #7-Ubuntu
4338:Completed S3 cycle(s)
4375:================================= Iteration 29 =================================
4383:This test run on 06/12/21 at 06:47:25 on host Linux u 5.14.0-1007-oem #7-Ubuntu
4409:Completed S3 cycle(s)
4446:================================= Iteration 30 =================================
4454:This test run on 06/12/21 at 06:48:19 on host Linux u 5.14.0-1007-oem #7-Ubuntu
4480:Completed S3 cycle(s)
...
```
Dec 06 21:25:15 u sudo[2820]: u : TTY=unknown ; PWD=/tmp/cwd-6by4jwg4.ea1d9899be9e0a0665aa16dbf6dca87ec0fe994ca4b8a5490ac412b9ecf7e97e ; USER=root ; COMMAND=/usr/bin/env BTDEVADDR=5C:3A:45:BA:14:74 OPEN_AC
Dec 06 21:25:15 u sudo[2820]: u : (command continued) WPA_AC_PSK=insecure WPA_AC_SSID=ubuntudemo_ac WPA_AX_PSK=insecure WPA_AX_SSID=ubuntudemo_ax WPA_BG_PSK=insecure WPA_BG_SSID=ubuntudemo WPA_N_PSK=insecu
                              pm_test.py reboot --checkbox-respawn-cmd "$PLAINBOX_SESSION_SHARE"/__respawn_checkbox --fwts --log-level=debug --log-dir="$PLAINBOX_SESSION_SHARE" --suspends-before-reboot=30 -r 3 --
Dec 06 21:25:15 u sudo[2820]: pam_unix(sudo:session): session opened for user root by (uid=0)
```
4517:================================= Iteration 1 ==================================
4525:This test run on 06/12/21 at 21:25:15 on host Linux u 5.14.0-1007-oem #7-Ubuntu
4551:Completed S3 cycle(s)
4588:================================= Iteration 2 ==================================
4596:This test run on 06/12/21 at 21:26:10 on host Linux u 5.14.0-1007-oem #7-Ubuntu
4622:Completed S3 cycle(s)
4659:================================= Iteration 3 ==================================
4667:This test run on 06/12/21 at 21:27:04 on host Linux u 5.14.0-1007-oem #7-Ubuntu
4693:Completed S3 cycle(s)
4730:================================= Iteration 4 ==================================
4738:This test run on 06/12/21 at 21:27:58 on host Linux u 5.14.0-1007-oem #7-Ubuntu
4764:Completed S3 cycle(s)
4801:================================= Iteration 5 ==================================
4809:This test run on 06/12/21 at 21:28:52 on host Linux u 5.14.0-1007-oem #7-Ubuntu
4835:Completed S3 cycle(s)
4872:================================= Iteration 6 ==================================
4880:This test run on 06/12/21 at 21:29:46 on host Linux u 5.14.0-1007-oem #7-Ubuntu
4906:Completed S3 cycle(s)
4943:================================= Iteration 7 ==================================
4951:This test run on 06/12/21 at 21:30:40 on host Linux u 5.14.0-1007-oem #7-Ubuntu
4977:Completed S3 cycle(s)
5014:================================= Iteration 8 ==================================
5022:This test run on 06/12/21 at 21:31:34 on host Linux u 5.14.0-1007-oem #7-Ubuntu
5048:Completed S3 cycle(s)
5085:================================= Iteration 9 ==================================
5093:This test run on 06/12/21 at 21:32:28 on host Linux u 5.14.0-1007-oem #7-Ubuntu
5119:Completed S3 cycle(s)
5156:================================= Iteration 10 =================================
5164:This test run on 06/12/21 at 21:33:22 on host Linux u 5.14.0-1007-oem #7-Ubuntu
5259:Completed S3 cycle(s)
5297:================================= Iteration 11 =================================
5305:This test run on 06/12/21 at 21:34:16 on host Linux u 5.14.0-1007-oem #7-Ubuntu
5716:Completed S3 cycle(s)
5754:================================= Iteration 12 =================================
5762:This test run on 06/12/21 at 21:35:13 on host Linux u 5.14.0-1007-oem #7-Ubuntu
5857:Completed S3 cycle(s)
5895:================================= Iteration 13 =================================
5903:This test run on 06/12/21 at 21:36:07 on host Linux u 5.14.0-1007-oem #7-Ubuntu
5929:Completed S3 cycle(s)
5966:================================= Iteration 14 =================================
5974:This test run on 06/12/21 at 21:37:01 on host Linux u 5.14.0-1007-oem #7-Ubuntu
6000:Completed S3 cycle(s)
6037:================================= Iteration 15 =================================
6045:This test run on 06/12/21 at 21:37:55 on host Linux u 5.14.0-1007-oem #7-Ubuntu
6071:Completed S3 cycle(s)
6108:================================= Iteration 16 =================================
6116:This test run on 06/12/21 at 21:38:49 on host Linux u 5.14.0-1007-oem #7-Ubuntu
6142:Completed S3 cycle(s)
6179:================================= Iteration 17 =================================
6187:This test run on 06/12/21 at 21:39:43 on host Linux u 5.14.0-1007-oem #7-Ubuntu
6213:Completed S3 cycle(s)
6250:================================= Iteration 18 =================================
6258:This test run on 06/12/21 at 21:40:37 on host Linux u 5.14.0-1007-oem #7-Ubuntu
6284:Completed S3 cycle(s)
6321:================================= Iteration 19 =================================
6329:This test run on 06/12/21 at 21:41:31 on host Linux u 5.14.0-1007-oem #7-Ubuntu
6355:Completed S3 cycle(s)
6392:================================= Iteration 20 =================================
6400:This test run on 06/12/21 at 21:42:25 on host Linux u 5.14.0-1007-oem #7-Ubuntu
6426:Completed S3 cycle(s)
6463:================================= Iteration 21 =================================
6471:This test run on 06/12/21 at 21:43:19 on host Linux u 5.14.0-1007-oem #7-Ubuntu
6497:Completed S3 cycle(s)
6534:================================= Iteration 22 =================================
6542:This test run on 06/12/21 at 21:44:13 on host Linux u 5.14.0-1007-oem #7-Ubuntu
6568:Completed S3 cycle(s)
6605:================================= Iteration 23 =================================
6613:This test run on 06/12/21 at 21:45:07 on host Linux u 5.14.0-1007-oem #7-Ubuntu
6639:Completed S3 cycle(s)
6676:================================= Iteration 24 =================================
6684:This test run on 06/12/21 at 21:46:01 on host Linux u 5.14.0-1007-oem #7-Ubuntu
6710:Completed S3 cycle(s)
6747:================================= Iteration 25 =================================
6755:This test run on 06/12/21 at 21:46:55 on host Linux u 5.14.0-1007-oem #7-Ubuntu
6781:Completed S3 cycle(s)
6818:================================= Iteration 26 =================================
6826:This test run on 06/12/21 at 21:47:49 on host Linux u 5.14.0-1007-oem #7-Ubuntu
6852:Completed S3 cycle(s)
6889:================================= Iteration 27 =================================
6897:This test run on 06/12/21 at 21:48:43 on host Linux u 5.14.0-1007-oem #7-Ubuntu
6923:Completed S3 cycle(s)
6960:================================= Iteration 28 =================================
6968:This test run on 06/12/21 at 21:49:37 on host Linux u 5.14.0-1007-oem #7-Ubuntu
6994:Completed S3 cycle(s)
7031:================================= Iteration 29 =================================
7039:This test run on 06/12/21 at 21:50:31 on host Linux u 5.14.0-1007-oem #7-Ubuntu
7065:Completed S3 cycle(s)
7102:================================= Iteration 30 =================================
7110:This test run on 06/12/21 at 21:51:25 on host Linux u 5.14.0-1007-oem #7-Ubuntu
7136:Completed S3 cycle(s)
...
```
Dec 06 21:52:56 u pm_test.py.desktop[1531]: [Desktop Entry]
Dec 06 21:52:56 u pm_test.py.desktop[1531]: Name=reboot test
Dec 06 21:52:56 u pm_test.py.desktop[1531]: Comment=Verify reboot works properly
Dec 06 21:52:56 u pm_test.py.desktop[1531]: Exec=sudo /usr/bin/python3 /usr/lib/plainbox-provider-checkbox/bin/pm_test.py -r 1 -w 0 --hardware-delay 30 --pm-delay 5 --min-pm-time 0 --max-pm-time 300 --append --to
Dec 06 21:52:56 u pm_test.py.desktop[1531]: Type=Application
Dec 06 21:52:56 u pm_test.py.desktop[1531]: X-GNOME-Autostart-enabled=true
Dec 06 21:52:56 u pm_test.py.desktop[1531]: Hidden=false
Dec 06 21:52:56 u pm_test.py.desktop[1531]: INFO reboot operations remaining: 2
Dec 06 21:52:56 u pm_test.py.desktop[1531]: INFO Reboot time: 0:27:41.716137
Dec 06 21:52:56 u pm_test.py.desktop[1531]: INFO Running suspend/resume cycles
Dec 06 21:52:56 u pm_test.py.desktop[1531]: DEBUG Executing: 'checkbox-support-fwts_test --log=/var/tmp/checkbox-ng/sessions/session_title-2021-12-06T10.25.57.session/session-share/fwts -s s3 --s3-device-check
```
7173:================================= Iteration 1 ==================================
7181:This test run on 06/12/21 at 21:52:56 on host Linux u 5.14.0-1007-oem #7-Ubuntu
7276:Completed S3 cycle(s)
7314:================================= Iteration 2 ==================================
7322:This test run on 06/12/21 at 21:53:50 on host Linux u 5.14.0-1007-oem #7-Ubuntu
7348:Completed S3 cycle(s)
7385:================================= Iteration 3 ==================================
7393:This test run on 06/12/21 at 21:54:44 on host Linux u 5.14.0-1007-oem #7-Ubuntu
7419:Completed S3 cycle(s)
7456:================================= Iteration 4 ==================================
7464:This test run on 06/12/21 at 21:55:38 on host Linux u 5.14.0-1007-oem #7-Ubuntu
7490:Completed S3 cycle(s)
7527:================================= Iteration 5 ==================================
7535:This test run on 06/12/21 at 21:56:32 on host Linux u 5.14.0-1007-oem #7-Ubuntu
7561:Completed S3 cycle(s)
7598:================================= Iteration 6 ==================================
7606:This test run on 06/12/21 at 21:57:26 on host Linux u 5.14.0-1007-oem #7-Ubuntu
7632:Completed S3 cycle(s)
7669:================================= Iteration 7 ==================================
7677:This test run on 06/12/21 at 21:58:20 on host Linux u 5.14.0-1007-oem #7-Ubuntu
7703:Completed S3 cycle(s)
7740:================================= Iteration 8 ==================================
7748:This test run on 06/12/21 at 21:59:14 on host Linux u 5.14.0-1007-oem #7-Ubuntu
7774:Completed S3 cycle(s)
7811:================================= Iteration 9 ==================================
7819:This test run on 06/12/21 at 22:00:08 on host Linux u 5.14.0-1007-oem #7-Ubuntu
7845:Completed S3 cycle(s)
7882:================================= Iteration 10 =================================
7890:This test run on 06/12/21 at 22:01:02 on host Linux u 5.14.0-1007-oem #7-Ubuntu
7916:Completed S3 cycle(s)
7953:================================= Iteration 11 =================================
7961:This test run on 06/12/21 at 22:01:56 on host Linux u 5.14.0-1007-oem #7-Ubuntu
7987:Completed S3 cycle(s)
8024:================================= Iteration 12 =================================
8032:This test run on 06/12/21 at 22:02:50 on host Linux u 5.14.0-1007-oem #7-Ubuntu
8058:Completed S3 cycle(s)
8095:================================= Iteration 13 =================================
8103:This test run on 06/12/21 at 22:03:44 on host Linux u 5.14.0-1007-oem #7-Ubuntu
8129:Completed S3 cycle(s)
8166:================================= Iteration 14 =================================
8174:This test run on 06/12/21 at 22:04:38 on host Linux u 5.14.0-1007-oem #7-Ubuntu
8200:Completed S3 cycle(s)
8237:================================= Iteration 15 =================================
8245:This test run on 06/12/21 at 22:05:32 on host Linux u 5.14.0-1007-oem #7-Ubuntu
8271:Completed S3 cycle(s)
8308:================================= Iteration 16 =================================
8316:This test run on 06/12/21 at 22:06:26 on host Linux u 5.14.0-1007-oem #7-Ubuntu
8342:Completed S3 cycle(s)
8379:================================= Iteration 17 =================================
8387:This test run on 06/12/21 at 22:07:20 on host Linux u 5.14.0-1007-oem #7-Ubuntu
8413:Completed S3 cycle(s)
8450:================================= Iteration 18 =================================
8458:This test run on 06/12/21 at 22:08:14 on host Linux u 5.14.0-1007-oem #7-Ubuntu
8484:Completed S3 cycle(s)
8521:================================= Iteration 19 =================================
8529:This test run on 06/12/21 at 22:09:08 on host Linux u 5.14.0-1007-oem #7-Ubuntu
8555:Completed S3 cycle(s)
8592:================================= Iteration 20 =================================
8600:This test run on 06/12/21 at 22:10:02 on host Linux u 5.14.0-1007-oem #7-Ubuntu
8626:Completed S3 cycle(s)
8663:================================= Iteration 21 =================================
8671:This test run on 06/12/21 at 22:10:56 on host Linux u 5.14.0-1007-oem #7-Ubuntu
8697:Completed S3 cycle(s)
8734:================================= Iteration 22 =================================
8742:This test run on 06/12/21 at 22:11:50 on host Linux u 5.14.0-1007-oem #7-Ubuntu
8768:Completed S3 cycle(s)
8805:================================= Iteration 23 =================================
8813:This test run on 06/12/21 at 22:12:44 on host Linux u 5.14.0-1007-oem #7-Ubuntu
8839:Completed S3 cycle(s)
8876:================================= Iteration 24 =================================
8884:This test run on 06/12/21 at 22:13:38 on host Linux u 5.14.0-1007-oem #7-Ubuntu
8910:Completed S3 cycle(s)
8947:================================= Iteration 25 =================================
8955:This test run on 06/12/21 at 22:14:32 on host Linux u 5.14.0-1007-oem #7-Ubuntu
8981:Completed S3 cycle(s)
9018:================================= Iteration 26 =================================
9026:This test run on 06/12/21 at 22:15:26 on host Linux u 5.14.0-1007-oem #7-Ubuntu
9052:Completed S3 cycle(s)
9089:================================= Iteration 27 =================================
9097:This test run on 06/12/21 at 22:16:20 on host Linux u 5.14.0-1007-oem #7-Ubuntu
9123:Completed S3 cycle(s)
9160:================================= Iteration 28 =================================
9168:This test run on 06/12/21 at 22:17:14 on host Linux u 5.14.0-1007-oem #7-Ubuntu
9194:Completed S3 cycle(s)
9231:================================= Iteration 29 =================================
9239:This test run on 06/12/21 at 22:18:08 on host Linux u 5.14.0-1007-oem #7-Ubuntu
9265:Completed S3 cycle(s)
9302:================================= Iteration 30 =================================
9310:This test run on 06/12/21 at 22:19:02 on host Linux u 5.14.0-1007-oem #7-Ubuntu
9336:Completed S3 cycle(s)
...
```
Dec 06 22:21:08 u pm_test.py.desktop[1533]: Name=reboot test
Dec 06 22:21:08 u pm_test.py.desktop[1533]: Comment=Verify reboot works properly
Dec 06 22:21:08 u pm_test.py.desktop[1533]: Exec=sudo /usr/bin/python3 /usr/lib/plainbox-provider-checkbox/bin/pm_test.py -r 0 -w 0 --hardware-delay 30 --pm-delay 5 --min-pm-time 0 --max-pm-time 300 --append --to
Dec 06 22:21:08 u pm_test.py.desktop[1533]: Type=Application
Dec 06 22:21:08 u pm_test.py.desktop[1533]: X-GNOME-Autostart-enabled=true
Dec 06 22:21:08 u pm_test.py.desktop[1533]: Hidden=false
Dec 06 22:21:08 u pm_test.py.desktop[1533]: INFO reboot operations remaining: 1
Dec 06 22:21:08 u pm_test.py.desktop[1533]: INFO Reboot time: 0:28:12.324568
Dec 06 22:21:08 u pm_test.py.desktop[1533]: INFO Running suspend/resume cycles
Dec 06 22:21:08 u pm_test.py.desktop[1533]: DEBUG Executing: 'checkbox-support-fwts_test --log=/var/tmp/checkbox-ng/sessions/session_title-2021-12-06T10.25.57.session/session-share/fwts -s s3 --s3-device-check
```
9373:================================= Iteration 1 ==================================
9381:This test run on 06/12/21 at 22:21:08 on host Linux u 5.14.0-1007-oem #7-Ubuntu
9849:Completed S3 cycle(s)
9888:================================= Iteration 2 ==================================
9896:This test run on 06/12/21 at 23:46:44 on host Linux u 5.14.0-1007-oem #7-Ubuntu
10374:Completed S3 cycle(s)
10412:================================= Iteration 3 ==================================
10420:This test run on 06/12/21 at 23:47:47 on host Linux u 5.14.0-1007-oem #7-Ubuntu
10868:Completed S3 cycle(s)
10907:================================= Iteration 4 ==================================
10915:This test run on 07/12/21 at 00:40:27 on host Linux u 5.14.0-1007-oem #7-Ubuntu

**Comment by yphus** [comment]
Power Management jobs have been reworked as part of https://github.com/canonical/checkbox/pull/477
