### ISSUE TITLE
LP1957011: Iperf SRU  Included in Network Only Tests.  

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#92]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1957011

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| In Progress	| 2022-01-10 21:46:39	| 6	| High	| False  	|

## Description
I noticed that an SRU Iperf test run was included with the network only launcher.  I assume this was included in error. 

https://certification.canonical.com/hardware/202112-29785/submission/239580/test-results/pass/

Apparently this was introduced in the following bug:

https://bugs.launchpad.net/plainbox-provider-certification-server/+bug/1944989

## Attachments
No attachments

Tags:
['cbox-18', 'servcert-213']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~bladernr wrote on 2022-01-11 21:33:22:
Grrr...stupid wildcard expansion...

**Comment by pieqq** [comment]
Fixed in Launchpad.
