### ISSUE TITLE
LP1966832: usb/storage-detect fails if run whole USB cases

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#94]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1966832

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2022-03-29 03:06:08	| 8	| High	| False  	|

## Description
usb/storage-detect fails if runs the category: com.canonical.plainbox::usb within client-cert-desktop-20-04 on some systems only has 1 USB port

the case put the end of whole USB cases after after-suspend-usb3/remove, it makes system under non-USB connected status then usb/storage-detect fails

-------------[ Running job 58 / 58. Estimated time left: unknown ]--------------
------------[ Detect storage partitions on a device on the USB bus ]------------
ID: com.canonical.certification::usb/storage-detect
Category: com.canonical.plainbox::usb
... 8< -------------------------------------------------------------------------
------------------------------------------------------------------------- >8 ---
Outcome: job failed

## Attachments
No attachments

Tags:
[]

**Comment by kissiel** [comment]
This looks like a very uncommon case. It's also difficult to understand fully what goes on here from the description provided. If the issue happens again, please feel free to open a new issue, or reopen this one. But please more context and information.
