### ISSUE TITLE
Add new CPUIDs to cpuid.py

### ISSUE THREAD

**Issue by bladernr** [canonical/checkbox#946]
### Enhancement Proposal

Add the following to the list in CPUID.py

Platform | CPUID | CPU Model
Intel Raptor Lake | 0xb0671 | Intel(R) Xeon(R) E E-2478
Intel Emerald Rapids | 0xc06f2 | INTEL(R) XEON(R) PLATINUM 8592+
AMD Siena SP6 | 0xaa0f02 | AMD Siena SP6

**Comment by rodwsmith** [comment]
Once this is done, the following will be done, too:
https://github.com/canonical/checkbox/issues/945
