### ISSUE TITLE
LP1971658: Checkbox fail to run graphics/2_auto_switch_card_* on two specific system.

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#96]
This issue was migrated from https://bugs.launchpad.net/checkbox-ng/+bug/1971658

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2022-05-05 06:00:41	| 6	| High	| False  	|

## Description
Please see http://10.102.156.15:8080/job/cert-stock-sru-impish-desktop-z2-sff-g8-workstation-28728/19/console and http://10.102.156.15:8080/job/cert-stock-sru-impish-desktop-z2-sff-g8-workstation-28727/22/console

I’m not sure why only happen on these two system.
It fails to run on every release(Focal-hwe, Impish, Focal-oem, Jammy)

I've also created a jira card for tracking at https://warthogs.atlassian.net/browse/CER-1884

## Attachments
No attachments

Tags:
[]

**Comment by yphus** [comment]
Reworking graphic cards test is now tracked [here](https://warthogs.atlassian.net/browse/CHECKBOX-643)
