### ISSUE TITLE
`ubuntu_core_features` fail when running on non-core image

### ISSUE THREAD

**Issue by LiaoU3** [canonical/checkbox#963]
### Bug Description

The resource job `ubuntu_core_features` fail when running on non-core image.

This issue happens because the resource job `ubuntu_core_features` is using by `kernel-snap/booted-kernel-matches-current-{name}`, and it' under `kernel-snap-automated` testplan, and it's nested by iot core automated testplan `client-cert-iot-ubuntucore-22-automated`, and it's nested by iot server testplan `client-cert-iot-server-22-04-automated`.

The structure is like this below:
```
iot server automated testplan
|-- iot core automated testplan
    |-- kernel-snap-automated
        |-- kernel-snap/booted-kernel-matches-current-{name}
            |-- ubuntu_core_features
```
The Server testplan will include `ubuntu_core_features`  resource job which is not supported on server image.
Hence I have 3 proposal:
1. Add a condition check in `ubuntu_core_features` like `{%- if __on_ubuntucore__ %}`.
2. Exclude `ubuntu_core_features` in iot server testplan.
3. Diverge the server and core testplan.

### To Reproduce

1. Install [server image](https://releases.ubuntu.com/22.04.3/ubuntu-22.04.3-live-server-amd64.iso) on the DUT.
2. Install checkbox
   1. sudo snap install checkbox22 --beta
   2. sudo snap install checkbox --beta --classic
3. Execute iot server testplan or run `ubuntu_core_features`
    - checkbox.checkbox-cli run com.canonical.certification::client-cert-iot-server-22-04-automated
    - checkbox.checkbox-cli run com.canonical.certification::ubuntu_core_features

### Environment

- OS Server 22.04
- Checkbox Type: Snap
- Checkbox Version: Beta (3.3.0-dev19)

### Relevant log output

```shell
ubuntu@ubuntu:~$ checkbox-baytown-classic.checkbox-cli run com.canonical.certification::ubuntu_core_features
$PROVIDERPATH is defined, so following provider sources are ignored ['/snap/checkbox-baytown-classic/9/providers/checkbox-provider-baytown', '/home/ubuntu/.local/share/plainbox-providers-1', '/var/tmp/checkbox-providers-develop'] 
===========================[ Running Selected Jobs ]============================
==============[ Running job 1 / 1. Estimated time left: 0:00:01 ]===============
--------[ Indicate whether product features of Ubuntu Core are enabled ]--------
ID: com.canonical.certification::ubuntu_core_features
Category: com.canonical.plainbox::uncategorised
... 8< -------------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nest-kr1sfgya.94fbbb8045a17d92b4defb5d82d4afacbb4abdd81525126e8c15ab7d65b0e986/snapd_resource.py", line 209, in <module>
    SnapdResource().main()
  File "/tmp/nest-kr1sfgya.94fbbb8045a17d92b4defb5d82d4afacbb4abdd81525126e8c15ab7d65b0e986/snapd_resource.py", line 205, in main
    actions[args.action]().invoked()
  File "/tmp/nest-kr1sfgya.94fbbb8045a17d92b4defb5d82d4afacbb4abdd81525126e8c15ab7d65b0e986/snapd_resource.py", line 169, in invoked
    self._detect_kernel_extraction()
  File "/tmp/nest-kr1sfgya.94fbbb8045a17d92b4defb5d82d4afacbb4abdd81525126e8c15ab7d65b0e986/snapd_resource.py", line 181, in _detect_kernel_extraction
    if int(get_series()) >= 20:
ValueError: invalid literal for int() with base 10: '22.04'
------------------------------------------------------------------------- >8 ---
Outcome: job failed
Finalizing session that hasn't been submitted anywhere: checkbox-run-2024-01-24T03.31.49
==================================[ Results ]===================================
 ☒ : Indicate whether product features of Ubuntu Core are enabled
```
```


### Additional context

_No response_

**Comment by pieqq** [comment]
These test plans were started when the assumption was that IoT devices would all run Ubuntu Core. This is obviously not correct anymore.

After a discussion with @kissiel, the plan here is to separate the test plan into a core-only jobs, and generic IoT jobs.

**Comment by pieqq** [comment]
After investigating a bit, I don't think splitting test plans is a good idea.

The job that creates this issue is from `kernel-snap-automated` test plan. We already have classic images with kernel snaps, meaning it's not that trivial to separate "ubuntucore-only" stuff from "generic" stuff.

It's probably better to fix the problem at the root.

**Comment by LiaoU3** [comment]
Just did a quick test on my computer (Desktop 23.10), this is fixed now.

checkbox                   4.0.0-dev194                6361   latest/edge      ce-certification-qa  classic
checkbox22                 4.0.0-dev194                866    latest/edge      ce-certification-qa  -

```terminal
(base) vincent@vincent-XPS-9320:~$ checkbox.checkbox-cli run com.canonical.certification::ubuntu_core_features
$PROVIDERPATH is defined, so following provider sources are ignored ['/home/vincent/.local/share/plainbox-providers-1', '/var/tmp/checkbox-providers-develop'] 
Skipped file: /snap/checkbox22/current/providers/checkbox-provider-base/units/stress/suspend_cycles_reboot.md
===========================[ Running Selected Jobs ]============================
==============[ Running job 1 / 1. Estimated time left: 0:00:01 ]===============
--------[ Indicate whether product features of Ubuntu Core are enabled ]--------
ID: com.canonical.certification::ubuntu_core_features
Category: com.canonical.certification::information_gathering
... 8< -------------------------------------------------------------------------
force_kernel_extraction: False

------------------------------------------------------------------------- >8 ---
Outcome: job passed
Finalizing session that hasn't been submitted anywhere: checkbox-run-2024-03-26T03.27.08
==================================[ Results ]===================================
 ☑ : Indicate whether product features of Ubuntu Core are enabled
```
