### ISSUE TITLE
LP1974209: Unable to detect the insertion of TBT3 storage

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#97]
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-checkbox/+bug/1974209

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Incomplete	| 2022-05-19 15:36:43	| 6	| High	| False  	|

## Description
[Summary]
checkbox-cli cannot detect the insertion of TBT3 storage.
However, system can detect and access it without problem.

screenshot: https://drive.google.com/file/d/1toDC-DPg1ipB62-TpG5-0Uxj5cUB2udM/view?usp=sharing

[Steps to reproduce]
1. Boot into OS
2. Run "checkbox-cli run com.canonical.certification::thunderbolt3/insert"
3. Follow the steps to insert TBT3 storage

[Expected result]
checkbox-cli can detect the TBT3 storage.

[Actual result]
checkbox-cli cannot detect the TBT3 storage.

I/O logs:

INSERT NOW

/tmp/nest-lzry0nu5.6bc01a9b6b0687602c09bf237634540db1ee4c24bf56fb1e9a8066d49c444cda/removable_storage_watcher.py:497: PyGIDeprecationWarning: GObject.timeout_add_seconds is deprecated; use GLib.timeout_add_seconds instead
  GObject.timeout_add_seconds(timeout, self._on_timeout_expired)
You have failed to perform the required manipulation in time

[Failure rate]
3/3

[Additional information]
CID: 202112-29802
SKU: TRBA-DVT2-C4
Image: canonical-oem-somerville-jammy-amd64-20220425-25+jellyfish-tentacool+X17
system-manufacturer: Dell Inc.
system-product-name: XPS 9320
bios-version: 0.2.15
CPU: 12th Gen Intel(R) Core(TM) i7-1280P (20x)
GPU: 0000:00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:46a6] (rev 0c)
kernel-version: 5.15.0-9027-generic

[Stage]
Issue reported and logs collected at a later stage

## Attachments
No attachments

Tags:
['jammy-test']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~pieq wrote on 2022-05-24 07:43:10:
Importance set to High because it is still possible to check this manually.

@Patrick, can you record the output of `journalctl -f` while inserting a TBT3 storage into this device?

1. In a terminal, run `journalctl -f`
2. Insert TBT3, and make sure user can access it
3. In the terminal, stop `journalctl -f` by pressing Ctrl+C, copy the output in a log file and attach it here.

**Comment by kissiel** [comment]
Turns out @amalinowski75  doesn't have the tb enclosure, reassigning to me.
