### ISSUE TITLE
Some audio cases are skipped since device.category=="AUDIO" doesn't match

### ISSUE THREAD

**Issue by baconYao** [canonical/checkbox#971]
### Bug Description

Some Audio cases from Mono Checkbox are skipped since they don't meet the requirement, "device.category == 'AUDIO'"

Skipped cases
- client-cert-desktop-22-04-automated: https://certification.canonical.com/hardware/202312-33205/submission/353580/test-results/skipped/
- client-cert-desktop-22-04-manual: https://certification.canonical.com/hardware/202312-33205/submission/353582/test-results/skipped/

### To Reproduce

1. Flash genio-classic-desktop-2204-20240122-162.img
2. Install Checkbox via the following command
   ```
   $ sudo install checkbox22 --beta
   $ sudo install checkbox --beta --classic
   ```
3. Run the following two Test Plans via checkbox control
   - client-cert-desktop-22-04-automated
   - client-cert-desktop-22-04-manual
4. Run the Audio Set

### Environment

CID: 202312-33205
OS: Jammy Classic Desktop image
Checkbox Type: Snap
Checkbox Version: checkbox22 3.3.0-dev19 727 latest/beta ce-certification-qa -

**Comment by baconYao** [comment]
Similar issue #563

**Comment by baconYao** [comment]
Here are the Audio information from Medaitek
- G1200: https://mediatek.gitlab.io/aiot/doc/aiot-dev-guide/master/sw/yocto/app-dev/audio/audio-g1200-evk.html
- G510 & G700: https://mediatek.gitlab.io/aiot/doc/aiot-dev-guide/master/sw/yocto/app-dev/audio/audio-g700-evk.html#overview
- G350: https://mediatek.gitlab.io/aiot/doc/aiot-dev-guide/master/sw/yocto/app-dev/audio/audio-i350-evk.html

I believe them will be helpful for this issue.

**Comment by kissiel** [comment]
Let's add a manifest entry for audio card. Let's switch the requires field to require the manifest entry.

**Comment by baconYao** [comment]
Verify Pass on G510 Desktop (2024_03_19)
  - submission: https://certification.canonical.com/hardware/202405-34024/submission/384469/

```bash
ubuntu@mtk-genio:~$ snap list
Name                       Version             Rev    Tracking         Publisher            Notes
bare                       1.0                 5      latest/stable    canonical✓           base
bugit                      1.2                 35     latest/stable    pieq                 devmode
checkbox                   4.1.0-dev25         7796   22.04/beta       ce-certification-qa  classic
checkbox-ce-oem            1.0-jammy           425    22.04/edge       ce-certification-qa  classic
checkbox22                 4.1.0-dev25         1025   latest/beta      ce-certification-qa  -

```
