### ISSUE TITLE
Job check_prerelease failed since Kernel is not from main Ubuntu repository 

### ISSUE THREAD

**Issue by baconYao** [canonical/checkbox#977]
### Bug Description

In Baoshan Project, I ran into issue ([LP#2025702](https://bugs.launchpad.net/baoshan/+bug/2025702)) to check if the Kernel is eligible for certification or not.

However, current checkpoint is stick to [main](https://github.com/canonical/checkbox/blob/ddb7aa82cef972d6df0b4ff0bcb16d67fd40302a/providers/base/bin/check_prerelease.py#L56) Ubuntu repository only.

After discussion with HWE, SWE, PE and QA team, we ensure that all Silicon Partner Kernel should not be main, which means the current Kernel state, **_universe_**, is the proper Ubuntu repository.

Reference Jira Card: https://warthogs.atlassian.net/browse/OEMQA-3922

### To Reproduce

1. Install testing image
2. Install checkbox22 via command `sudo snap install checkbox22 --beta`
3. Install checkbox via command `sudo snap install checkbox --beta --devmode`
4. Run command `$ checkbox.checkbox-cli run com.canonical.certification::miscellanea/check_prerelease`

### Environment

- CID: 202307-31859
- OS: Jammy Classic Desktop Image (iot-baoshan-classic-desktop-2204-x01-20231005-133)
- Checkbox Type: Snap
- Checkbox Version: checkbox22 3.3.0-dev19 727

**Comment by zongminl** [comment]
@baconYao Do you think this issue can be closed as #978 is merged?
