### ISSUE TITLE
LP1981090: Test should fail if nvidia drivers are not loaded

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#98]
This issue was migrated from https://bugs.launchpad.net/checkbox-provider-gpgpu/+bug/1981090

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| In Progress	| 2022-07-08 15:18:22	| 6	| High	| False  	|

## Description
If the nvidia drivers are not loaded at runtime, the test itself will error out but will still be marked as PASS.

This test should be marked fail if the nvidia compute drivers are not loaded.

https://certification.canonical.com/hardware/202206-30404/submission/270289/test/81282/result/26835378/

terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
read[0] error 0

No clients are alive!  Aborting
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
Burning for 14400 seconds.

After spitting out that error, the test is completed with an exit code of 0 and looks like a pass when it is not.

## Attachments
No attachments

Tags:
['servcert-406']

**Comment by beliaev-maksim** [comment]
This thread was migrated from launchpad.net
##### https://launchpad.net/~zhanglei-mao wrote on 2022-07-12 02:17:57:
The partner also reported that he have to disable secure boot, then nvidia driver was loaded and test-gpu can be passed. 

root@crack-bengal:~#  lsmod |grep nvidia

nvidia_uvm           1126400  2

nvidia_drm             57344  0

nvidia_modeset       1138688  1 nvidia_drm

nvidia              40738816  148 nvidia_uvm,nvidia_modeset

drm_kms_helper        172032  2 ast,nvidia_drm

drm                   401408  6 drm_kms_helper,ast,nvidia,nvidia_drm,ttm

**Comment by pieqq** [comment]
Marked as "Rejected" in Jira, closing here.
