### ISSUE TITLE
Misuse of `after` for the after suspend jobs `maxfreq_test-log-attach` and `scaling_test-log-attach`

### ISSUE THREAD

**Issue by LiaoU3** [canonical/checkbox#996]
### Bug Description

Since we are now using `after` for [after-suspend-cpu/maxfreq_test-log-attach](https://github.com/canonical/checkbox/blob/c345eee07c9d04d5406fe466300efd32fa150b9f/providers/base/units/cpu/jobs.pxu#L119) and [after-suspend-cpu/scaling_test-log-attach](https://github.com/canonical/checkbox/blob/c345eee07c9d04d5406fe466300efd32fa150b9f/providers/base/units/cpu/jobs.pxu#L59), if the aftered jobs fail, these 2 jobs will still run and fail.
However in the original non-after-suspend jobs, [cpu/scaling_test-log-attach](https://github.com/canonical/checkbox/blob/c345eee07c9d04d5406fe466300efd32fa150b9f/providers/base/units/cpu/jobs.pxu#L48) and [cpu/maxfreq_test-log-attach](https://github.com/canonical/checkbox/blob/c345eee07c9d04d5406fe466300efd32fa150b9f/providers/base/units/cpu/jobs.pxu#L108), we use `depeneds` instead of `after`.
Maybe we accidentally code it as `after`?

Submission: https://certification.canonical.com/hardware/202307-31833/submission/325311/

### To Reproduce

1. checkbox.checkbox-cli run com.canonical.certification::after-suspend-cpu-cert-automated

### Environment

-  Prepare a DUT which does not support scaling_test and maxfreq_test.

**Comment by weizhenwu** [comment]
@LiaoU3 
I might mixed up `after` with `depend`.
Agreed with you that we should follow the original test cases to use `depend`
